force-app/main/default/objects/animalos__Area__c/animalos__Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Area__c/fields/animalos__Parent_Area__c.field-meta.xml
<CustomField>
    <fullName>animalos__Parent_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Area</label>
    <referenceTo>animalos__Area__c</referenceTo>
    <relationshipLabel>Areas</relationshipLabel>
    <relationshipName>Child_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Area__c.field-meta.xml
<CustomField>
    <fullName>animalos__Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>animalos__Area__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Codes__c.field-meta.xml
<CustomField>
    <fullName>animalos__Codes__c</fullName>
    <label>Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Advertisement of an Animal</fullName>
            </value>
            <value>
                <fullName>AH Owner Medical Assist</fullName>
            </value>
            <value>
                <fullName>Animal fighting/Prohibited event</fullName>
            </value>
            <value>
                <fullName>Animal in hot vehicle</fullName>
            </value>
            <value>
                <fullName>Animal Unattended</fullName>
            </value>
            <value>
                <fullName>Assistance Request - Animal Owner</fullName>
            </value>
            <value>
                <fullName>Assistance Request - HEA Bequest</fullName>
            </value>
            <value>
                <fullName>Assistance Request - Inspectorate</fullName>
            </value>
            <value>
                <fullName>Assistance Request - Provide Emergency Relief</fullName>
            </value>
            <value>
                <fullName>Assistance Request - Shelter</fullName>
            </value>
            <value>
                <fullName>Baiting</fullName>
            </value>
            <value>
                <fullName>Cause Captive Animal To Be Injured/killed By Dog</fullName>
            </value>
            <value>
                <fullName>Cruelty</fullName>
            </value>
            <value>
                <fullName>Dog/Cat Attack</fullName>
                <label>Dog/cat Attack</label>
            </value>
            <value>
                <fullName>Emergency - Fire Event</fullName>
            </value>
            <value>
                <fullName>Emergency - Flood Event</fullName>
            </value>
            <value>
                <fullName>Emergency - Heat Related</fullName>
            </value>
            <value>
                <fullName>Emergency - Oiled Wildlife</fullName>
            </value>
            <value>
                <fullName>Emergency Relief</fullName>
            </value>
            <value>
                <fullName>Entanglement - Fishing Line</fullName>
            </value>
            <value>
                <fullName>Entanglement - Other</fullName>
            </value>
            <value>
                <fullName>Flighted Bird</fullName>
            </value>
            <value>
                <fullName>Food &amp; Water</fullName>
            </value>
            <value>
                <fullName>Greyhound Complaint</fullName>
            </value>
            <value>
                <fullName>HEA Bequest Assistance Request</fullName>
            </value>
            <value>
                <fullName>Heat Distress</fullName>
            </value>
            <value>
                <fullName>Heat Related</fullName>
            </value>
            <value>
                <fullName>Hit By Car</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Important_Notes__c.field-meta.xml
<CustomField>
    <fullName>animalos__Important_Notes__c</fullName>
    <label>Important Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Location_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location_Of_Interest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Of Interest</label>
    <referenceTo>animalos__Location_Of_Interest__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Observed_Physical_Violence__c.field-meta.xml
<CustomField>
    <fullName>animalos__Observed_Physical_Violence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Observed Physical Violence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Observed_Verbal_Abuse__c.field-meta.xml
<CustomField>
    <fullName>animalos__Observed_Verbal_Abuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Observed Verbal Abuse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Priority__c.field-meta.xml
<CustomField>
    <fullName>animalos__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>No Incident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Reported_Physical_Violence__c.field-meta.xml
<CustomField>
    <fullName>animalos__Reported_Physical_Violence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reported Physical Violence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Reported_Verbal_Abuse__c.field-meta.xml
<CustomField>
    <fullName>animalos__Reported_Verbal_Abuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reported Verbal Abuse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/animalos__Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC{0000000}</displayFormat>
        <label>Job Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Contact_Jobs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact_Type__c</fullName>
    <label>Contact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Informant</fullName>
            </value>
            <value>
                <fullName>Informant Secondary</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Person Of Interest</fullName>
            </value>
            <value>
                <fullName>POI Secondary</fullName>
            </value>
            <value>
                <fullName>Police Officer</fullName>
            </value>
            <value>
                <fullName>Rescuer</fullName>
            </value>
            <value>
                <fullName>Spoken to</fullName>
            </value>
            <value>
                <fullName>Subject animal owner</fullName>
            </value>
            <value>
                <fullName>Subject property owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>Witness Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Observed_Physical_Violence__c.field-meta.xml
<CustomField>
    <fullName>animalos__Observed_Physical_Violence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Observed Physical Violence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Observed_Verbal_Abuse__c.field-meta.xml
<CustomField>
    <fullName>animalos__Observed_Verbal_Abuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Observed Verbal Abuse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Reported_Physical_Violence__c.field-meta.xml
<CustomField>
    <fullName>animalos__Reported_Physical_Violence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reported Physical Violence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Reported_Verbal_Abuse__c.field-meta.xml
<CustomField>
    <fullName>animalos__Reported_Verbal_Abuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reported Verbal Abuse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/animalos__Location_Of_Interest__c.object-meta.xml
<CustomObject>
    <label>Location Of Interest</label>
    <nameField>
        <label>Location Of Interest</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location_Of_Interest__c/fields/animalos__Observed_Physical_Violence__c.field-meta.xml
<CustomField>
    <fullName>animalos__Observed_Physical_Violence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Observed Physical Violence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/fields/animalos__Observed_Verbal_Abuse__c.field-meta.xml
<CustomField>
    <fullName>animalos__Observed_Verbal_Abuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Observed Verbal Abuse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/fields/animalos__Reported_Physical_Violence__c.field-meta.xml
<CustomField>
    <fullName>animalos__Reported_Physical_Violence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reported Physical Violence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/fields/animalos__Reported_Verbal_Abuse__c.field-meta.xml
<CustomField>
    <fullName>animalos__Reported_Verbal_Abuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reported Verbal Abuse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/aos_VolunteerRescueReqReceiptMetaProc.cls
public class aos_VolunteerRescueReqReceiptMetaProc extends aos_MetadataProcessor {

    public override aos_Response process(aos_Request request) {
        this.request = request == null ? new MetadataRequest() : (MetadataRequest) request;

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {

        this.response.dto.putAll(new Map<String, Object>{
                'page-styles' => 'margin-top: 0.3in; margin-bottom: 0.3in',
                'font-family' => '"Arial", sans-serif',
                'renderAs' => aos_Utils.objects.defaultIfNull(this.request.getString('renderAs'), 'html')
        });

        String jobId = this.request.getString('jobId');
        aos_Utils.objects.throwIfBlank(jobId, 'No jobId param');

        String contactId = this.request.getString('contactId');
        aos_Utils.objects.throwIfBlank(contactId, 'No contactId param');

        Contact contactVar = (Contact) aos_Utils.arrays.firstOrException([
            SELECT Id, Name
            FROM Contact
            WHERE Id = :contactId
        ]);

        animalos__Job__c jobVar = (animalos__Job__c) aos_Utils.arrays.firstOrException([
            SELECT Id
                ,Name
                ,animalos__Address__City__s
                ,animalos__Priority__c
                ,CreatedDate
                ,animalos__Area__r.animalos__Parent_Area__r.Name
                ,animalos__Area__r.Name
                ,animalos__Codes__c
                ,CreatedBy.Name
                ,animalos__Important_Notes__c
                ,animalos__Location_Of_Interest__c
                ,animalos__Reported_Physical_Violence__c
                ,animalos__Observed_Physical_Violence__c
                ,animalos__Reported_Verbal_Abuse__c
                ,animalos__Observed_Verbal_Abuse__c
            FROM animalos__Job__c
            WHERE Id = :jobId
        ]);

        String jobCodesSplitted;

        if (String.isNotBlank(jobVar.animalos__Codes__c)) {
            jobCodesSplitted = String.join(new List<String>(jobVar.animalos__Codes__c.split(';')), ', ');
        }

        List<animalos__Job_Contact__c> jobContactsVar = [
            SELECT Id
                ,Name
                ,animalos__Contact__c
                ,animalos__Contact__r.Name
                ,animalos__Contact__r.MailingStreet
                ,animalos__Contact__r.MailingCity
                ,animalos__Contact__r.MailingState
                ,animalos__Contact__r.MailingPostalCode
                ,animalos__Contact__r.Phone
                ,animalos__Contact__r.Email
                ,animalos__Contact_Type__c
                ,animalos__Reported_Physical_Violence__c
                ,animalos__Observed_Physical_Violence__c
                ,animalos__Reported_Verbal_Abuse__c
                ,animalos__Observed_Verbal_Abuse__c
            FROM animalos__Job_Contact__c
            WHERE animalos__Job__c = :jobVar.Id
        ];

        animalos__Location_Of_Interest__c locationOfInterestVar = (animalos__Location_Of_Interest__c) aos_Utils.arrays.firstOrDefault([
            SELECT Id
                ,Name
                ,animalos__Reported_Physical_Violence__c
                ,animalos__Observed_Physical_Violence__c
                ,animalos__Reported_Verbal_Abuse__c
                ,animalos__Observed_Verbal_Abuse__c
            FROM animalos__Location_Of_Interest__c
            WHERE Id = :jobVar.animalos__Location_Of_Interest__c
        ], new animalos__Location_Of_Interest__c());

        Integer locationOfInterestJobCount = [SELECT Count() FROM animalos__Job__c WHERE animalos__Location_Of_Interest__c = :locationOfInterestVar.Id];

        List<Object> components = new List<Object>();

        aos_DTO dto = new aos_DTO();

        dto.put('contact', contactVar);
        dto.put('job', jobVar);
        dto.put('jobContacts', jobContactsVar);
        dto.put('locationOfInterest', locationOfInterestVar);
        dto.put('locationOfInterestJobCount', locationOfInterestJobCount);
        dto.put('jobCodesSplitted', jobCodesSplitted);
        dto.put('todayFormatted', system.today().format());
        dto.put('renderAs', aos_Utils.objects.defaultIfNull(this.request.getString('renderAs'), 'html'));

        components.add(this.setTemplate(dto));

        this.response.dto.put('components', components);
        this.response.dto.put('head-component', new Component.aos_VolunteerRescueRequestReceiptStyles());

        System.debug(this.response.dto);
    }

    private Object setTemplate(aos_DTO dto){
        return new Component.aos_VolunteerRescueRequestReceipt(
                dto = dto.getMap()
        );
    }
}