force-app/main/default/objects/animalos__Alert__c/animalos__Alert__c.object-meta.xml
<CustomObject>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL{00000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Active__c.field-meta.xml
<CustomField>
    <fullName>animalos__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Alert_Message__c.field-meta.xml
<CustomField>
    <fullName>animalos__Alert_Message__c</fullName>
    <label>Alert Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Display_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>animalos__Display_Created_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows the Alert creation date</description>
    <label>Display Created Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Message_Formatted__c.field-meta.xml
<CustomField>
    <fullName>animalos__Message_Formatted__c</fullName>
    <label>Message Formatted</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Modal_Button_Label__c.field-meta.xml
<CustomField>
    <fullName>animalos__Modal_Button_Label__c</fullName>
    <defaultValue>&apos;Acknowledge&apos;</defaultValue>
    <label>Modal Button Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Modal_Title__c.field-meta.xml
<CustomField>
    <fullName>animalos__Modal_Title__c</fullName>
    <label>Modal Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Mode__c.field-meta.xml
<CustomField>
    <fullName>animalos__Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dismissible</fullName>
            </value>
            <value>
                <fullName>Sticky</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Style__c.field-meta.xml
<CustomField>
    <fullName>animalos__Style__c</fullName>
    <label>Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alert</fullName>
            </value>
            <value>
                <fullName>Toast</fullName>
            </value>
            <value>
                <fullName>Modal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Target_Object__c.field-meta.xml
<CustomField>
    <fullName>animalos__Target_Object__c</fullName>
    <label>Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Target_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>animalos__Target_Record_Id__c</fullName>
    <label>Target Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Variant__c.field-meta.xml
<CustomField>
    <fullName>animalos__Variant__c</fullName>
    <label>Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>Danger</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>aos_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>HEA Animals</relationshipLabel>
    <relationshipName>aos_HEA_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AnimalHEAAlert.cls
global class TDTM_aos_AnimalHEAAlert extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert, animalos.TDTM.AfterUpdate {

    public void onAfterInsert(List<SObject> records) {
        createHEAAnimalAlert(records, null);
    }

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        createHEAAnimalAlert(records, oldMap);
    }

    private void createHEAAnimalAlert(List<SObject> records, Map<Id, SObject> existingRecords) {
        List<animalos__Alert__c> animalAlertsForUpsert = new List<animalos__Alert__c>();
        Set<String> animalIds = aos_Utils.sObjects.getStringFieldValues(records, animalos__Animal__c.Id);

        Map<String, SObject> activeAnimalAlertByAnimalId = aos_Utils.sObjects.getSObjectsByAnyFieldMap([
            SELECT Id, animalos__Target_Record_Id__c, animalos__Alert_Message__c
            FROM animalos__Alert__c
            WHERE animalos__Target_Record_Id__c IN :animalIds AND animalos__Alert_Message__c = 'This is a HEA/BEQUEST pet.  DO NOT EUTHANISE.  VETS, please read animal notes. Any concerns please contact Fundraising on 1300 777 221.'
            AND animalos__Start_Date_Time__c <= TODAY AND (animalos__End_Date_Time__c = NULL OR animalos__End_Date_Time__c > TODAY)
        ], animalos__Alert__c.animalos__Target_Record_Id__c);

        for (animalos__Animal__c animal : (List<animalos__Animal__c>) records) {

            Boolean isCreated = Trigger.isInsert && existingRecords == null;
            Boolean isUpdated = Trigger.isUpdate && existingRecords != null && aos_Utils.sObjects.isSomeFieldChanged(
                animal, existingRecords.get(animal.Id), new List<SObjectField>{
                    animalos__Animal__c.aos_Opportunity__c
                }
            );

            if ((isCreated || isUpdated) && animal.aos_Opportunity__c != null) {
                animalAlertsForUpsert.add(
                    new animalos__Alert__c(
                        animalos__Target_Record_Id__c = animal.Id,
                        animalos__Alert_Message__c = 'This is a HEA/BEQUEST pet.  DO NOT EUTHANISE.  VETS, please read animal notes. Any concerns please contact Fundraising on 1300 777 221.',
                        animalos__Message_Formatted__c = '<p><b>This is a HEA/BEQUEST pet.  DO NOT EUTHANISE.  VETS, please read animal notes. Any concerns please contact Fundraising on 1300 777 221.</b></p>',
                        animalos__Start_Date_Time__c = Datetime.now(),
                        animalos__Active__c = true,
                        animalos__Display_Created_Date__c = false,
                        animalos__Modal_Button_Label__c = 'Acknowledge',
                        animalos__Modal_Title__c = 'Alert',
                        animalos__Mode__c = 'Sticky',
                        animalos__Style__c = 'Alert',
                        animalos__Target_Object__c = 'animalos__animal__c',
                        animalos__Variant__c = 'Error'
                    )
                );
            } else if (isUpdated && animal.aos_Opportunity__c == null) {
                animalos__Alert__c activeAlert = (animalos__Alert__c) activeAnimalAlertByAnimalId.get(animal.Id);
                if (activeAlert != null) {
                    activeAlert.animalos__End_Date_Time__c = Datetime.now();
                    activeAlert.animalos__Active__c = false;
                    animalAlertsForUpsert.add(activeAlert);
                }
            }
        }

        upsert animalAlertsForUpsert;
    }
}