force-app/main/default/objects/animalos__Alert__c/animalos__Alert__c.object-meta.xml
<CustomObject>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL{00000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Target_Object__c.field-meta.xml
<CustomField>
    <fullName>animalos__Target_Object__c</fullName>
    <label>Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Target_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>animalos__Target_Record_Id__c</fullName>
    <label>Target Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/animalos_AlertDomain.cls
public without sharing class animalos_AlertDomain extends fflib_SObjectDomain implements fflib_ISObjectDomain {

    public animalos_AlertDomain(List<sObject> sObjectList) {
        super(sObjectList);
        this.Configuration.disableTriggerCRUDSecurity();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new animalos_AlertDomain(sObjectList);
        }
    }

    public override void onBeforeInsert() {
        this.populateAnimalLookupField(this.Records);
    }

    public override void onAfterInsert() {
    }
    

    public void populateAnimalLookupField(List<sObject> records) {

        for (animalos__Alert__c alert : (List<animalos__Alert__c>) records) {

            if (String.isNotBlank(alert.animalos__Target_Record_Id__c) && 'animalos__Animal__c'.equalsIgnoreCase(alert.animalos__Target_Object__c)) {
                alert.Animal__c = alert.animalos__Target_Record_Id__c;
            }
        }
    }
}