force-app/main/default/objects/animalos__Alert__c/animalos__Alert__c.object-meta.xml
<CustomObject>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL{00000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Target_Object__c.field-meta.xml
<CustomField>
    <fullName>animalos__Target_Object__c</fullName>
    <label>Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Alert__c/fields/animalos__Target_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>animalos__Target_Record_Id__c</fullName>
    <label>Target Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Unit__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Unit</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Unit Animals</relationshipLabel>
    <relationshipName>Unit_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AlertDomain.cls
public without sharing class AlertDomain extends fflib_SObjectDomain implements fflib_ISObjectDomain {

    public AlertDomain(List<animalos__Alert__c> sObjectList) {
        super(sObjectList);
        this.Configuration.disableTriggerCRUDSecurity();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new AlertDomain(sObjectList);
        }
    }

    public override void onAfterInsert() {
        this.shareRecords(this.Records, new Map<Id, animalos__Alert__c>());
    }

    private void shareRecords(List<animalos__Alert__c> alerts, Map<Id, animalos__Alert__c> existingAlertsByIds) {
        Set<Id> animalIds = new Set<Id>();

        for (animalos__Alert__c alertVar : alerts) {
            if ('animalos__Animal__c'.equalsIgnoreCase(alertVar.animalos__Target_Object__c) && String.isNotBlank('animalos__Target_Record_Id__c')) {
                animalIds.add(alertVar.animalos__Target_Record_Id__c);
            }
        }

        Map<Id, animalos__Animal__c> animalsByIds = new Map<Id, animalos__Animal__c>([
                SELECT Id, animalos__Current_Site__c, animalos__Current_Unit__c
                FROM animalos__Animal__c
                WHERE Id IN :animalIds
        ]);

        if(!animalsByIds.isEmpty()) {
            Set<Id> locationIds = new Set<Id>();
            locationIds.addAll(vertic_Utils.sObjects.getIdFieldValues(animalsByIds.values(), animalos__Animal__c.animalos__Current_Site__c));
            locationIds.addAll(vertic_Utils.sObjects.getIdFieldValues(animalsByIds.values(), animalos__Animal__c.animalos__Current_Unit__c));

            List<Location_Volunteer__c> existingLocationVolunteers = [
                    SELECT Id, Volunteer__c, Location__c
                    FROM Location_Volunteer__c
                    WHERE Location__c IN :locationIds
            ];

            if (!existingLocationVolunteers.isEmpty()) {
                Map<String, List<SObject>> existingLocationVolunteersByLocations = vertic_Utils.sObjects.getSObjectsListByAnyFieldMap(existingLocationVolunteers, Location_Volunteer__c.Location__c);
                Set<Id> contactIds = vertic_Utils.sObjects.getIdFieldValues(existingLocationVolunteers, Location_Volunteer__c.Volunteer__c);

                Map<String, SObject> usersByContactIds = vertic_Utils.sObjects.getSObjectsByAnyFieldMap([
                        SELECT Id, ContactId
                        FROM User
                        WHERE ContactId IN :contactIds
                        AND Profile.Name IN ('Partners Portal Volunteer User Plus', 'Foster Carer Portal User Plus')
                ], Schema.User.ContactId);

                List<animalos__Alert__Share> shareRecordsToBeCreated = new List<animalos__Alert__Share>();
                for(animalos__Alert__c alertVar : alerts) {
                    Boolean isInsert = Trigger.isInsert;
                    animalos__Animal__c relatedAnimal = animalsByIds.get(alertVar.animalos__Target_Record_Id__c);
                    if(isInsert && relatedAnimal != null) {
                        List<Location_Volunteer__c> relatedLocationVolunteers = new List<Location_Volunteer__c>();

                        if(existingLocationVolunteersByLocations.containsKey(relatedAnimal.animalos__Current_Site__c)) {
                            relatedLocationVolunteers.addAll((List<Location_Volunteer__c>)existingLocationVolunteersByLocations.get(relatedAnimal.animalos__Current_Site__c));
                        }
                        if(existingLocationVolunteersByLocations.containsKey(relatedAnimal.animalos__Current_Unit__c)) {
                            relatedLocationVolunteers.addAll((List<Location_Volunteer__c>)existingLocationVolunteersByLocations.get(relatedAnimal.animalos__Current_Unit__c));
                        }

                        if(!relatedLocationVolunteers.isEmpty()) {
                            for(Location_Volunteer__c relatedLocationVolunteer : relatedLocationVolunteers) {
                                shareRecordsToBeCreated.add(new animalos__Alert__Share(
                                        ParentId = alertVar.Id,
                                        UserOrGroupId = (usersByContactIds.get(relatedLocationVolunteer.Volunteer__c))?.Id,
                                        RowCause = 'Manual',
                                        AccessLevel = 'Edit'
                                ));
                            }
                        }
                    }
                }

                if(!shareRecordsToBeCreated.isEmpty()) {
                    insert shareRecordsToBeCreated;
                }
            }
        }
    }
}