force-app/main/default/objects/animalos__Interaction_Caution__c/animalos__Interaction_Caution__c.object-meta.xml
<CustomObject>
    <label>Interaction Caution</label>
    <nameField>
        <displayFormat>IC{000000000}</displayFormat>
        <label>Interaction Caution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Cautions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Caution_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Caution_Date_Time__c</fullName>
    <label>Caution Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Caution_Details__c.field-meta.xml
<CustomField>
    <fullName>animalos__Caution_Details__c</fullName>
    <label>Caution Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Caution_Source__c.field-meta.xml
<CustomField>
    <fullName>animalos__Caution_Source__c</fullName>
    <label>Caution Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Observed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Caution_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Caution_Type__c</fullName>
    <label>Caution Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical Violence</fullName>
            </value>
            <value>
                <fullName>Verbal Abuse</fullName>
            </value>
            <value>
                <fullName>Firearms/weapons</fullName>
            </value>
            <value>
                <fullName>Known to Police</fullName>
            </value>
            <value>
                <fullName>Substance Abuse</fullName>
                <label>Suspected Substance Abuse</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction Cautions</relationshipLabel>
    <relationshipName>Interaction_Cautions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Job_Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Contact</label>
    <referenceTo>animalos__Job_Contact__c</referenceTo>
    <relationshipLabel>Interaction Cautions</relationshipLabel>
    <relationshipName>Interaction_Cautions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/animalos__Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC{0000000}</displayFormat>
        <label>Job Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Contact_Jobs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/aos_JobContactIntCautionsMetaProc.cls
public class aos_JobContactIntCautionsMetaProc extends vertic_MetadataProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                animalos__Interaction_Caution__c.animalos__Caution_Source__c,
                animalos__Interaction_Caution__c.animalos__Caution_Type__c
        };

        super.process(this.request);

        this.doInit();

        return this.response;
    }

    private void doInit() {
        String contactId = this.request.getString('contactId');
        String jobId = this.request.getString('jobId');
        String jobContactId = this.request.getString('jobContactId');

        if(String.isBlank(contactId) && String.isBlank(jobId) && String.isBlank(jobContactId)) {
            throw new vertic_Structs.MissingDataException('At least one of the following parameters must be provided: contactId, jobId, jobContactId');
        }

        Set<String> fields = new Set<String>{
                'Id',
                'animalos__Caution_Details__c',
                'animalos__Caution_Type__c',
                'animalos__Caution_Source__c',
                'animalos__Caution_Date_Time__c',
                'animalos__Job_Contact__r.animalos__Job__r.Name'
        };

        fflib_QueryFactory queryFactory = new fflib_QueryFactory(animalos__Interaction_Caution__c.SObjectType)
                .selectFields(fields)
                .addOrdering('animalos__Job_Contact__r.animalos__Job__r.Name', fflib_QueryFactory.SortOrder.DESCENDING)
                .addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);

        if (String.isNotBlank(contactId)) {
            queryFactory.setCondition('animalos__Contact__c = :contactId');
        }

        if (String.isNotBlank(jobId)) {
            queryFactory.setCondition('animalos__Job_Contact__r.animalos__Job__c = :jobId');
        }

        if (String.isNotBlank(jobContactId)) {
            queryFactory.setCondition('animalos__Job_Contact__c = :jobContactId');
        }

        List<animalos__Interaction_Caution__c> interactionCautions = Database.query(queryFactory.toSOQL());
        this.response.getMapper().mapFromListSObjects('interactionCautions', interactionCautions);
    }
}