force-app/main/default/objects/animalos__Interaction_Caution__c/animalos__Interaction_Caution__c.object-meta.xml
<CustomObject>
    <label>Interaction Caution</label>
    <nameField>
        <displayFormat>IC{000000000}</displayFormat>
        <label>Interaction Caution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Cautions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Caution_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Caution_Date_Time__c</fullName>
    <label>Caution Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Caution_Source__c.field-meta.xml
<CustomField>
    <fullName>animalos__Caution_Source__c</fullName>
    <label>Caution Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Observed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Caution_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Caution_Type__c</fullName>
    <label>Caution Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical Violence</fullName>
            </value>
            <value>
                <fullName>Verbal Abuse</fullName>
            </value>
            <value>
                <fullName>Firearms/weapons</fullName>
            </value>
            <value>
                <fullName>Known to Police</fullName>
            </value>
            <value>
                <fullName>Substance Abuse</fullName>
                <label>Suspected Substance Abuse</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction Cautions</relationshipLabel>
    <relationshipName>Interaction_Cautions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Job_Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Contact</label>
    <referenceTo>animalos__Job_Contact__c</referenceTo>
    <relationshipLabel>Interaction Cautions</relationshipLabel>
    <relationshipName>Interaction_Cautions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/animalos__Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC{0000000}</displayFormat>
        <label>Job Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Contact_Jobs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/aos_JobContactsAddIntCautionMetaProc.cls
public class aos_JobContactsAddIntCautionMetaProc extends vertic_MetadataProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                animalos__Interaction_Caution__c.animalos__Caution_Source__c,
                animalos__Interaction_Caution__c.animalos__Caution_Type__c
        };

        super.process(this.request);

        this.doInit();

        return this.response;
    }

    private void doInit() {
        String jobContactId = this.request.getString('jobContactId');

        animalos__Interaction_Caution__c interactionCautionVar = new animalos__Interaction_Caution__c(
                animalos__Caution_Date_Time__c = Datetime.now(), animalos__Job_Contact__c = jobContactId
        );

        if(String.isNotBlank(jobContactId)) {
            animalos__Job_Contact__c jobContactVar = (animalos__Job_Contact__c) vertic_Utils.arrays.firstOrException([
                    SELECT Id, animalos__Contact__c
                    FROM animalos__Job_Contact__c
                    WHERE Id = :jobContactId
            ], 'No Job Contact with Id: ' + jobContactId);
            interactionCautionVar.animalos__Contact__c = jobContactVar.animalos__Contact__c;
        }

        this.response.put('interactionCaution', interactionCautionVar);
    }
}