force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Scheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Scheduled_Date_Time__c</fullName>
    <label>Scheduled Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_Adopter__c.field-meta.xml
<CustomField>
    <fullName>aos_Adopter__c</fullName>
    <formula>IF(ISBLANK(aos_Adoption_Transactions__c), &quot;NULL&quot;,
IF(aos_Adoption_Transactions__c = 1, &quot;Yes&quot;,
IF(aos_Adoption_Transactions__c = 0, &quot;No&quot;,
IF(aos_Adoption_Transactions__c &gt; 1, &quot;Repeat&quot;, NULL)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adopter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_Adoption_Count__c.field-meta.xml
<CustomField>
    <fullName>aos_Adoption_Count__c</fullName>
    <label>Adoption Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_Adoptions_Last_10_Years__c.field-meta.xml
<CustomField>
    <fullName>aos_Adoptions_Last_10_Years__c</fullName>
    <label>Adoptions Last 10 Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_Adoptions_Last_5_Years__c.field-meta.xml
<CustomField>
    <fullName>aos_Adoptions_Last_5_Years__c</fullName>
    <label>Adoptions Last 5 Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_Adoptions_This_Year__c.field-meta.xml
<CustomField>
    <fullName>aos_Adoptions_This_Year__c</fullName>
    <label>Adoptions This Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_First_Adoption_Date__c.field-meta.xml
<CustomField>
    <fullName>aos_First_Adoption_Date__c</fullName>
    <label>First Adoption Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_Last_Adoption_Date__c.field-meta.xml
<CustomField>
    <fullName>aos_Last_Adoption_Date__c</fullName>
    <label>Last Adoption Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/aos_CalcRollupsContactAdoption.cls
global class aos_CalcRollupsContactAdoption extends animalos.vertic_SequentialScheduledBatch {
    global override Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
                SELECT Id,
                        aos_First_Adoption_Date__c, aos_Last_Adoption_Date__c, aos_Adoption_Count__c, aos_Adoptions_This_Year__c,
                        aos_Adoptions_Last_5_Years__c, aos_Adoptions_Last_10_Years__c, aos_Adopter__c
                FROM Contact
                WHERE Id IN (
                        SELECT animalos__Contact__c
                        FROM animalos__Referral__c
                        WHERE RecordType.DeveloperName = 'Adoption' AND LastModifiedDate >= :this.sequentialBatchSetting.animalos__Last_Calculation_Datetime__c
                )
        ]);
    }

    global override void process(List<SObject> records) {

        Map<String, Object> adoptionsByContact = aos_Utils.sObjects.getSObjectsListByAnyFieldMap([
                SELECT Id, animalos__Scheduled_Date_Time__c, animalos__Contact__c
                FROM animalos__Referral__c
                WHERE animalos__Contact__c IN :records
                AND RecordType.DeveloperName = 'Adoption'
        ], animalos__Referral__c.animalos__Contact__c);

        for (Contact contact : (List<Contact>) records) {
            List<animalos__Referral__c> adoptions = (List<sObject>) adoptionsByContact.get(contact.Id);
            this.calculateAdoptions(contact, adoptions);
        }

        update records;
    }



    private void calculateAdoptions(Contact contactForUpdate, List<SObject> adoptions) {
        contactForUpdate.aos_Adoption_Count__c = adoptions == null ? 0 : adoptions.size();
        contactForUpdate.aos_Adoptions_This_Year__c = 0;
        contactForUpdate.aos_Adoptions_Last_5_Years__c = 0;
        contactForUpdate.aos_Adoptions_Last_10_Years__c = 0;

        if (adoptions != null) {
            for (animalos__Referral__c adoption : (List<animalos__Referral__c>) adoptions) {

                if (adoption.animalos__Scheduled_Date_Time__c >= Date.today().addYears(-1)) {
                    contactForUpdate.aos_Adoptions_This_Year__c += 1;
                }

                if (adoption.animalos__Scheduled_Date_Time__c >= Date.today().addYears(-5)) {
                    contactForUpdate.aos_Adoptions_Last_5_Years__c += 1;
                }

                if (adoption.animalos__Scheduled_Date_Time__c >= Date.today().addYears(-10)) {
                    contactForUpdate.aos_Adoptions_Last_10_Years__c += 1;
                }

                contactForUpdate.aos_First_Adoption_Date__c = contactForUpdate.aos_First_Adoption_Date__c == null ? adoption.animalos__Scheduled_Date_Time__c?.date() :
                        contactForUpdate.aos_First_Adoption_Date__c > adoption.animalos__Scheduled_Date_Time__c ? adoption.animalos__Scheduled_Date_Time__c?.date() :
                                contactForUpdate.aos_First_Adoption_Date__c;

                contactForUpdate.aos_Last_Adoption_Date__c = contactForUpdate.aos_Last_Adoption_Date__c == null ? adoption.animalos__Scheduled_Date_Time__c?.date() :
                        contactForUpdate.aos_Last_Adoption_Date__c > adoption.animalos__Scheduled_Date_Time__c ? contactForUpdate.aos_Last_Adoption_Date__c :
                                adoption.animalos__Scheduled_Date_Time__c?.date();
            }
        }
    }
}