force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/aos_Programs_Contact__c.field-meta.xml
<CustomField>
    <fullName>aos_Programs_Contact__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programs Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Programs Referrals</relationshipLabel>
    <relationshipName>aos_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_Program_Contact__c.field-meta.xml
<CustomField>
    <fullName>aos_Program_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Program Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_ReferralSetSecureContact.cls
global class TDTM_aos_ReferralSetSecureContact extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert, animalos.TDTM.AfterUpdate {
    global void onAfterInsert(List<SObject> records) {
        this.setSecureContact(records);
    }

    global void onAfterUpdate(List<SObject> records, Map<Id, SObject> existingRecords) {
        this.setSecureContact(records);
    }

    private void setSecureContact(List<SObject> records) {
        Set<Id> contactIds = aos_Utils.sObjects.getIdFieldValues(records, animalos__Referral__c.aos_Programs_Contact__c);
        List<Contact> contacts = new List<Contact>();

        for (Id contactId : contactIds) {
            contacts.add(new Contact(Id = contactId, aos_Program_Contact__c = true));
        }

        animalos.TDTM.getTriggerSObjectTypeEvent(Contact.SObjectType).disableAll();
        update contacts;
    }
}