force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Group_Key__c.field-meta.xml
<CustomField>
    <fullName>aos_Group_Key__c</fullName>
    <label>Group Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdoptionAgreementSubmitProc.cls
public without sharing class AdoptionAgreementSubmitProc extends vertic_AbstractProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {
        animalos__Referral__c referralVar = new animalos__Referral__c();
        this.request.getMapper().mapToSObject('referral', referralVar);
        update referralVar;
        Id referralId = (Id) referralVar.Id;
        vertic_AsyncProcess asyncProcess = new vertic_AsyncProcess();

        aos_Async_Process__c saveSignaturesVap = vertic_AsyncProcess.create(
                AdoptionAgreementSaveSignaturesProc.class,
                this.request.getMap()
        );

        saveSignaturesVap.aos_Group_Key__c = referralId;
        asyncProcess.add(saveSignaturesVap);

        aos_Async_Process__c savePdfVap = vertic_AsyncProcess.create(
                AdoptionAgreementSavePdfProc.class,
                this.request.getMap()
        );
        savePdfVap.aos_Group_Key__c = referralId;
        asyncProcess.add(savePdfVap);

        asyncProcess.enqueue();
    }
}