force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Full_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Full_Location_Name__c</fullName>
    <formula>CASE( RecordType.Name,
    &apos;Block&apos;, IF(ISBLANK( animalos__Sitename__c), Name, animalos__Parent_Block__r.Name &amp; &apos; / &apos; &amp; Name),
    &apos;Unit&apos;, IF(ISBLANK( animalos__Sitename__c), animalos__Parent_Block__r.Name &amp; &apos; / &apos; &amp; Name, animalos__Parent_Block__r.animalos__Parent_Block__r.Name &amp; &apos; / &apos; &amp; animalos__Parent_Block__r.Name &amp; &apos; / &apos; &amp; Name),
    &apos;Site&apos;, Name, 
    &apos;Foster&apos;, Name,
    &apos;Offsite&apos;, Name, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Parent_Block__c.field-meta.xml
<CustomField>
    <fullName>animalos__Parent_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Block</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Sub Locations</relationshipLabel>
    <relationshipName>Sub_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/aos_Location_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Location Volunteer</label>
    <nameField>
        <displayFormat>LV{00000}</displayFormat>
        <label>Location Volunteer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Location__c.field-meta.xml
<CustomField>
    <fullName>aos_Location__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>Location_Volunteers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>aos_Volunteer__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>aos_Volunteer_Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/aos_PartnersUserSetupMetaProc.cls
public class aos_PartnersUserSetupMetaProc extends aos_MetadataProcessor {

    public override aos_Response process(aos_Request request) {
        this.request = request == null ? new aos_MetadataProcessor.MetadataRequest() : (aos_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                // SObject Fields, e.g. Contact.Salutation
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        String recordId = this.request.getRequiredString('recordId');

        Contact contactVar = (Contact) aos_Utils.arrays.firstOrException([
                SELECT Id, FirstName, LastName, Email, Name, animalos__POI_Flag__c
                FROM Contact
                WHERE Id = :recordId
        ]);

        User userVar = (User) aos_Utils.arrays.firstOrNull([
                SELECT Id, Name, FirstName, LastName, Username, ProfileId, Profile.Name, IsActive
                FROM User
                WHERE ContactId = :contactVar.Id AND ProfileId IN :aos_PartnersPortalReshareRecordsProc.PARTNERS_PORTAL_PROFILE_IDS
        ]);

        String networkId = ((Network) aos_Utils.arrays.firstOrNull([
                SELECT Id
                FROM Network
                WHERE Name LIKE '%Partners'
        ]))?.Id;

        List<Profile> profiles = [
                SELECT Id, Name
                FROM Profile
                WHERE Id IN (
                        SELECT ParentId
                        FROM NetworkMemberGroup
                        WHERE NetworkId = :networkId
                )
                AND Name != 'System Administrator'
        ];

        List<aos_Structs.SelectOption> profileOptions = new List<aos_Structs.SelectOption>();

        for (Profile profile : profiles) {
            profileOptions.add(new aos_Structs.SelectOption(profile.Id, profile.Name));
        }

        List<aos_Location_Volunteer__c> locationVolunteers = [
                SELECT Id, aos_Location__c, aos_Location__r.Name, aos_Location__r.RecordType.DeveloperName, aos_Location__r.animalos__Full_Location_Name__c,
                        aos_Location__r.animalos__Parent_Block__c, aos_Location__r.animalos__Parent_Block__r.Name, aos_Status__c
                FROM aos_Location_Volunteer__c
                WHERE aos_Volunteer__c = :contactVar.Id
        ];

        this.response.put('doesCommunityExist', String.isNotBlank(networkId));
        this.response.getMapper().mapFromSObject('contact', contactVar);
        this.response.getMapper().mapFromSObject('user', userVar ?? new User(
                FirstName = contactVar.FirstName,
                LastName = contactVar.LastName,
                ContactId = contactVar.Id,
                Email = contactVar.Email,
                Username = (String.isNotBlank(contactVar.Email) ? contactVar.Email + '.partner' : '')
        ));
        this.response.getMapper().mapFromListSObjects('locationVolunteers', locationVolunteers);
        this.response.addSelectOptions('profileOptions', profileOptions);
    }
}