force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foster Locations</relationshipLabel>
    <relationshipName>Foster_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Parent_Block__c.field-meta.xml
<CustomField>
    <fullName>animalos__Parent_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Block</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Sub Locations</relationshipLabel>
    <relationshipName>Sub_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/aos_Location_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Location Volunteer</label>
    <nameField>
        <displayFormat>LV{00000}</displayFormat>
        <label>Location Volunteer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Location__c.field-meta.xml
<CustomField>
    <fullName>aos_Location__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>Location_Volunteers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>aos_Volunteer__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>aos_Volunteer_Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/PartnersUserSetupAddLVProc.cls
public class PartnersUserSetupAddLVProc extends vertic_AbstractProcessor implements vertic_Structs.IRollbackable {

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {
        String recordId = this.request.getRequiredString('recordId');
        Contact contactVar = (Contact) vertic_Utils.arrays.firstOrException([
                SELECT Id, Name
                FROM Contact
                WHERE Id = :recordId
        ]);

        animalos__Location__c location = new animalos__Location__c();
        this.request.getMapper().mapToSObject('location', location);
        location.animalos__Contact__c = recordId;
        location.RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Location__c.SObjectType, 'Foster');
        location.Name = contactVar.Name + ' Foster';

        location.Id = ((animalos__Location__c) vertic_Utils.arrays.firstOrNull([
                SELECT Id
                FROM animalos__Location__c
                WHERE animalos__Parent_Block__c = :location.animalos__Parent_Block__c AND animalos__Contact__c = :contactVar.Id
        ]))?.Id;
        upsert location;

        aos_Location_Volunteer__c locationVolunteer = (aos_Location_Volunteer__c) vertic_Utils.arrays.firstOrNull([
                SELECT Id
                FROM aos_Location_Volunteer__c
                WHERE aos_Location__c = :location.Id AND aos_Volunteer__c = :contactVar.Id
        ]);

        if (locationVolunteer == null) {
            locationVolunteer = new aos_Location_Volunteer__c(
                    aos_Location__c = location.Id,
                    aos_Volunteer__c = contactVar.Id,
                    aos_Status__c = 'Active'
            );
            insert locationVolunteer;
        }
    }

}