force-app/main/default/objects/animalos__Animal_Report__c/animalos__Animal_Report__c.object-meta.xml
<CustomObject>
    <label>Animal Report</label>
    <nameField>
        <displayFormat>AR{000000}</displayFormat>
        <label>Animal Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Report__c/fields/animalos__Animal_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Type__c</fullName>
    <label>Animal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Report__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Animal Reports</relationshipLabel>
    <relationshipName>Animal_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Report__c/fields/aos_Case__c.field-meta.xml
<CustomField>
    <fullName>aos_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animal Reports (AnimalOS)</relationshipLabel>
    <relationshipName>Animal_Reports_AnimalOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/animalos__Interaction_Caution__c.object-meta.xml
<CustomObject>
    <label>Interaction Caution</label>
    <nameField>
        <displayFormat>IC{000000000}</displayFormat>
        <label>Interaction Caution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Cautions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction Cautions</relationshipLabel>
    <relationshipName>Interaction_Cautions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Interaction_Caution__c/fields/animalos__Job_Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Contact</label>
    <referenceTo>animalos__Job_Contact__c</referenceTo>
    <relationshipLabel>Interaction Cautions</relationshipLabel>
    <relationshipName>Interaction_Cautions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Location_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location_Of_Interest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Of Interest</label>
    <referenceTo>animalos__Location_Of_Interest__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>animalos__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Under Reg Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Recheck</fullName>
            </value>
            <value>
                <fullName>Pending Prosecution</fullName>
            </value>
            <value>
                <fullName>Awaiting Notification Response</fullName>
            </value>
            <value>
                <fullName>Awaiting Further Information</fullName>
            </value>
            <value>
                <fullName>Awaiting Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Re-Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Attendance</fullName>
            </value>
            <value>
                <fullName>In Attendance</fullName>
            </value>
            <value>
                <fullName>Working on Job</fullName>
            </value>
            <value>
                <fullName>Attended – CC left</fullName>
            </value>
            <value>
                <fullName>Attended – enquires continuing</fullName>
            </value>
            <value>
                <fullName>Departed Job</fullName>
            </value>
            <value>
                <fullName>Equipment Set</fullName>
            </value>
            <value>
                <fullName>Follow Up Required</fullName>
            </value>
            <value>
                <fullName>Awaiting AWD Compliance Check</fullName>
            </value>
            <value>
                <fullName>Covering Inspector -Assigned</fullName>
            </value>
            <value>
                <fullName>Covering Inspector – Awaiting Attendance</fullName>
            </value>
            <value>
                <fullName>Covering Inspector – Preliminary Enquiries Made</fullName>
            </value>
            <value>
                <fullName>Notes outstanding</fullName>
            </value>
            <value>
                <fullName>Pending Forfeiture Application</fullName>
            </value>
            <value>
                <fullName>Pending Forfeiture decision</fullName>
            </value>
            <value>
                <fullName>Pending FBOE</fullName>
            </value>
            <value>
                <fullName>Pending FBOE Application Decision</fullName>
            </value>
            <value>
                <fullName>Preliminary inquiries made</fullName>
            </value>
            <value>
                <fullName>Prosecution Commenced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/aos_Case__c.field-meta.xml
<CustomField>
    <fullName>aos_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>aos_Jobs_AnimalOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/recordTypes/Inspectorate.recordType-meta.xml
<RecordType>
    <fullName>Inspectorate</fullName>
    <active>true</active>
    <label>Inspectorate</label>
</RecordType>

force-app/main/default/objects/animalos__Job__c/recordTypes/Rescue.recordType-meta.xml
<RecordType>
    <fullName>Rescue</fullName>
    <active>true</active>
    <label>Rescue</label>
</RecordType>

force-app/main/default/objects/animalos__Job_Contact__c/animalos__Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC{0000000}</displayFormat>
        <label>Job Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Contact_Jobs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact_Type__c</fullName>
    <label>Contact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Informant</fullName>
            </value>
            <value>
                <fullName>Informant Secondary</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Person Of Interest</fullName>
            </value>
            <value>
                <fullName>POI Secondary</fullName>
            </value>
            <value>
                <fullName>Police Officer</fullName>
            </value>
            <value>
                <fullName>Rescuer</fullName>
            </value>
            <value>
                <fullName>Spoken to</fullName>
            </value>
            <value>
                <fullName>Subject animal owner</fullName>
            </value>
            <value>
                <fullName>Subject property owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>Witness Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>animalos__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/aos_Case__c.field-meta.xml
<CustomField>
    <fullName>aos_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Job Contacts (AnimalOS)</relationshipLabel>
    <relationshipName>aos_Job_Contacts_AnimalOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/animalos__Location_Of_Interest__c.object-meta.xml
<CustomObject>
    <label>Location Of Interest</label>
    <nameField>
        <label>Location Of Interest</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/aos_AnimalWelfareCaseSubmitProc.cls
public without sharing class aos_AnimalWelfareCaseSubmitProc extends aos_AbstractProcessor implements aos_Structs.IRollbackable {

    public override aos_Response process(aos_Request request) {
        this.request = request;

        this.doSubmit();


        return this.response;
    }

    private void doSubmit() {
        aos_UnitOfWork uow = new aos_UnitOfWork(new List<SObjectType>{
                animalos__Location_Of_Interest__c.SObjectType,
                Contact.SObjectType,
                Case.SObjectType,
                animalos__Job__c.SObjectType,
                animalos__Job_Contact__c.SObjectType,
                animalos__Animal_Report__c.SObjectType,
                animalos__Interaction_Caution__c.SObjectType
        });

        Set<String> caseSubjectParts = new Set<String>();

        Case caseVar = new Case();
        this.request.getMapper().mapToSObject('case', caseVar);
        caseVar.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(Case.SObjectType, 'Inspectorate_Cruelty');

        animalos__Job__c jobVar = new animalos__Job__c();
        this.request.getMapper().mapToSObject('job', jobVar);

        animalos__Location_Of_Interest__c locationOfInterestVar = new animalos__Location_Of_Interest__c();
        this.request.getMapper().mapToSObject('locationOfInterest', locationOfInterestVar);
        uow.registerUpsert(locationOfInterestVar);

        //Save & Create Job action
        if (jobVar != null) {
            caseVar.Status = 'Job Raised';
            jobVar.animalos__Status__c = 'New';
        }

        caseVar.Location_Address__Street__s = locationOfInterestVar.animalos__Address__Street__s;
        caseVar.Location_Address__City__s = locationOfInterestVar.animalos__Address__City__s;
        caseVar.Location_Address__StateCode__s = locationOfInterestVar.animalos__Address__StateCode__s;
        caseVar.Location_Address__PostalCode__s = locationOfInterestVar.animalos__Address__PostalCode__s;
        caseVar.Location_Address__CountryCode__s = locationOfInterestVar.animalos__Address__CountryCode__s;
        caseVar.Location_Address__Latitude__s = locationOfInterestVar.animalos__Address__Latitude__s;
        caseVar.Location_Address__Longitude__s = locationOfInterestVar.animalos__Address__Longitude__s;

        uow.registerUpsert(caseVar);

        //Save & Create Job action
        if (jobVar != null) {
            if (jobVar.animalos__Start_Date__c == null) {
                jobVar.animalos__Start_Date__c = Datetime.now();
            }

            String rescueRecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Job__c.SObjectType, 'Rescue');
            String inspectorateRecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Job__c.SObjectType, 'Inspectorate');

            if (jobVar.Id == null && jobVar.RecordTypeId != null) {
                Group groupVar;

                if (rescueRecordTypeId.equals(jobVar.RecordTypeId)) {
                    groupVar = (Group) aos_Utils.arrays.firstOrNull([
                            SELECT Id, DeveloperName
                            FROM Group
                            WHERE DeveloperName = 'Awaiting_Assignment_Rescue' AND Id IN (
                                    SELECT QueueId
                                    FROM QueueSobject
                                    WHERE SobjectType = 'animalos__Job__c'
                            )
                    ]);
                }

                if (inspectorateRecordTypeId.equals(jobVar.RecordTypeId)) {
                    groupVar = (Group) aos_Utils.arrays.firstOrNull([
                            SELECT Id, Name, DeveloperName
                            FROM Group
                            WHERE DeveloperName = 'Awaiting_Assignment' AND Id IN (
                                    SELECT QueueId
                                    FROM QueueSobject
                                    WHERE SobjectType = 'animalos__Job__c'
                            )
                    ]);
                }

                if (groupVar != null) {
                    jobVar.OwnerId = groupVar.Id;
                }
            }

            uow.registerRelationship(jobVar, animalos__Job__c.aos_Case__c, caseVar);
            uow.registerRelationship(jobVar, animalos__Job__c.animalos__Location_Of_Interest__c, locationOfInterestVar);
            jobVar.animalos__Address__Street__s = locationOfInterestVar.animalos__Address__Street__s;
            jobVar.animalos__Address__City__s = locationOfInterestVar.animalos__Address__City__s;
            jobVar.animalos__Address__StateCode__s = locationOfInterestVar.animalos__Address__StateCode__s;
            jobVar.animalos__Address__PostalCode__s = locationOfInterestVar.animalos__Address__PostalCode__s;
            jobVar.animalos__Address__CountryCode__s = locationOfInterestVar.animalos__Address__CountryCode__s;
            jobVar.animalos__Address__Latitude__s = locationOfInterestVar.animalos__Address__Latitude__s;
            jobVar.animalos__Address__Longitude__s = locationOfInterestVar.animalos__Address__Longitude__s;
            uow.registerUpsert(jobVar);
        }

        List<animalos__Animal_Report__c> animalReports = this.request.getMapper().mapToListSObjects('animalReports', animalos__Animal_Report__c.SObjectType);
        if (animalReports != null) {
            for (animalos__Animal_Report__c animalReport : animalReports) {
                if ('Dog'.equals(animalReport.animalos__Animal_Type__c) || 'Puppy'.equals(animalReport.animalos__Animal_Type__c)) {
                    animalReport.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Animal_Report__c.SObjectType, 'Dog');
                } else if ('Cat'.equals(animalReport.animalos__Animal_Type__c) || 'Kitten'.equals(animalReport.animalos__Animal_Type__c)) {
                    animalReport.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Animal_Report__c.SObjectType, 'Cat');
                } else if ('Bird'.equals(animalReport.animalos__Animal_Type__c) || 'Native Birds'.equals(animalReport.animalos__Animal_Type__c) || 'Non Native Birds'.equals(animalReport.animalos__Animal_Type__c)) {
                    animalReport.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Animal_Report__c.SObjectType, 'Bird');
                } else if ('Cattle'.equals(animalReport.animalos__Animal_Type__c) || 'Donkey'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Farm'.equals(animalReport.animalos__Animal_Type__c) || 'Fowl'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Goat'.equals(animalReport.animalos__Animal_Type__c) || 'Horse'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Pig'.equals(animalReport.animalos__Animal_Type__c) || 'Pony'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Sheep'.equals(animalReport.animalos__Animal_Type__c)) {
                    animalReport.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Animal_Report__c.SObjectType, 'Livestock');
                } else if ('Ferret'.equals(animalReport.animalos__Animal_Type__c) || 'Gerbil'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Guinea Pig'.equals(animalReport.animalos__Animal_Type__c) || 'Hamster'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Rabbit'.equals(animalReport.animalos__Animal_Type__c) || 'Mouse'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Rat'.equals(animalReport.animalos__Animal_Type__c) || 'Rodent'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Small Pets'.equals(animalReport.animalos__Animal_Type__c)) {
                    animalReport.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Animal_Report__c.SObjectType, 'Pocket_Pet');
                } else if ('Poultry'.equals(animalReport.animalos__Animal_Type__c) || 'Chicken'.equals(animalReport.animalos__Animal_Type__c) ||
                        'Duck'.equals(animalReport.animalos__Animal_Type__c) || 'Goose'.equals(animalReport.animalos__Animal_Type__c)) {
                    animalReport.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Animal_Report__c.SObjectType, 'Poultry');
                } else {
                    animalReport.RecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(animalos__Animal_Report__c.SObjectType, 'General_Animal_Report');
                }
            }

            uow.registerUpsert(animalReports);
            uow.registerRelationship(animalReports, animalos__Animal_Report__c.aos_Case__c, caseVar);
            //Save & Create Job action
            if (jobVar != null) {
                uow.registerRelationship(animalReports, animalos__Animal_Report__c.animalos__Job__c, jobVar);
            }
        }

        if (jobVar != null && jobVar.RecordTypeId != null) {
            caseSubjectParts.add(aos_Utils.sObjects.recordTypeNameById(animalos__Job__c.SObjectType, jobVar.RecordTypeId));
        }

        List<Map<String, Object>> jobContactMaps = this.request.getListAsMap('jobContacts');
        Map<String, List<Contact>> contactsByAccountIds = new Map<String, List<Contact>>();

        if (jobContactMaps != null) {
            for (Map<String, Object> jobContactMap : jobContactMaps) {
                Contact contactVar = new Contact();
                animalos__Job_Contact__c jobContactVar = new animalos__Job_Contact__c();
                aos_DTO jobContactDTO = new aos_DTO(new Map<String, Object>{
                        'jobContact' => jobContactMap
                });

                String organizationId = jobContactDTO.getString('jobContact.OrganizationId');

                jobContactDTO.getMapper().mapToSObject('jobContact.animalos__Contact__r', contactVar);
                jobContactDTO.getMapper().mapToSObject('jobContact', jobContactVar);
                List<animalos__Interaction_Caution__c> interactionCautions = jobContactDTO.getMapper().mapToListSObjects('jobContact.animalos__Interaction_Cautions__r.records', animalos__Interaction_Caution__c.SObjectType);

                uow.registerUpsert(contactVar);
                uow.registerUpsert(jobContactVar);
                uow.registerRelationship(jobContactVar, animalos__Job_Contact__c.animalos__Contact__c, contactVar);
                uow.registerRelationship(jobContactVar, animalos__Job_Contact__c.aos_Case__c, caseVar);

                if (String.isNotBlank(organizationId)) {
                    if (contactsByAccountIds.containsKey(organizationId)) {
                        contactsByAccountIds.get(organizationId).add(contactVar);
                    } else {
                        contactsByAccountIds.put(organizationId, new List<Contact>{
                                contactVar
                        });
                    }
                }

                if (interactionCautions != null && !interactionCautions.isEmpty()) {
                    for (animalos__Interaction_Caution__c interactionCaution : interactionCautions) {
                        uow.registerUpsert(interactionCaution);
                        uow.registerRelationship(interactionCaution, animalos__Interaction_Caution__c.animalos__Job_Contact__c, jobContactVar);
                        uow.registerRelationship(interactionCaution, animalos__Interaction_Caution__c.animalos__Contact__c, contactVar);
                    }
                }

                if ('Person Of Interest'.equalsIgnoreCase(jobContactVar.animalos__Contact_Type__c)) {
                    caseSubjectParts.add((String.isNotBlank(contactVar.FirstName) ? contactVar.FirstName + ' ' : 'Unknown ') + contactVar.LastName);
                    uow.registerRelationship(caseVar, Case.ContactId, contactVar);
                }
                //Save & Create Job action
                if (jobVar != null) {
                    uow.registerRelationship(jobContactVar, animalos__Job_Contact__c.animalos__Job__c, jobVar);
                }
            }
        }

        if (String.isNotBlank(caseVar.Location_Address__City__s)) {
            caseSubjectParts.add(caseVar.Location_Address__City__s);
        }

        if (String.isNotBlank(caseVar.Location_Address__PostalCode__s)) {
            caseSubjectParts.add(caseVar.Location_Address__PostalCode__s);
        }

        caseVar.Subject = String.join(new List<String>(caseSubjectParts), ' - ');

        System.debug(locationOfInterestVar);
        uow.commitWork();

        List<AccountContactRelation> accountContactRelations = [
                SELECT Id, ContactId, AccountId
                FROM AccountContactRelation
                WHERE AccountId IN :contactsByAccountIds.keySet()
        ];

        Map<String, AccountContactRelation> relationsByContactAndAccountIds = new Map<String, AccountContactRelation>();

        for (AccountContactRelation accountContactRelation : accountContactRelations) {
            relationsByContactAndAccountIds.put(accountContactRelation.ContactId + '' + accountContactRelation.AccountId, accountContactRelation);
        }

        List<AccountContactRelation> relationsToInsert = new List<AccountContactRelation>();

        if (!contactsByAccountIds.isEmpty()) {
            for (String organizationId : contactsByAccountIds.keySet()) {
                List<Contact> contacts = contactsByAccountIds.get(organizationId);

                for (Contact contactVar : contacts) {
                    if (relationsByContactAndAccountIds.get(contactVar.Id + '' + organizationId) != null) {
                        continue;
                    }

                    relationsToInsert.add(new AccountContactRelation(
                            ContactId = contactVar.Id,
                            AccountId = organizationId
                    ));
                }
            }
        }

        insert relationsToInsert;

        this.response.getMapper()
                .mapFromSObject('caseVar', caseVar)
                .mapAnyValue('caseVar.CaseNumber', [
                        SELECT Id, CaseNumber
                        FROM Case
                        WHERE Id = :caseVar.Id
                        LIMIT 1
                ]?.CaseNumber);
        //Save & Create Job action
        if (jobVar != null) {
            this.response.getMapper()
                    .mapFromSObject('job', jobVar)
                    .mapAnyValue('job.Name', [
                            SELECT Id, Name
                            FROM animalos__Job__c
                            WHERE Id = :jobVar.Id
                            LIMIT 1
                    ]?.Name);
        }
    }
}