force-app/main/default/objects/animalos__Animal_Report__c/animalos__Animal_Report__c.object-meta.xml
<CustomObject>
    <label>Animal Report</label>
    <nameField>
        <displayFormat>AR{000000}</displayFormat>
        <label>Animal Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Report__c/fields/aos_Notify_Inspector__c.field-meta.xml
<CustomField>
    <fullName>aos_Notify_Inspector__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Inspector</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AnimalReportSetSendEmail.cls
global class TDTM_aos_AnimalReportSetSendEmail extends animalos.TDTM.Handler implements animalos.TDTM.BeforeUpdate {
    public static Map<String, Boolean> SEND_EMAIL_BY_ANIMAL_REPORT_ID = new Map<String, Boolean>();

    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        this.setSendEmailByAnimalReportId(records);
    }

    private void setSendEmailByAnimalReportId(List<SObject> records) {
        for (animalos__Animal_Report__c animalReportVar : (List<animalos__Animal_Report__c>) records) {
            SEND_EMAIL_BY_ANIMAL_REPORT_ID.put(animalReportVar.Id, animalReportVar.aos_Notify_Inspector__c);
            animalReportVar.aos_Notify_Inspector__c = false;
        }
    }
}