force-app/main/default/objects/animalos__Animal_Report__c/animalos__Animal_Report__c.object-meta.xml
<CustomObject>
    <label>Animal Report</label>
    <nameField>
        <displayFormat>AR{000000}</displayFormat>
        <label>Animal Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Report__c/fields/aos_Case__c.field-meta.xml
<CustomField>
    <fullName>aos_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animal Reports (AnimalOS)</relationshipLabel>
    <relationshipName>Animal_Reports_AnimalOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Report__c/fields/aos_Notify_Inspector__c.field-meta.xml
<CustomField>
    <fullName>aos_Notify_Inspector__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Inspector</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TDTM_AnimalReportSetSendEmailCase.cls
global class TDTM_AnimalReportSetSendEmailCase extends animalos.TDTM.Handler implements animalos.TDTM.BeforeUpdate {
    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        this.setSendEmailByCaseId(records);
    }

    private void setSendEmailByCaseId(List<SObject> records) {
        for (animalos__Animal_Report__c animalReportVar : (List<animalos__Animal_Report__c>) records) {
            TDTM_CaseSetSendEmail.SEND_EMAIL_BY_CASE_ID.put(animalReportVar.aos_Case__c, TDTM_CaseSetSendEmail.SEND_EMAIL_BY_CASE_ID.get(animalReportVar.aos_Case__c) == true || animalReportVar.aos_Notify_Inspector__c == true);
            animalReportVar.aos_Notify_Inspector__c = false;
        }
    }
}