force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDTM_AnimalReferralSetReferralValues.cls
global class TDTM_AnimalReferralSetReferralValues extends animalos.TDTM.Handler implements animalos.TDTM.BeforeInsert {
    public void onBeforeInsert(List<SObject> records) {
        this.setReferralValues(records);
    }

    private void setReferralValues(List<SObject> records) {
        Set<Id> referralIds = vertic_Utils.sObjects.getIdFieldValues(records, animalos__Animal_Referral__c.animalos__Referral__c);
        Map<Id, animalos__Referral__c> referralsByIds = new Map<Id, animalos__Referral__c>([
                SELECT Id, animalos__Job__c
                FROM animalos__Referral__c
                WHERE Id IN :referralIds
        ]);

        for (animalos__Animal_Referral__c animalReferral : (List<animalos__Animal_Referral__c>) records) {
            animalos__Referral__c referral = referralsByIds.get(animalReferral.animalos__Referral__c);
            if (referral != null) {
                animalReferral.animalos__Job__c = referral.animalos__Job__c;
            }
        }
    }
}