force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Referral_Stage_Tracking__c/aos_Referral_Stage_Tracking__c.object-meta.xml
<CustomObject>
    <label>Referral Stage Tracking</label>
    <nameField>
        <displayFormat>RST{00000}</displayFormat>
        <label>Referral Stage Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Stage Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Referral_Stage_Tracking__c/fields/aos_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>aos_End_Date_Time__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/aos_Referral_Stage_Tracking__c/fields/aos_Parent_Referral_Stage_Tracking__c.field-meta.xml
<CustomField>
    <fullName>aos_Parent_Referral_Stage_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Referral Stage Tracking</label>
    <referenceTo>aos_Referral_Stage_Tracking__c</referenceTo>
    <relationshipLabel>Referral Stage Trackings</relationshipLabel>
    <relationshipName>aos_Referral_Stage_Tracking_Childs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Referral_Stage_Tracking__c/fields/aos_Referral__c.field-meta.xml
<CustomField>
    <fullName>aos_Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Referral Stage Trackings</relationshipLabel>
    <relationshipName>Referral_Stage_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AnimalReferralCreateStageTrack.cls
global inherited sharing class TDTM_aos_AnimalReferralCreateStageTrack extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert {

    public void onAfterInsert(List<SObject> records) {
        this.updateParentStageTrackingRecord(records);
    }

    private void updateParentStageTrackingRecord(List<SObject> records) {
        Set<Id> referralIds = vertic_Utils.sObjects.getIdFieldValues(records, animalos__Animal_Referral__c.animalos__Referral__c);

        List<aos_Referral_Stage_Tracking__c> lastReferralStageTrackingRecords = [
                SELECT Id
                FROM aos_Referral_Stage_Tracking__c
                WHERE aos_Referral__c IN :referralIds
                AND aos_Parent_Referral_Stage_Tracking__c = NULL
                AND aos_End_Date_Time__c = NULL
        ];

        if (!lastReferralStageTrackingRecords.isEmpty()) {
            //it will trigger TDTM_aos_ReferralStageTrackingChilds and create child records
            update lastReferralStageTrackingRecords;
        }
    }
}