force-app/main/default/objects/aos_Location_Volunteer__c/aos_Location_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Location Volunteer</label>
    <nameField>
        <displayFormat>LV{00000}</displayFormat>
        <label>Location Volunteer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Location__c.field-meta.xml
<CustomField>
    <fullName>aos_Location__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>Location_Volunteers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_User__c.field-meta.xml
<CustomField>
    <fullName>aos_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>aos_Location_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>aos_Volunteer__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>aos_Volunteer_Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TDTM_aos_LocationVolunteerReshareRecords.cls
global class TDTM_aos_LocationVolunteerReshareRecords extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert, animalos.TDTM.AfterUpdate, animalos.TDTM.BeforeDelete {
    public void onAfterInsert(List<SObject> records) {
        this.reshareRecords(records, null);
    }

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        this.reshareRecords(records, (Map<Id, aos_Location_Volunteer__c>) oldMap);
    }

    public void onBeforeDelete(List<SObject> records) {
        this.reshareRecords(records, null);
    }

    public void reshareRecords(List<aos_Location_Volunteer__c> locationVolunteers, Map<Id, aos_Location_Volunteer__c> existingRecords) {
        Set<Id> userIds = new Set<Id>();

        if (Trigger.isInsert || Trigger.isDelete) {
            userIds = aos_Utils.sObjects.getIdFieldValues(locationVolunteers,aos_Location_Volunteer__c.aos_User__c);
        }

        if (Trigger.isUpdate && existingRecords != null) {
            for (aos_Location_Volunteer__c locationVolunteer : (List<aos_Location_Volunteer__c>) locationVolunteers) {
                if (existingRecords.containsKey(locationVolunteer.Id) &&
                        aos_Utils.sObjects.isSomeFieldChanged(
                                locationVolunteer,
                                existingRecords.get(locationVolunteer.Id), new List<SObjectField>{
                                        aos_Location_Volunteer__c.aos_Location__c,
                                        aos_Location_Volunteer__c.aos_Volunteer__c,
                                        aos_Location_Volunteer__c.aos_Status__c
                                })) {
                    userIds.add(locationVolunteer.aos_User__c);
                    userIds.add(existingRecords.get(locationVolunteer.Id)?.aos_User__c);
                }
            }
        }

        if (!userIds.isEmpty()) {
            aos_PartnersPortalReshareRecordsProc.submitVAPsByUserIds(userIds);
        }
    }
}