force-app/main/default/objects/aos_Location_Volunteer__c/aos_Location_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Location Volunteer</label>
    <nameField>
        <displayFormat>LV{00000}</displayFormat>
        <label>Location Volunteer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_User__c.field-meta.xml
<CustomField>
    <fullName>aos_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>aos_Location_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>aos_Volunteer__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>aos_Volunteer_Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TDTM_aos_UserUpdateRelatedLocationVol.cls
global without sharing class TDTM_aos_UserUpdateRelatedLocationVol extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert {
    public void onAfterInsert(List<SObject> records) {
        System.debug('TDTM_UserUpdateRelatedLocationVolunteers.onAfterInsert() - records: ' + records);
        this.updateRelatedLocationVolunteers(records);
    }

    public void updateRelatedLocationVolunteers(List<SObject> records) {
        Set<Id> contactIds = new Set<Id>();
        for (User userVar : (List<User>) records) {
            if (Trigger.isInsert && String.isNotBlank(userVar.ContactId) && PartnersPortalReshareRecordsProc.PARTNERS_PORTAL_PROFILE_IDS.contains(userVar.ProfileId)) {
                contactIds.add(userVar.ContactId);
            }
        }

        if (!contactIds.isEmpty()) {
            Map<String, SObject> usersByContactIds = vertic_Utils.sObjects.getSObjectsByAnyFieldMap(records, Schema.User.ContactId);
            List<aos_Location_Volunteer__c> locationVolunteers = [
                    SELECT Id, aos_Volunteer__c, aos_User__c
                    FROM aos_Location_Volunteer__c
                    WHERE aos_Volunteer__c IN :contactIds
            ];

            for (aos_Location_Volunteer__c locationVolunteer : locationVolunteers) {
                locationVolunteer.aos_User__c = (Id) usersByContactIds.get(locationVolunteer.aos_Volunteer__c)?.get('Id');
            }

            update locationVolunteers;
        }
    }
}