force-app/main/default/objects/aos_LGA__c/aos_LGA__c.object-meta.xml
<CustomObject>
    <description>Reference list of Local Government Areas</description>
    <label>LGA</label>
    <nameField>
        <label>LGA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LGA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_LGA__c/fields/aos_Old__c.field-meta.xml
<CustomField>
    <fullName>aos_Old__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Old</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_Postcode__c/aos_Postcode__c.object-meta.xml
<CustomObject>
    <description>Reference list of QLD Postcodes</description>
    <label>Postcode</label>
    <nameField>
        <label>Postcode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Postcode__c/fields/aos_LGA__c.field-meta.xml
<CustomField>
    <fullName>aos_LGA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LGA</label>
    <referenceTo>aos_LGA__c</referenceTo>
    <relationshipLabel>Postcodes</relationshipLabel>
    <relationshipName>aos_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Postcode__c/fields/aos_Postcode__c.field-meta.xml
<CustomField>
    <fullName>aos_Postcode__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Postcode__c/fields/aos_Suburb__c.field-meta.xml
<CustomField>
    <fullName>aos_Suburb__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/aos_LGA__c.field-meta.xml
<CustomField>
    <fullName>aos_LGA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Local Government Area the Contact sits within (based on the Mailing Postcode).</description>
    <inlineHelpText>The Local Government Area the Contact sits within (based on the Mailing Postcode).</inlineHelpText>
    <label>LGA</label>
    <referenceTo>aos_LGA__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_ContactPopulateLGA.cls
global class TDTM_aos_ContactPopulateLGA extends animalos.TDTM.Handler implements animalos.TDTM.BeforeInsert, animalos.TDTM.BeforeUpdate {
    public void onBeforeInsert(List<SObject> records) {
        this.populateLGA((List<Contact>) records, new Map<Id, Contact>());
    }

    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> existingRecords) {
        this.populateLGA((List<Contact>) records, (Map<Id, Contact>) existingRecords);
    }

    private void populateLGA(List<Contact> contacts, Map<Id, Contact> existingContacts) {
        Set<String> cityValues = vertic_Utils.sObjects.getStringFieldValues(contacts, 'MailingCity');
        Set<String> postcodeValues = vertic_Utils.sObjects.getStringFieldValues(contacts, 'MailingPostalCode');

        List<aos_Postcode__c> postcodes = [
                SELECT Id, aos_LGA__c, aos_Postcode__c, aos_Suburb__c
                FROM aos_Postcode__c
                WHERE aos_Suburb__c IN :cityValues
                AND aos_Postcode__c IN :postcodeValues
                AND aos_LGA__c != NULL
                AND aos_Suburb__c != NULL
                AND aos_Postcode__c != NULL
                AND aos_LGA__r.aos_Old__c = FALSE
        ];

        for (Contact contact : contacts) {
            Boolean isInsert = Trigger.isInsert;
            Boolean isUpdate = Trigger.isUpdate &&
                    !existingContacts.isEmpty() &&
                    existingContacts.containsKey(contact.Id) &&
                    vertic_Utils.sObjects.isSomeFieldChanged(contact, existingContacts.get(contact.Id), new List<String>{
                            'MailingCity', 'MailingPostalCode'
                    });

            if (isInsert || isUpdate) {
                for (aos_Postcode__c postcode : postcodes) {
                    if (contact.MailingCity == postcode.aos_Suburb__c && contact.MailingPostalCode == postcode.aos_Postcode__c) {
                        contact.LGA__c = postcode.aos_LGA__c;
                    }
                }
            }
        }
    }
}