force-app/main/default/objects/aos_One_Drive_File_Permission__c/aos_One_Drive_File_Permission__c.object-meta.xml
<CustomObject>
    <label>One Drive File Permission</label>
    <nameField>
        <label>One Drive File Permission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One Drive File Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_One_Drive_File_Permission__c/fields/aos_Available_Profiles_Text__c.field-meta.xml
<CustomField>
    <fullName>aos_Available_Profiles_Text__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Available Profiles</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_One_Drive_File_Permission__c/fields/aos_One_Drive_File_Id__c.field-meta.xml
<CustomField>
    <fullName>aos_One_Drive_File_Id__c</fullName>
    <label>One Drive File Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/aos_OneDrive_File__c.object-meta.xml
<CustomObject>
    <label>OneDrive File</label>
    <nameField>
        <label>OneDrive File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OneDrive Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_File_ID__c.field-meta.xml
<CustomField>
    <fullName>aos_File_ID__c</fullName>
    <label>File ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/aos_CreateOneDriveFilePermissionProc.cls
public without sharing class aos_CreateOneDriveFilePermissionProc extends aos_AbstractProcessor {

    /**
     * ==============================================================================================================
     *                                              PROCESS
     * ==============================================================================================================
     */

    public override aos_Response process(aos_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }


    /**
     * ==============================================================================================================
     *                                             PRIVATE METHODS
     * ==============================================================================================================
     */

    private void doSubmit() {
        String oneDriveFileId = this.request.getString('id');
        String userId = UserInfo.getUserId();
        aos_OneDrive_File__c oneDriveFile = (aos_OneDrive_File__c) aos_Utils.arrays.firstOrNull([
                SELECT Id
                FROM aos_OneDrive_File__c
                WHERE aos_File_ID__c = :oneDriveFileId
        ]);


        List<Profile> profiles = [
                SELECT Id, Name
                FROM Profile
        ];
        String availableProfiles = '';

        if (oneDriveFile != null) {

            for (Profile profileVar : profiles) {
                availableProfiles += profileVar.Name + ';';
            }
        }

        aos_One_Drive_File_Permission__c oneDriveFilePermission = new aos_One_Drive_File_Permission__c(
                OwnerId = userId,
                aos_One_Drive_File_Id__c = oneDriveFileId,
                aos_Available_Profiles_Text__c = availableProfiles
        );

        insert oneDriveFilePermission;
    }


    /**
     * ==============================================================================================================
     *                                               STRUCTURES
     * ==============================================================================================================
     */

    // Proposed Live Templates to override Super properties:
    // aos_Request
    // aos_Response


}