force-app/main/default/objects/animalos__Log__c/animalos__Log__c.object-meta.xml
<CustomObject>
    <label>AnimalOS Log</label>
    <nameField>
        <displayFormat>AL{00000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AnimalOS Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Payload__c.field-meta.xml
<CustomField>
    <fullName>animalos__Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Process__c.field-meta.xml
<CustomField>
    <fullName>animalos__Process__c</fullName>
    <label>Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RetryLogProc.cls
public class RetryLogProc extends vertic_AbstractProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.retry();

        return this.response;
    }


    private void retry() {
        String logId = this.request.getRequiredString('recordId');
        animalos__Log__c logVar = (animalos__Log__c) vertic_Utils.arrays.firstOrException([
                SELECT Id, animalos__Payload__c, animalos__Process__c
                FROM animalos__Log__c
                WHERE Id = :logId
        ], 'Log not found: ' + logId);

        try {
            vertic_AbstractProcessor processor = (vertic_AbstractProcessor) Type.forName(logVar.animalos__Process__c).newInstance();
            processor.process((Map<String, Object>) JSON.deserializeUntyped(logVar.animalos__Payload__c));
            update new animalos.Logging()
                    .setId(logVar.Id)
                    .addPayload((Map<String, Object>) JSON.deserializeUntyped(logVar.animalos__Payload__c))
                    .setType('Success')
                    .build();
        } catch (Exception ex) {
            update new animalos.Logging()
                    .setId(logVar.Id)
                    .addDetails(ex)
                    .addPayload((Map<String, Object>) JSON.deserializeUntyped(logVar.animalos__Payload__c))
                    .setType('Error')
                    .build();
        }
    }
}