force-app/main/default/objects/animalos__Log__c/animalos__Log__c.object-meta.xml
<CustomObject>
    <label>AnimalOS Log</label>
    <nameField>
        <displayFormat>AL{00000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AnimalOS Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Location_Volunteer__c/aos_Location_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Location Volunteer</label>
    <nameField>
        <displayFormat>LV{00000}</displayFormat>
        <label>Location Volunteer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>aos_Volunteer__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>aos_Volunteer_Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TDTM_aos_UserDisableRelatedVolunteer.cls
global class TDTM_aos_UserDisableRelatedVolunteer extends animalos.TDTM.Handler implements animalos.TDTM.AfterUpdate {
    public void onAfterUpdate(List<SObject> record, Map<Id, SObject> existingRecords) {
        this.disableRelatedVolunteer(record, existingRecords);
    }

    private void disableRelatedVolunteer(List<SObject> records, Map<Id, SObject> existingRecords) {
        List<User> users = new List<User>();

        for (User userVar : (List<User>) records) {
            User existingUser = (User) existingRecords.get(userVar.Id);

            Boolean isDisabled = !userVar.IsActive && existingUser.IsActive;
            Boolean hasContact = userVar.ContactId != null;

            if (isDisabled && hasContact) {
                users.add(userVar);
            }
        }

        if (!users.isEmpty()) {
            Set<Id> contactIds = vertic_Utils.sObjects.getIdFieldValues(users, User.ContactId);
            List<animalos__Log__c> logs = new List<animalos__Log__c>();

            Map<String, Object> locationVolunteersByContactIds = vertic_Utils.sObjects.getSObjectsListByAnyFieldMap([
                    SELECT Id, aos_Volunteer__c
                    FROM aos_Location_Volunteer__c
                    WHERE aos_Volunteer__c IN :contactIds
            ], aos_Location_Volunteer__c.aos_Volunteer__c);

            List<aos_Location_Volunteer__c> locationVolunteersForUpdate = new List<aos_Location_Volunteer__c>();

            for (User userVar : users) {
                List<aos_Location_Volunteer__c> locationVolunteers = (List<aos_Location_Volunteer__c>) locationVolunteersByContactIds.get(userVar.ContactId);

                if (locationVolunteers != null && !locationVolunteers.isEmpty()) {
                    for (aos_Location_Volunteer__c locationVolunteer : locationVolunteers) {
                        logs.add(
                                new animalos.Logging()
                                        .setProcess('TDTM_aos_UserDisableRelatedVolunteer.DisableLocationVolunteerProc')
                                        .addPayload('recordId', locationVolunteer.Id)
                                        .build()
                        );
                    }
                }
            }

            System.enqueueJob(new aos_ProcessLogQueueable(logs));
        }
    }

    public without sharing class DisableLocationVolunteerProc extends vertic_AbstractProcessor {
        public override vertic_Response process(vertic_Request request) {
            this.request = request;

            String recordId = this.request.getString('recordId');

            aos_Location_Volunteer__c locationVolunteer = (aos_Location_Volunteer__c) vertic_Utils.arrays.firstOrException([
                    SELECT Id, aos_Status__c
                    FROM aos_Location_Volunteer__c
                    WHERE Id = :recordId
            ], 'No Location Volunteer with Id: ' + recordId);

            locationVolunteer.aos_Status__c = 'Inactive';

            update locationVolunteer;

            return this.response;
        }
    }

}