force-app/main/default/objects/animalos__Log__c/animalos__Log__c.object-meta.xml
<CustomObject>
    <label>AnimalOS Log</label>
    <nameField>
        <displayFormat>AL{00000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AnimalOS Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Payload__c.field-meta.xml
<CustomField>
    <fullName>animalos__Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Process__c.field-meta.xml
<CustomField>
    <fullName>animalos__Process__c</fullName>
    <label>Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RetryLogProcTest.cls
@IsTest
public class RetryLogProcTest {

    @IsTest
    static void testRetryProc() {
        animalos__Log__c logVar = new animalos__Log__c(
            animalos__Process__c = 'InvalidProcess',
            animalos__Payload__c = JSON.serialize(new Map<String, Object>{'recordId' => 'testRecordId'}),
            animalos__Type__c = 'Scheduled'
        );
        insert logVar;
        animalos__Log__c retryLogVar = new animalos__Log__c(
                animalos__Process__c = 'RetryLogProc',
                animalos__Type__c = 'Error',
                animalos__Payload__c = JSON.serialize(new Map<String, Object>{'recordId' => logVar.Id})
        );
        insert retryLogVar;

        vertic_Response responseVar = new RetryLogProc().process(new Map<String, Object>{
            'recordId' => retryLogVar.Id
        });

        Assert.isTrue(responseVar.isValid);
        Assert.isTrue([SELECT animalos__Type__c FROM animalos__Log__c WHERE Id = :logVar.Id].animalos__Type__c == 'Error', 'Log should be updated to Error');
        Assert.isTrue([SELECT animalos__Type__c FROM animalos__Log__c WHERE Id = :retryLogVar.Id].animalos__Type__c == 'Success', 'Log should be updated to Success');
    }
}