force-app/main/default/objects/animalos__Job_Contact__c/animalos__Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC{0000000}</displayFormat>
        <label>Job Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Contact__c/fields/aos_Notify_Inspector__c.field-meta.xml
<CustomField>
    <fullName>aos_Notify_Inspector__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Inspector</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TDTM_JobContactSetSendEmail.cls
global class TDTM_JobContactSetSendEmail extends animalos.TDTM.Handler implements animalos.TDTM.BeforeUpdate {
    public static Map<String, Boolean> SEND_EMAIL_BY_JOB_CONTACT_ID = new Map<String, Boolean>();

    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        this.setSendEmailByJobContactId(records);
    }

    private void setSendEmailByJobContactId(List<SObject> records) {
        for (animalos__Job_Contact__c jobContact : (List<animalos__Job_Contact__c>) records) {
            SEND_EMAIL_BY_JOB_CONTACT_ID.put(jobContact.Id, jobContact.aos_Notify_Inspector__c);
            jobContact.aos_Notify_Inspector__c = false;
        }
    }
}