force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Autorun__c.field-meta.xml
<CustomField>
    <fullName>aos_Autorun__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Autorun</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Description__c.field-meta.xml
<CustomField>
    <fullName>aos_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Group_Key__c.field-meta.xml
<CustomField>
    <fullName>aos_Group_Key__c</fullName>
    <label>Group Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Payload__c.field-meta.xml
<CustomField>
    <fullName>aos_Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Priority__c.field-meta.xml
<CustomField>
    <fullName>aos_Priority__c</fullName>
    <description>Priority for processing order.</description>
    <inlineHelpText>Priority for processing order.</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Processor__c.field-meta.xml
<CustomField>
    <fullName>aos_Processor__c</fullName>
    <label>Processor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShelterBuddyGetPersonsProc.cls
public with sharing class ShelterBuddyGetPersonsProc extends vertic_AbstractProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        Integer page = vertic_Utils.objects.defaultIfNull(this.request.getInteger('page'), 1);
        Integer pageSize = vertic_Utils.objects.defaultIfNull(this.request.getInteger('pageSize'), 10);
        Integer startIndex = vertic_Utils.objects.defaultIfNull(this.request.getInteger('startIndex'), 0);

        ShelterBuddyAPIUtils shelterBuddyAPIUtils = new ShelterBuddyAPIUtils();
        HttpResponse personListResponse = shelterBuddyAPIUtils.commonRequest('getPersonList', new List<String>{
            '' + page,
            '' + pageSize,
            '' + startIndex
        }, null);

        System.debug(personListResponse);

        if (personListResponse.getStatusCode() != 200) {
            throw new vertic_Structs.ProcessException(personListResponse.getStatusCode() + '\n\n\n' + personListResponse.getStatus() + personListResponse.getBody());
        }

        vertic_DTO responseDTO = new vertic_DTO(personListResponse.getBody());
        List<vertic_DTO> dataDTOs = responseDTO.getListAsDTONonNull('Data');

        List<aos_Async_Process__c> vaps = new List<aos_Async_Process__c>();

        System.debug('dataDTOs.size(): '+ dataDTOs.size());

        for (vertic_DTO dataDTO : dataDTOs) {
            vaps.add(new aos_Async_Process__c(
                    aos_Processor__c = '' + PersonUpsertProc.class,
                    aos_Payload__c = JSON.serializePretty(new Map<String, Object>{
                    'personJSON' => JSON.serialize(dataDTO.getMap())
                }),
                    aos_Group_Key__c = dataDTO.getString('Id'),
                    aos_Description__c = 'Load Person',
                    aos_Priority__c = 1
            ));
        }

        if (responseDTO.get('Paging.Next') != null) {
            vaps.add(0, new aos_Async_Process__c(
                    aos_Processor__c = '' + ShelterBuddyGetPersonsProc.class,
                    aos_Payload__c = JSON.serializePretty(new Map<String, Object>{
                    'page' => ++page,
                    'pageSize' => pageSize
                }),
                    aos_Description__c = 'Load Persons',
                    aos_Priority__c = 10,
                    aos_Autorun__c = false // TODO: comment out to sync all.
            ));
        }

        System.debug('vaps.size(): '+ vaps.size());

        insert vaps;

        return this.response;
    }

    public static void startLoad(Integer pageSize) {
        insert new aos_Async_Process__c(
                aos_Processor__c = '' + ShelterBuddyGetPersonsProc.class,
                aos_Payload__c = JSON.serializePretty(new Map<String, Object>{
                'page' => 1,
                'pageSize' => pageSize
            }),
                aos_Description__c = 'Load Persons',
                aos_Priority__c = 10
        );
    }

}