force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Description__c.field-meta.xml
<CustomField>
    <fullName>aos_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Group_Key__c.field-meta.xml
<CustomField>
    <fullName>aos_Group_Key__c</fullName>
    <label>Group Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Payload__c.field-meta.xml
<CustomField>
    <fullName>aos_Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Processor__c.field-meta.xml
<CustomField>
    <fullName>aos_Processor__c</fullName>
    <label>Processor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/aos_OneDriveMoveFileToFolder.cls
public without sharing class aos_OneDriveMoveFileToFolder extends aos_AbstractProcessor {

    /**
     * ==============================================================================================================
     *                                              PROCESS
     * ==============================================================================================================
     */

    public override aos_Response process(aos_Request request) {
        this.request = request;

        this.moveFileToFolder();

        return this.response;
    }


    /**
     * ==============================================================================================================
     *                                             PRIVATE METHODS
     * ==============================================================================================================
     */

    private void moveFileToFolder() {

        aos_OneDriveUtils.moveFileToFolder(
                this.request.getString('driveId'),
                this.request.getString('fileId'),
                this.request.getString('newFolderId'),
                this.request.getString('fileName')
        );

    }

    public static aos_Async_Process__c enqueueVAP(String driveId, String fileId, String newFolderId, String fileName, String newFolderName ){
        aos_Async_Process__c verticAsyncProcessVar = new aos_Async_Process__c();

        Map<String, Object> request = new Map<String, Object>{
                'driveId' => driveId,
                'fileId' => fileId,
                'newFolderId' => newFolderId,
                'fileName' => fileName
        };

        verticAsyncProcessVar.aos_Processor__c = 'OneDriveMoveFileToFolder';
        verticAsyncProcessVar.aos_Payload__c = JSON.serialize(request);
        verticAsyncProcessVar.aos_Description__c = 'Get OneDrive Folder Files';
        verticAsyncProcessVar.aos_Group_Key__c = newFolderName;

        return verticAsyncProcessVar;
    }

    /**
     * ==============================================================================================================
     *                                               STRUCTURES
     * ==============================================================================================================
     */




    // Proposed Live Templates to override Super properties:
    // aos_Request
    // aos_Response


}