force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Details__c.field-meta.xml
<CustomField>
    <fullName>aos_Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Payload__c.field-meta.xml
<CustomField>
    <fullName>aos_Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Retrying</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
                <isActive>false</isActive>
                <label>Processing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/vertic_VAPRetrySubmitProc.cls
public without sharing class vertic_VAPRetrySubmitProc extends vertic_AbstractProcessor {

    /**
     * ==============================================================================================================
     *                                              PROCESS
     * ==============================================================================================================
     */

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }


    /**
     * ==============================================================================================================
     *                                             PRIVATE METHODS
     * ==============================================================================================================
     */

    private void doSubmit() {

        String vapId = this.request.getRequiredString('id');

        aos_Async_Process__c vapVar = (aos_Async_Process__c)vertic_Utils.arrays.firstOrException(
            [SELECT Id, aos_Status__c FROM aos_Async_Process__c WHERE Id = :vapId],
            'No aos_Async_Process__c with Id: ' + vapId
        );

        if('Completed'.equalsIgnoreCase(vapVar.aos_Status__c)){
            throw new vertic_Structs.ValidationException('The process already successfully processed!');
        }

        vertic_AsyncProcess.process(new Set<String>{vapId}, new Map<String, Object>{
            'forceStatus' => true
        });

        vapVar = (aos_Async_Process__c)vertic_Utils.arrays.firstOrException(
        [SELECT Id, aos_Details__c, aos_Payload__c, aos_Status__c FROM aos_Async_Process__c WHERE Id = :vapId],
            'No aos_Async_Process__c with Id: ' + vapId
        );

        this.response.getMapper().mapFromSObject('vap', vapVar);

    }


    /**
     * ==============================================================================================================
     *                                               STRUCTURES
     * ==============================================================================================================
     */

    // Proposed Live Templates to override Super properties: 
    // vertic_request
    // vertic_response


}