force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Description__c.field-meta.xml
<CustomField>
    <fullName>aos_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Group_Key__c.field-meta.xml
<CustomField>
    <fullName>aos_Group_Key__c</fullName>
    <label>Group Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Payload__c.field-meta.xml
<CustomField>
    <fullName>aos_Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Processor__c.field-meta.xml
<CustomField>
    <fullName>aos_Processor__c</fullName>
    <label>Processor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/aos_OneDriveCheckIsExistFolderProc.cls
public without sharing class aos_OneDriveCheckIsExistFolderProc extends aos_AbstractProcessor {

    /**
     * ==============================================================================================================
     *                                              PROCESS
     * ==============================================================================================================
     */

    public override aos_Response process(aos_Request request) {
        this.request = request;

        this.checkIsExistFolder();

        return this.response;
    }


    /**
     * ==============================================================================================================
     *                                             PRIVATE METHODS
     * ==============================================================================================================
     */

    private void checkIsExistFolder() {
        this.request.put('isExistFolderId', aos_OneDriveUtils.checkIsExistFolder(this.request.getString('driveId'), this.request.getString('newOneDriveFolderName')));

        if(this.request.getString('isExistFolderId') != null){
            List<aos_Async_Process__c> asyncProcesses = new List<aos_Async_Process__c>();

            for (Object fileObj : this.request.getList('Files')){

                Map<String, Object> file = (Map<String,Object>) fileObj;

                asyncProcesses.add(aos_OneDriveMoveFileToFolder.enqueueVAP(
                        this.request.getString('driveId'),
                        (String)file.get('id'),
                        this.request.getString('isExistFolderId'),
                        (String)file.get('name'),
                        this.request.getString('newOneDriveFolderName')
                ));
            }

            insert asyncProcesses;
        } else {
            aos_OneDriveCreateFolderProc.enqueueVAP(this.request);
        }
    }

    public static void enqueueVAP(aos_Request request){
        aos_Async_Process__c verticAsyncProcessVar = new aos_Async_Process__c();

        verticAsyncProcessVar.aos_Processor__c = 'OneDriveCheckIsExistFolderProc';
        verticAsyncProcessVar.aos_Payload__c = JSON.serialize(request.getMap());
        verticAsyncProcessVar.aos_Description__c = 'Check Is Exist Folder';
        verticAsyncProcessVar.aos_Group_Key__c = request.getString('newOneDriveFolderName');

        insert verticAsyncProcessVar;
    }

    /**
     * ==============================================================================================================
     *                                               STRUCTURES
     * ==============================================================================================================
     */

    // Proposed Live Templates to override Super properties:
    // aos_Request
    // aos_Response


}