force-app/main/default/objects/animalos__Assessment__c/animalos__Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS{00000}</displayFormat>
        <label>Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Total_Score__c.field-meta.xml
<CustomField>
    <fullName>animalos__Total_Score__c</fullName>
    <label>Total Score</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/aos_Assessment_Score__c/aos_Assessment_Score__c.object-meta.xml
<CustomObject>
    <label>Assessment Score</label>
    <nameField>
        <label>Assessment Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Assessment_Score__c/fields/aos_Assessment__c.field-meta.xml
<CustomField>
    <fullName>aos_Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>animalos__Assessment__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Assessment_Score__c/fields/aos_Score__c.field-meta.xml
<CustomField>
    <fullName>aos_Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalcRollupsAssessmentTotalScore.cls
global class CalcRollupsAssessmentTotalScore extends animalos.vertic_SequentialScheduledBatch {
    global override Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
                SELECT Id, animalos__Total_Score__c
                FROM animalos__Assessment__c
                WHERE Id IN (
                    SELECT aos_Assessment__c
                    FROM aos_Assessment_Score__c
                    WHERE LastModifiedDate >= :this.sequentialBatchSetting.animalos__Last_Calculation_Datetime__c
                )
        ]);
    }

    global override void process(List<SObject> records) {

        Map<String, Object> assessmentScoresByAssessmentId = vertic_Utils.sObjects.getSObjectsListByAnyFieldMap([
                SELECT Id, aos_Score__c, aos_Assessment__c
                FROM aos_Assessment_Score__c
                WHERE aos_Assessment__c IN :records
        ], aos_Assessment_Score__c.aos_Assessment__c);

        List<animalos__Assessment__c> assessmentsForUpdate = new List<animalos__Assessment__c>();

        for (animalos__Assessment__c assessment : (List<animalos__Assessment__c>) records) {

            List<aos_Assessment_Score__c> assessmentScores = (List<aos_Assessment_Score__c>) assessmentScoresByAssessmentId.get(assessment.Id);

            Decimal totalScore = 0;
            if (assessmentScores != null) {
                for (aos_Assessment_Score__c assessmentScore : assessmentScores) {
                    totalScore += assessmentScore.aos_Score__c;
                }
            }
            assessment.animalos__Total_Score__c = totalScore;

            assessmentsForUpdate.add(assessment);
        }

        if (assessmentsForUpdate.size() > 0) {
            fflib_SObjectDomain.getTriggerEvent(animalos_AssessmentDomain.class).disableAll();
            update assessmentsForUpdate;
            fflib_SObjectDomain.getTriggerEvent(animalos_AssessmentDomain.class).enableAll();
        }
    }
}