force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Block__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Block</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Block Animals</relationshipLabel>
    <relationshipName>Block_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Unit__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Unit</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Unit Animals</relationshipLabel>
    <relationshipName>Unit_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adopted – Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted - Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Adopted – Offsite</fullName>
            </value>
            <value>
                <fullName>Adoption Pending/Hold on Property Check</fullName>
            </value>
            <value>
                <fullName>Available For Adoption</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – In Foster</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – No Web Presence</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Offsite</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Waiting Space</fullName>
            </value>
            <value>
                <fullName>Awaiting Behavioural Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Evaluation</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Retest</fullName>
            </value>
            <value>
                <fullName>Awaiting Desex</fullName>
            </value>
            <value>
                <fullName>Awaiting Euthanasia</fullName>
            </value>
            <value>
                <fullName>Awaiting Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Rescue</fullName>
            </value>
            <value>
                <fullName>Awaiting Spay/Neuter – In Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Surgery – Not Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Awaiting Transfer</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Vet Exam/Health Check</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Offsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Off Site</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Onsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal On Site</fullName>
            </value>
            <value>
                <fullName>Court Hold</fullName>
            </value>
            <value>
                <fullName>Returned to Habitat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Animal_Released_By__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal_Released_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Released By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Released_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Referral_Description__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral_Description__c</fullName>
    <label>Referral Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Scheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Scheduled_Date_Time__c</fullName>
    <label>Scheduled Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Home Inspection</fullName>
            </value>
            <value>
                <fullName>Veterinary Check</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Trial Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Adopted Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Input</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/aos_Animal__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>aos_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/aos_ReleaseAnimalQASubmitProc.cls
public without sharing class aos_ReleaseAnimalQASubmitProc extends vertic_AbstractProcessor {
    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {
        String animalId = this.request.getString('recordId');
        Decimal latitude = this.request.getDecimal('address.latitude');
        Decimal longitude = this.request.getDecimal('address.longitude');
        String city = this.request.getString('address.city');
        String state = this.request.getString('address.state');
        String postalCode = this.request.getString('address.postalCode');
        String street = this.request.getString('address.street');
        String userId = this.request.getString('userId');
        String jobId = this.request.getString('jobId');
        String description = this.request.getString('description');

        animalos__Animal__c animalVar = (animalos__Animal__c) vertic_Utils.arrays.firstOrNull(
        [
                SELECT
                        Id,
                        Name,
                        animalos__Current_Site__c,
                        animalos__Current_Block__c,
                        animalos__Current_Unit__c
                FROM animalos__Animal__c
                WHERE Id = :animalId
        ]
        );

        User userVar = (User) vertic_Utils.arrays.firstOrNull(
        [
                SELECT
                        Id,
                        FirstName,
                        LastName
                FROM User
                WHERE Id = :userId
        ]
        );

        animalos__Referral__c referralVar = new animalos__Referral__c();

        referralVar.RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Referral__c.SObjectType, 'Wildlife_Release');
        referralVar.animalos__Referral_Description__c = description;
        referralVar.animalos__Stage__c = 'New';
        referralVar.animalos__Scheduled_Date_Time__c = Datetime.now();

        if (String.isNotBlank(jobId)) {
            referralVar.animalos__Job__c = jobId;
        }
        referralVar.aos_Animal__c = animalId;

        referralVar.Name = String.format(
                '{0} {1} Wildlife Release',
                new List<String>{
                        userVar.FirstName,
                        userVar.LastName
                }
        );

        referralVar.aos_Referral_Address__CountryCode__s = 'AU';
        referralVar.aos_Referral_Address__City__s = city;
        referralVar.aos_Referral_Address__Street__s = street;
        referralVar.aos_Referral_Address__PostalCode__s = postalCode;
        referralVar.aos_Referral_Address__Latitude__s = latitude;
        referralVar.aos_Referral_Address__Longitude__s = longitude;

        switch on state {
            when 'Queensland' {
                referralVar.aos_Referral_Address__StateCode__s = 'QLD';
            }
            when 'New South Wales' {
                referralVar.aos_Referral_Address__StateCode__s = 'NSW';
            }
            when 'Victoria' {
                referralVar.aos_Referral_Address__StateCode__s = 'VIC';
            }
            when 'South Australia' {
                referralVar.aos_Referral_Address__StateCode__s = 'SA';
            }
            when 'Western Australia' {
                referralVar.aos_Referral_Address__StateCode__s = 'WA';
            }
        }

        animalVar.aos_Animal_Released_By__c = userId;
        animalVar.animalos__Stage__c = 'Out';
        animalVar.animalos__Status__c = 'Returned to Habitat';

        insert referralVar;

        animalos__Animal_Referral__c animalReferral = new animalos__Animal_Referral__c(
                animalos__Animal__c = animalVar.Id,
                animalos__Referral__c = referralVar.Id,
                animalos__Unit__c = animalVar.animalos__Current_Unit__c,
                animalos__Block__c = animalVar.animalos__Current_Block__c,
                animalos__Site__c = animalVar.animalos__Current_Site__c
        );
        insert animalReferral;

        update animalVar;
    }
}