force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Adoption_Fee__c.field-meta.xml
<CustomField>
    <fullName>animalos__Adoption_Fee__c</fullName>
    <label>Adoption Fee</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Adoption_Profile__c.field-meta.xml
<CustomField>
    <fullName>animalos__Adoption_Profile__c</fullName>
    <label>Adoption Profile</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>animalos__Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Gender__c.field-meta.xml
<CustomField>
    <fullName>animalos__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>animalos__Microchip_Number__c</fullName>
    <label>Microchip Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Neutered_Spayed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Neutered_Spayed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Neutered/Spayed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adopted – Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted - Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Adopted – Offsite</fullName>
            </value>
            <value>
                <fullName>Adoption Pending/Hold on Property Check</fullName>
            </value>
            <value>
                <fullName>Available For Adoption</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – In Foster</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – No Web Presence</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Offsite</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Waiting Space</fullName>
            </value>
            <value>
                <fullName>Awaiting Behavioural Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Evaluation</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Retest</fullName>
            </value>
            <value>
                <fullName>Awaiting Desex</fullName>
            </value>
            <value>
                <fullName>Awaiting Euthanasia</fullName>
            </value>
            <value>
                <fullName>Awaiting Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Rescue</fullName>
            </value>
            <value>
                <fullName>Awaiting Spay/Neuter – In Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Surgery – Not Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Awaiting Transfer</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Vet Exam/Health Check</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Offsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Off Site</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Onsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal On Site</fullName>
            </value>
            <value>
                <fullName>Court Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Age_Restriction__c.field-meta.xml
<CustomField>
    <fullName>aos_Age_Restriction__c</fullName>
    <inlineHelpText>How does this animal relate to people of different ages?</inlineHelpText>
    <label>Age Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no known child related issues</fullName>
                <label>All ages</label>
            </value>
            <value>
                <fullName>6 years +</fullName>
            </value>
            <value>
                <fullName>12 years +</fullName>
            </value>
            <value>
                <fullName>15 +</fullName>
            </value>
            <value>
                <fullName>adult household only</fullName>
                <label>Adult household</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Crossbreed__c.field-meta.xml
<CustomField>
    <fullName>aos_Crossbreed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Crossbreed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Home_Requirements__c.field-meta.xml
<CustomField>
    <fullName>aos_Home_Requirements__c</fullName>
    <inlineHelpText>How much company would be best for this dog?</inlineHelpText>
    <label>Home Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Someone home most/all of the time</fullName>
            </value>
            <value>
                <fullName>Someone working average work hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Id__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Id__c</fullName>
    <externalId>true</externalId>
    <label>PetRescue_Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Location__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PetRescue Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Animals (PetRescue Location)</relationshipLabel>
    <relationshipName>aos_Animals_PetRescue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Sync__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Sync__c</fullName>
    <formula>AND(
    aos_Adoption_EOI_Required__c = false,
    TEXT(animalos__Stage__c) = &quot;Adoption Ready&quot;,
    NOT(
        OR(
            ISPICKVAL(animalos__Status__c, &apos;Available For Adoption - No Web Presence&apos;)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PetRescue Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Senior_Pet__c.field-meta.xml
<CustomField>
    <fullName>aos_Senior_Pet__c</fullName>
    <formula>IF(IF( NOT( ISBLANK( animalos__Date_of_Birth__c ) ) , IF( DATE( 2000 , MONTH( animalos__Date_of_Birth__c ) , DAY( animalos__Date_of_Birth__c ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ), YEAR (Today()) - YEAR ( animalos__Date_of_Birth__c ), YEAR (Today()) - YEAR ( animalos__Date_of_Birth__c ) -1 ), 0) &gt; 8, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Senior Pet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Description__c.field-meta.xml
<CustomField>
    <fullName>aos_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Group_Key__c.field-meta.xml
<CustomField>
    <fullName>aos_Group_Key__c</fullName>
    <label>Group Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_PetRescue_Setting__mdt/aos_PetRescue_Setting__mdt.object-meta.xml
<CustomObject>
    <label>PetRescue Setting</label>
    <pluralLabel>PetRescue Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/aos_PetRescue_Setting__mdt/fields/aos_API_Key__c.field-meta.xml
<CustomField>
    <fullName>aos_API_Key__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/aos_PetRescue_Setting__mdt/fields/aos_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>aos_Location_Id__c</fullName>
    <label>Location Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AnimalPostToPetRescue.cls
global class TDTM_aos_AnimalPostToPetRescue extends animalos.TDTM.Handler implements animalos.TDTM.AfterUpdate {

    public static Boolean uploadToPetRescueIgnoringUpdateConditions = false;

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        postAnimalToPetRescue(records, oldMap);
    }

    private void postAnimalToPetRescue(List<SObject> records, Map<Id, SObject> existingRecords) {

        if ('true'.equalsIgnoreCase(aos_SettingService.getValue('PETRESCUE_PROCESSING_DISABLED'))) {
            return;
        }

        aos_AsyncProcess asyncProcess = new aos_AsyncProcess();

        Map<String, Object> petRescueSettingsByLocationId = aos_Utils.sObjects.getSObjectsByAnyFieldMap(
            aos_PetRescue_Setting__mdt.getAll().values(),
            aos_PetRescue_Setting__mdt.aos_Location_Id__c
        );

        for (animalos__Animal__c animal : (List<animalos__Animal__c>) records) {
            animalos__Animal__c existingAnimal = (animalos__Animal__c) existingRecords?.get(animal.Id);

            Boolean isUpdated = Trigger.isUpdate && existingRecords != null && existingAnimal != null &&
                (aos_Utils.sObjects.isSomeFieldChanged(
                    animal,
                    existingAnimal,
                    new List<SObjectField>{
                        animalos__Animal__c.animalos__Animal_Name__c,
                        animalos__Animal__c.animalos__Adoption_Fee__c,
                        animalos__Animal__c.animalos__Stage__c,
                        animalos__Animal__c.animalos__Status__c,
                        animalos__Animal__c.animalos__Current_Site__c,
                        animalos__Animal__c.aos_Crossbreed__c,
                        animalos__Animal__c.animalos__Date_of_Birth__c,
                        animalos__Animal__c.animalos__Neutered_Spayed__c,
                        animalos__Animal__c.animalos__Microchip_Number__c,
                        animalos__Animal__c.animalos__Adoption_Profile__c,
                        animalos__Animal__c.animalos__Primary_Breed__c,
                        animalos__Animal__c.animalos__Gender__c,
                        animalos__Animal__c.animalos__Type__c,
                        animalos__Animal__c.aos_Age_Restriction__c,
                        animalos__Animal__c.aos_Home_Requirements__c,
                        animalos__Animal__c.aos_Senior_Pet__c
                    }));

            Boolean availableForAdoption = String.isNotBlank(animal.animalos__Status__c) && animal.animalos__Status__c.containsIgnoreCase('Available For Adoption');
            Boolean notAvailableForAdoption = String.isNotBlank(animal.animalos__Status__c) && !animal.animalos__Status__c.containsIgnoreCase('Available For Adoption');
            Boolean noWebPresence = String.isNotBlank(animal.animalos__Status__c) && animal.animalos__Status__c?.containsIgnoreCase('No Web Presence');

            if ((((animal.aos_PetRescue_Sync__c || String.isNotBlank(animal.aos_PetRescue_Id__c)) && isUpdated) || uploadToPetRescueIgnoringUpdateConditions)
                && ((animal.animalos__Current_Site__c != null && petRescueSettingsByLocationId.get(animal.animalos__Current_Site__c) != null)
                || (animal.aos_PetRescue_Location__c != null && petRescueSettingsByLocationId.get(animal.aos_PetRescue_Location__c) != null))) {
                String status = '';

                if (availableForAdoption) {
                    status = 'active';
                }

                if ((notAvailableForAdoption || noWebPresence) && String.isNotBlank(animal.aos_PetRescue_Id__c)) {
                    status = 'removed';
                }

                if (String.isNotBlank(animal.animalos__Status__c) &&
                    animal.animalos__Status__c?.containsIgnoreCase('Adopted') &&
                    String.isNotBlank(animal.aos_PetRescue_Id__c)) {
                    status = 'rehomed';
                }

                if (String.isNotBlank(status)) {
                    String petRescueLocationKey = ((aos_PetRescue_Setting__mdt) petRescueSettingsByLocationId.get(animal.aos_PetRescue_Location__c))?.aos_API_Key__c;
                    String currentSiteKey = ((aos_PetRescue_Setting__mdt) petRescueSettingsByLocationId.get(animal.animalos__Current_Site__c))?.aos_API_Key__c;
                    String locationId = '';

                    if (String.isBlank(currentSiteKey) && String.isBlank(petRescueLocationKey)) {
                        continue;
                    }

                    if (String.isNotBlank(petRescueLocationKey) && String.isNotBlank(currentSiteKey) && !petRescueLocationKey.equals(currentSiteKey)) {
                        locationId = animal.animalos__Current_Site__c;
                    }

                    if (String.isNotBlank(petRescueLocationKey) && String.isNotBlank(currentSiteKey) && petRescueLocationKey.equals(currentSiteKey)) {
                        locationId = animal.aos_PetRescue_Location__c;
                    }

                    if (String.isNotBlank(petRescueLocationKey) && String.isBlank(currentSiteKey)) {
                        locationId = animal.aos_PetRescue_Location__c;
                    }

                    if (String.isBlank(petRescueLocationKey) && String.isNotBlank(currentSiteKey)) {
                        locationId = animal.animalos__Current_Site__c;
                    }

                    aos_Async_Process__c vap = aos_AsyncProcess.create(
                        aos_AnimalToPetRescueProc.class,
                        new Map<String, Object>{
                            'recordId' => animal.Id,
                            'status' => status,
                            'locationId' => locationId
                        }
                    );
                    vap.aos_Group_Key__c = animal.Id;
                    vap.aos_Description__c = 'Creation on PetRescue';
                    asyncProcess.add(vap);
                }
            }
        }
        asyncProcess.enqueue();
    }
}