force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adopted – Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted - Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Adopted – Offsite</fullName>
            </value>
            <value>
                <fullName>Adoption Pending/Hold on Property Check</fullName>
            </value>
            <value>
                <fullName>Available For Adoption</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – In Foster</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – No Web Presence</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Offsite</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Waiting Space</fullName>
            </value>
            <value>
                <fullName>Awaiting Behavioural Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Evaluation</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Retest</fullName>
            </value>
            <value>
                <fullName>Awaiting Desex</fullName>
            </value>
            <value>
                <fullName>Awaiting Euthanasia</fullName>
            </value>
            <value>
                <fullName>Awaiting Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Rescue</fullName>
            </value>
            <value>
                <fullName>Awaiting Spay/Neuter – In Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Surgery – Not Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Awaiting Transfer</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Vet Exam/Health Check</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Offsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Off Site</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Onsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal On Site</fullName>
            </value>
            <value>
                <fullName>Court Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/aos_OneDrive_File__c.object-meta.xml
<CustomObject>
    <label>OneDrive File</label>
    <nameField>
        <label>OneDrive File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OneDrive Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Animal__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>OneDrive Files</relationshipLabel>
    <relationshipName>OneDrive_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_File_ID__c.field-meta.xml
<CustomField>
    <fullName>aos_File_ID__c</fullName>
    <label>File ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_File_Link__c.field-meta.xml
<CustomField>
    <fullName>aos_File_Link__c</fullName>
    <label>File Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>aos_Folder_Name__c</fullName>
    <label>Folder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Is_Public__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/aos_RetrieveAnimalFilesGetProc.cls
public class aos_RetrieveAnimalFilesGetProc extends aos_AbstractProcessor implements aos_Structs.IRollbackable {

    private Set<String> oneDriveFileFields = new Set<String>{
            'Name',
            'aos_Animal__r.Name',
            'aos_Animal__r.animalos__Status__c',
            'aos_File_Link__c',
            'aos_Folder_Name__c',
            'aos_Is_Primary__c',
            'aos_File_ID__c',
            'aos_Is_Deleted__c',
            'LastModifiedDate'
    };

    public override aos_Response process(aos_Request request) {
        this.request = (aos_RestService.Request) request;
        this.response = (aos_RestService.Response) super.response;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {

        Integer queryLimit = String.isBlank(this.request.params.get('Limit')) ? null : Integer.valueOf(this.request.params.get('Limit'));
        String lastModifiedDateStr = this.request.params.get('LastModifiedDate');
        Date lastModifiedDate;
        if (String.isNotBlank(lastModifiedDateStr)) {
            lastModifiedDate = Date.valueOf(lastModifiedDateStr + 'T00:00:00Z');
        }
        List<String> statuses = new List<String>();
        String animalStatus = this.request.params.get('AnimalStatus');

        aos_QueryFactory queryFactory = new aos_QueryFactory(aos_OneDrive_File__c.SObjectType)
                .selectFields(this.oneDriveFileFields);

        List<String> conditions = new List<String>();
        List<String> totalConditions;

        conditions.add('aos_Is_Public__c = TRUE');
        conditions.add('aos_Folder_Name__c LIKE \'%PHOTO%\'');
        conditions.add('aos_Is_Deleted__c = FALSE');

        if (String.isNotBlank(this.request.params.get('AnimalId'))) {
            String animalId = this.request.params.get('AnimalId');
            conditions.add('aos_Animal__c = :animalId');
            totalConditions = conditions.clone();
        } else {
            if (String.isNotBlank(animalStatus)) {
                statuses = animalStatus.split(',');
                conditions.add('aos_Animal__r.animalos__Status__c IN :statuses');
            }

            if (lastModifiedDate != null) {
                conditions.add('LastModifiedDate > :lastModifiedDate');
            }

            if (String.isNotBlank(this.request.params.get('Limit'))) {
                queryFactory.setLimit(Integer.valueOf(this.request.params.get('Limit')));
            }
            totalConditions = conditions.clone();

            if (String.isNotBlank(this.request.params.get('LastRecordId'))) {
                conditions.add('Id > \'' + this.request.params.get('LastRecordId') + '\'');
            }
        }

        queryFactory.setCondition(String.join(conditions, ' AND '))
                .setOrdering(aos_OneDrive_File__c.Id, aos_QueryFactory.SortOrder.ASCENDING);
        List<aos_OneDrive_File__c> oneDriveFiles = Database.query(queryFactory.toSOQL());

        Integer recordsLeft = (Integer) Database.countQuery(('SELECT COUNT() FROM aos_OneDrive_File__c WHERE ' + String.join(conditions, ' AND '))) - (queryLimit == null ? 0 : queryLimit);

        this.response.put('oneDriveFiles', oneDriveFiles);

        Integer totalNumberOfRecords = (Integer) Database.countQuery(('SELECT COUNT() FROM aos_OneDrive_File__c WHERE ' + String.join(totalConditions, ' AND ')));
        this.response.put('recordsLeft', recordsLeft < 0 || String.isBlank(this.request.params.get('Limit')) ? 0 : recordsLeft);
        this.response.put('totalNumberOfRecords', totalNumberOfRecords);
    }

    private aos_RestService.Response response;

    protected override aos_Response getResponseInstance() {
        return new aos_RestService.Response();
    }

    /** ============================================================================================================= */

    private aos_RestService.Request request;

    public override Type getRequestType() {
        return aos_RestService.Request.class;
    }

    public override aos_Request getRequestInstance(String requestJSON) {
        return (aos_RestService.Request) JSON.deserialize(requestJSON, this.getRequestType());
    }

}