force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Action__c/animalos__Animal_Action__c.object-meta.xml
<CustomObject>
    <label>Animal Action</label>
    <nameField>
        <displayFormat>AA{00000}</displayFormat>
        <label>Animal Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Actions</relationshipLabel>
    <relationshipName>Animal_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Animal Actions</relationshipLabel>
    <relationshipName>Animal_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Medicine__c/animalos__Medicine__c.object-meta.xml
<CustomObject>
    <label>Medicine</label>
    <nameField>
        <label>Medicine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medicines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Medicine_Used__c/animalos__Medicine_Used__c.object-meta.xml
<CustomObject>
    <label>Medicine Used</label>
    <nameField>
        <displayFormat>MU{00000}</displayFormat>
        <label>Medicine Used ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medicines Used</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Medicine_Used__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Medicines Used</relationshipLabel>
    <relationshipName>Medicines_Used</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Medicine_Used__c/fields/animalos__Animal_Action__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Action</label>
    <referenceTo>animalos__Animal_Action__c</referenceTo>
    <relationshipLabel>Medicines Used (Animal Action)</relationshipLabel>
    <relationshipName>Medicines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Medicine_Used__c/fields/animalos__Medicine__c.field-meta.xml
<CustomField>
    <fullName>animalos__Medicine__c</fullName>
    <label>Medicine</label>
    <referenceTo>animalos__Medicine__c</referenceTo>
    <relationshipLabel>Medicines Used</relationshipLabel>
    <relationshipName>Medicines_Used</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Medicine_Used__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Medicines Used</relationshipLabel>
    <relationshipName>Medicines_Used</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Vet_Consult__c/animalos__Vet_Consult__c.object-meta.xml
<CustomObject>
    <label>Vet Consult</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Vet Consult ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vet Consults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Vet_Consult__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Vet Consults</relationshipLabel>
    <relationshipName>Vet_Consults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/aos_CreateAnimalActionsQASubmitProc.cls
public class aos_CreateAnimalActionsQASubmitProc extends aos_AbstractProcessor implements aos_Structs.IRollbackable {

    private aos_UnitOfWork uow = new aos_UnitOfWork(
            new List<SObjectType>{
                    animalos__Animal_Action__c.SObjectType,
                    animalos__Medicine_Used__c.SObjectType
            }
    );

    public override aos_Response process(aos_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {
        List<aos_DTO> animalActionDTOs = this.request.getDTOs('animalActions');

        for (aos_DTO animalActionDTO : animalActionDTOs) {
            animalos__Animal_Action__c animalAction = new animalos__Animal_Action__c();
            animalActionDTO.getMapper().mapToSObject(animalAction);
            this.uow.registerNew(animalAction);

            String medicineId = animalActionDTO.getString('medicineId');

            if (String.isNotBlank(medicineId)) {
                animalos__Medicine_Used__c medicineUsed = new animalos__Medicine_Used__c(
                        animalos__Medicine__c = medicineId,
                        animalos__Animal__c = animalAction.animalos__Animal__c,
                        animalos__Vet_Consult__c = animalAction.animalos__Vet_Consult__c
                );
                this.uow.registerNew(medicineUsed, animalos__Medicine_Used__c.animalos__Animal_Action__c, animalAction);
            }
        }

        this.uow.commitWork();
    }

}