force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>animalos__Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Gender__c.field-meta.xml
<CustomField>
    <fullName>animalos__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>animalos__Microchip_Number__c</fullName>
    <label>Microchip Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Colour__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Colour__c</fullName>
    <label>Primary Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agouti</fullName>
            </value>
            <value>
                <fullName>Albino</fullName>
            </value>
            <value>
                <fullName>Appaloosa</fullName>
            </value>
            <value>
                <fullName>Apricot</fullName>
            </value>
            <value>
                <fullName>Badgerface</fullName>
            </value>
            <value>
                <fullName>Bay</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Belton</fullName>
            </value>
            <value>
                <fullName>Birchen</fullName>
            </value>
            <value>
                <fullName>Biscuit</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Black Brindle</fullName>
            </value>
            <value>
                <fullName>Black Brown</fullName>
            </value>
            <value>
                <fullName>Black Otter</fullName>
            </value>
            <value>
                <fullName>Black Tan</fullName>
            </value>
            <value>
                <fullName>Blenheim</fullName>
            </value>
            <value>
                <fullName>Blonde</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Blue Bicolour</fullName>
            </value>
            <value>
                <fullName>Blue Black</fullName>
            </value>
            <value>
                <fullName>Blue Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Cream Tortoiseshell</fullName>
            </value>
            <value>
                <fullName>Blue Eyed White</fullName>
            </value>
            <value>
                <fullName>Blue Fawn</fullName>
            </value>
            <value>
                <fullName>Blue Fawn Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Marten</fullName>
            </value>
            <value>
                <fullName>Blue Merle</fullName>
            </value>
            <value>
                <fullName>Blue Otter</fullName>
            </value>
            <value>
                <fullName>Blue Point</fullName>
            </value>
            <value>
                <fullName>Blue Roan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConfirmationOfDetailsQAMetaProc.cls
public class ConfirmationOfDetailsQAMetaProc extends vertic_MetadataProcessor {

    protected List<animalos__Animal__c> animals = new List<animalos__Animal__c>();

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                // SObject Fields, e.g. Contact.Salutation
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        String recordId = this.request.getRequiredString('recordId');

        List<Object> components = new List<Object>();
        vertic_DTO dto = new vertic_DTO();

        animalos__Referral__c referral = (animalos__Referral__c) vertic_Utils.arrays.firstOrException([
                SELECT
                        Id,
                        animalos__Contact__r.Name,
                        animalos__Contact__r.Full_Address__c,
                        animalos__Contact__r.Email,
                        animalos__Contact__r.HomePhone,
                        animalos__Contact__r.npe01__WorkPhone__c,
                        animalos__Contact__r.MobilePhone,
                        animalos__Contact__r.Fax
                FROM animalos__Referral__c
                WHERE Id = :recordId
        ]);

        this.animals = [
                SELECT Id, animalos__Microchip_Number__c, animalos__Animal_Name__c,
                        animalos__Gender__c, animalos__Primary_Breed__r.Name,
                        animalos__Type__c, animalos__Primary_Colour__c,
                        animalos__Date_of_Birth__c, Microchip_Implant_Date__c
                FROM animalos__Animal__c
                WHERE Id IN (
                        SELECT animalos__Animal__c
                        FROM animalos__Animal_Referral__c
                        WHERE animalos__Referral__c = :recordId
                )
        ];

        vertic_AutoMapper autoMapper = new vertic_AutoMapper(dto)
                .getOptions()
                .setIsVisualforce(true)
                .setIsAllFields(true)
                .setDefaultFieldValue(' ')
                .getMapper()
                .mapFromSObject('referral', referral)
                .mapFromListSObjects('animals', animals, new vertic_AutoMapper.BinderQueue(new AnimalBinder(this)));


        components.add(new Component.ConfirmationOfDetails(
                dto = dto.getMap()
        ));

        this.response.dto.put('components', components);
        this.response.dto.put('head-component', new Component.ConfirmationOfDetailsStyles());
    }

    public class AnimalBinder extends vertic_AutoMapper.AbstractBinder {

        private ConfirmationOfDetailsQAMetaProc parentClass;

        public AnimalBinder(ConfirmationOfDetailsQAMetaProc parentClass) {
            this.parentClass = parentClass;
        }

        public void bind(SObject animalVar, Map<String, Object> dtoMap) {
            animalos__Animal__c animal = (animalos__Animal__c) animalVar;

            dtoMap.put('animalBreed', animal.animalos__Primary_Breed__r == null ? '' : animal.animalos__Primary_Breed__r.Name);
            dtoMap.put('isLast', this.parentClass.animals.indexOf((animalos__Animal__c) animalVar) == (this.parentClass.animals.size() - 1));
        }
    }
}