force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Adoption_Fee__c.field-meta.xml
<CustomField>
    <fullName>animalos__Adoption_Fee__c</fullName>
    <label>Adoption Fee</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Adoption_Profile__c.field-meta.xml
<CustomField>
    <fullName>animalos__Adoption_Profile__c</fullName>
    <label>Adoption Profile</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Age_for_Adoption_Website__c.field-meta.xml
<CustomField>
    <fullName>animalos__Age_for_Adoption_Website__c</fullName>
    <formula>IF(NOT(ISBLANK(animalos__Date_of_Birth__c)),
CASE(FLOOR((TODAY() - animalos__Date_of_Birth__c )/365),
0, &apos;&apos;,
1, &apos;1 Year&apos;,
TEXT(FLOOR((TODAY() - animalos__Date_of_Birth__c )/365)) &amp;&apos; Years&apos;) &amp; &apos; &apos; &amp;
CASE(FLOOR(MOD((TODAY() - animalos__Date_of_Birth__c),365)/30),
0, &apos;&apos;,
1, &apos;1 Month&apos;,
TEXT(FLOOR(MOD((TODAY() - animalos__Date_of_Birth__c),365)/30)) &amp;&apos; Months&apos;),
&apos;Unknown&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age for Adoption Website</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Unit__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Unit</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Unit Animals</relationshipLabel>
    <relationshipName>Unit_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Gender__c.field-meta.xml
<CustomField>
    <fullName>animalos__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Secondary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Secondary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Secondary Breed)</relationshipLabel>
    <relationshipName>Animals_Secondary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/aos_Shelter_ID__c.field-meta.xml
<CustomField>
    <fullName>aos_Shelter_ID__c</fullName>
    <label>Shelter ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/animalos__Movement__c.object-meta.xml
<CustomObject>
    <label>Movement</label>
    <nameField>
        <displayFormat>M{00000}</displayFormat>
        <label>Movement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Current__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Location__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdoptionScreenMetaProc.cls
public without sharing class AdoptionScreenMetaProc extends vertic_MetadataProcessor{
    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{};

        super.process(this.request);

        this.initMetadata();

        return this.response;
    }

    private void initMetadata(){
        String unitId = this.request.getString('unitId');

        animalos__Location__c locationVar = (animalos__Location__c)vertic_Utils.arrays.firstOrException(
                [
                        SELECT Id
                        FROM animalos__Location__c
                        WHERE
                                aos_Shelter_ID__c = :unitId
                                AND RecordType.DeveloperName = 'Unit'
                        LIMIT 1
                ], 'There is no unit with provided Id'
        );

        List<animalos__Movement__c> movements = [
                SELECT
                        Id,
                        animalos__Animal__c
                FROM animalos__Movement__c
                WHERE
                        animalos__Current__c = TRUE
                        AND animalos__Location__r.aos_Shelter_ID__c = :unitId
                        AND animalos__Location__r.RecordType.DeveloperName = 'Unit'
        ];

        Set<String> animalIds = vertic_Utils.sObjects.getSObjectsByAnyFieldMap(movements, animalos__Movement__c.animalos__Animal__c).keySet();

        List<animalos__Animal__c> animals = [
                SELECT
                        Id,
                        Name,
                        animalos__Animal_Name__c,
                        animalos__Adoption_Fee__c,
                        animalos__Primary_Breed__c,
                        animalos__Primary_Breed__r.Name,
                        animalos__Secondary_Breed__c,
                        animalos__Secondary_Breed__r.Name,
                        animalos__Gender__c,
                        animalos__Adoption_Profile__c,
                        animalos__Current_Unit__r.Name,
                        animalos__Age_for_Adoption_Website__c
                FROM animalos__Animal__c
                WHERE Id IN :animalIds
        ];

        this.response.getMapper().mapFromListSObjects('animals', animals, new vertic_AutoMapper.BinderQueue(
                new AnimalBinder(animals)
        ));
        this.response.put('unitId', unitId);
        this.response.put('unitHasMultipleAnimals', animals.size() > 0);
    }

    public class AnimalBinder extends vertic_AutoMapper.AbstractBinder {

        List<animalos__Animal__c> animals;

        public AnimalBinder(
                List<animalos__Animal__c> animals
        ) {
            this.animals = animals;
        }

        public void bind(SObject animalVar, Map<String, Object> dtoMap) {
            animalos__Animal__c animal = (animalos__Animal__c) animalVar;

            String photoTitle = 'Profile Photo - ' + animal.Name;

            ContentDocumentLink photoDocumentLink = (ContentDocumentLink) vertic_Utils.arrays.firstOrNull([
                    SELECT ContentDocument.LatestPublishedVersionId
                    FROM ContentDocumentLink
                    WHERE LinkedEntityId = :animal.Id
                    AND ContentDocument.Title = :photoTitle
            ]);
            if (photoDocumentLink != null) {
                ContentDistribution photoDistribution = (ContentDistribution) vertic_Utils.arrays.firstOrNull([
                        SELECT ContentDownloadUrl
                        FROM ContentDistribution
                        WHERE ContentVersionId = :photoDocumentLink.ContentDocument.LatestPublishedVersionId
                        OR ContentDocumentId = :photoDocumentLink.ContentDocumentId
                ]);

                if (photoDistribution != null) {
                    dtoMap.put('photoUrl', photoDistribution.ContentDownloadUrl);
                }
            }
        }
    }

}