force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Adoption_Fee__c.field-meta.xml
<CustomField>
    <fullName>animalos__Adoption_Fee__c</fullName>
    <label>Adoption Fee</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Adoption_Profile__c.field-meta.xml
<CustomField>
    <fullName>animalos__Adoption_Profile__c</fullName>
    <label>Adoption Profile</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_About_Me_Adoptapet__c.field-meta.xml
<CustomField>
    <fullName>aos_About_Me_Adoptapet__c</fullName>
    <label>About Me (Adoptapet)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_About_Me_PetRescue__c.field-meta.xml
<CustomField>
    <fullName>aos_About_Me_PetRescue__c</fullName>
    <label>About Me (PetRescue)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Activity_level_playfulness__c.field-meta.xml
<CustomField>
    <fullName>aos_Activity_level_playfulness__c</fullName>
    <label>Activity level/playfulness</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High (includes kittens)</fullName>
                <label>High (e.g. kittens, adolescent cats, certain breeds)</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <label>Average</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <label>Relaxed (e.g. Seniors)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Adopter_Experience__c.field-meta.xml
<CustomField>
    <fullName>aos_Adopter_Experience__c</fullName>
    <inlineHelpText>What level of training or behaviour management does this dog require?</inlineHelpText>
    <label>Behaviour and Training Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needs minimal training (e.g. senior dogs)</fullName>
            </value>
            <value>
                <fullName>Needs daily opportunities to learn about life (e.g. puppies, most dogs)</fullName>
            </value>
            <value>
                <fullName>Needs experienced owner for management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Adoption_EOI_Required__c.field-meta.xml
<CustomField>
    <fullName>aos_Adoption_EOI_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If animal requires an EOI for adoption, please tick this box. This will sync with the website.</description>
    <inlineHelpText>If animal requires an EOI for adoption, please tick this box. This will sync with the website.</inlineHelpText>
    <label>Adoption - EOI Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Age_Restriction__c.field-meta.xml
<CustomField>
    <fullName>aos_Age_Restriction__c</fullName>
    <inlineHelpText>How does this animal relate to people of different ages?</inlineHelpText>
    <label>Age Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no known child related issues</fullName>
                <label>All ages</label>
            </value>
            <value>
                <fullName>6 years +</fullName>
            </value>
            <value>
                <fullName>12 years +</fullName>
            </value>
            <value>
                <fullName>15 +</fullName>
            </value>
            <value>
                <fullName>adult household only</fullName>
                <label>Adult household</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Cat_Home_Requirements__c.field-meta.xml
<CustomField>
    <fullName>aos_Cat_Home_Requirements__c</fullName>
    <label>Cat Home Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Peaceful and quiet home environment</fullName>
            </value>
            <value>
                <fullName>Must have secure outdoor acces</fullName>
            </value>
            <value>
                <fullName>Not suited for apartment living</fullName>
            </value>
            <value>
                <fullName>Must have secure outdoor access</fullName>
                <isActive>false</isActive>
                <label>Must have secure outdoor access</label>
            </value>
            <value>
                <fullName>No apartments</fullName>
                <isActive>false</isActive>
                <label>No apartments</label>
            </value>
            <value>
                <fullName>Quiet calm household</fullName>
                <isActive>false</isActive>
                <label>Quiet calm household</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Dog_Sociability__c.field-meta.xml
<CustomField>
    <fullName>aos_Dog_Sociability__c</fullName>
    <label>Dog Sociability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appears dog social</fullName>
            </value>
            <value>
                <fullName>Can be selective (e.g. no off leash dogs parks)</fullName>
            </value>
            <value>
                <fullName>Single dog household</fullName>
            </value>
            <value>
                <fullName>Must be only dog</fullName>
                <isActive>false</isActive>
                <label>Must be only dog</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Fencing_Requirements__c.field-meta.xml
<CustomField>
    <fullName>aos_Fencing_Requirements__c</fullName>
    <inlineHelpText>What kind of fencing is needed for this dog?</inlineHelpText>
    <label>Fencing Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No special requirements</fullName>
            </value>
            <value>
                <fullName>Solid fencing (e.g. nothing to climb or height restriction)</fullName>
            </value>
            <value>
                <fullName>Secure footings (history of digging)</fullName>
            </value>
            <value>
                <fullName>6ft colorbond with footings (manageable escape history)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_General_Requirements__c.field-meta.xml
<CustomField>
    <fullName>aos_General_Requirements__c</fullName>
    <label>General Requirements</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Has breed knowledge/experience</fullName>
                <label>Breed savvy home</label>
            </value>
            <value>
                <fullName>Must go home with another dog</fullName>
                <label>Canine companion needed</label>
            </value>
            <value>
                <fullName>Has owned a cat before</fullName>
                <label>Familiar with cat behaviour and needs</label>
            </value>
            <value>
                <fullName>Must be only pet</fullName>
            </value>
            <value>
                <fullName>No dogs</fullName>
                <label>Not suitable for a home with dogs</label>
            </value>
            <value>
                <fullName>No pocket pets or birds</fullName>
                <label>Not suitable for a home with pocket pets or birds</label>
            </value>
            <value>
                <fullName>Quiet/Calm Household</fullName>
                <label>Peaceful or quiet home environment</label>
            </value>
            <value>
                <fullName>Must go home as bonded pair</fullName>
                <label>Rehomed with bonded companion</label>
            </value>
            <value>
                <fullName>STV - see relevant waiver</fullName>
                <label>Veterinary consult prior to adoption</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Indoors_Outdoors_Preference__c.field-meta.xml
<CustomField>
    <fullName>aos_Indoors_Outdoors_Preference__c</fullName>
    <label>Indoors/Outdoors Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoors</fullName>
            </value>
            <value>
                <fullName>Indoors and outdoors</fullName>
            </value>
            <value>
                <fullName>Outdoors Mainly</fullName>
            </value>
            <value>
                <fullName>Indoors when left alone</fullName>
            </value>
            <value>
                <fullName>No specific requirement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Lifestyle__c.field-meta.xml
<CustomField>
    <fullName>aos_Lifestyle__c</fullName>
    <inlineHelpText>How much exercise or time and input does this dog need (for puppies think about the breed and exercise requirements during growth)?</inlineHelpText>
    <label>Lifestyle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High (high energy working breeds, adolescent/energetic dogs)</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <label>Average</label>
            </value>
            <value>
                <fullName>Mild (e.g. seniors)</fullName>
                <label>Relaxed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TDTM_aos_AnimalPopulateAboutMe.cls
global class TDTM_aos_AnimalPopulateAboutMe extends animalos.TDTM.Handler implements animalos.TDTM.BeforeInsert, animalos.TDTM.BeforeUpdate {

    public void onBeforeInsert(List<SObject> records) {
        populateAboutMeFields(records, null);
    }

    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        populateAboutMeFields(records, oldMap);
    }

    private void populateAboutMeFields(List<SObject> records, Map<Id, SObject> existingRecords) {
        for (animalos__Animal__c animal : (List<animalos__Animal__c>) records) {
            animalos__Animal__c existingAnimal = (animalos__Animal__c) existingRecords?.get(animal.Id);

            Boolean isCreated = Trigger.isInsert && existingRecords == null;
            Boolean isUpdated = Trigger.isUpdate && existingRecords != null && existingAnimal != null && vertic_Utils.sObjects.isSomeFieldChanged(
                animal, existingAnimal, new List<SObjectField>{
                    animalos__Animal__c.animalos__Adoption_Profile__c,
                    animalos__Animal__c.aos_Age_Restriction__c,
                    animalos__Animal__c.aos_Dog_Sociability__c,
                    animalos__Animal__c.aos_Adopter_Experience__c,
                    animalos__Animal__c.aos_Fencing_Requirements__c,
                    animalos__Animal__c.aos_Indoors_Outdoors_Preference__c,
                    animalos__Animal__c.aos_Lifestyle__c,
                    animalos__Animal__c.aos_Activity_level_playfulness__c,
                    animalos__Animal__c.aos_General_Requirements__c,
                    animalos__Animal__c.aos_Cat_Home_Requirements__c,
                    animalos__Animal__c.animalos__Adoption_Fee__c,
                    animalos__Animal__c.aos_Adoption_EOI_Required__c
                }
            );

            if (isCreated || isUpdated) {
                animal.aos_About_Me_Adoptapet__c = generateAboutMeField(animal, 'Adoptapet');
                animal.aos_About_Me_PetRescue__c = generateAboutMeField(animal, 'PetRescue');
            }
        }
    }

    private String generateAboutMeField(animalos__Animal__c animal, String type) {
        String aboutMe = String.isNotBlank(animal.animalos__Adoption_Profile__c) ? animal.animalos__Adoption_Profile__c + '<br><br>' : '';
        aboutMe += String.isNotBlank(animal.aos_Age_Restriction__c) ? '<p><b>Best with Children Aged:</b> ' + animal.aos_Age_Restriction__c + '</p>' : '';

        if ('Dog'.equals(animal.animalos__Type__c) || 'Puppy'.equals(animal.animalos__Type__c)) {
            aboutMe += String.isNotBlank(animal.aos_Dog_Sociability__c) ? '<p><b>Compatibility with Other Dogs:</b> ' + animal.aos_Dog_Sociability__c + '</p>' : '';
            aboutMe += String.isNotBlank(animal.aos_Adopter_Experience__c) ? '<p><b>Training and Behaviour Needs:</b> ' + animal.aos_Adopter_Experience__c + '</p>' : '';
            aboutMe += String.isNotBlank(animal.aos_Fencing_Requirements__c) ? '<p><b>Fencing Needs:</b> ' + animal.aos_Fencing_Requirements__c + '</p>' : '';
            aboutMe += String.isNotBlank(animal.aos_Indoors_Outdoors_Preference__c) ? '<p><b>Indoors/Outdoors Living Preference:</b> ' + animal.aos_Indoors_Outdoors_Preference__c + '</p>' : '';
            aboutMe += String.isNotBlank(animal.aos_Lifestyle__c) ? '<p><b>Energy Level of Household:</b> ' + animal.aos_Lifestyle__c + '</p>' : '';
        }

        if ('Cat'.equals(animal.animalos__Type__c) || 'Kitten'.equals(animal.animalos__Type__c)) {
            aboutMe += String.isNotBlank(animal.aos_Activity_level_playfulness__c) ? '<p><b>Energy Level of Household:</b> ' + animal.aos_Activity_level_playfulness__c + '</p>' : '';

            List<String> requirements = new List<String>();
            if (String.isNotBlank(animal.aos_General_Requirements__c)) {
                requirements.add(animal.aos_General_Requirements__c.replaceAll(';', '; '));
            }
            if (String.isNotBlank(animal.aos_Cat_Home_Requirements__c)) {
                requirements.add(animal.aos_Cat_Home_Requirements__c);
            }
            String requirementsString = String.join(requirements, '. ');

            aboutMe += String.isNotBlank(requirementsString) ? '<p><b>Additional Needs:</b> ' + requirementsString + '</p>' : '';
        }

        if (!'Cat'.equals(animal.animalos__Type__c) && !'Kitten'.equals(animal.animalos__Type__c)) {
            aboutMe += String.isNotBlank(animal.aos_General_Requirements__c) ? '<p><b>Additional Needs:</b> ' + animal.aos_General_Requirements__c.replaceAll(';', '; ') + '</p>' : '';
        }

        if (!'PetRescue'.equals(type)) {
            aboutMe += animal.animalos__Adoption_Fee__c != null ? '<p><b>Adoption Fee:</b> $' + animal.animalos__Adoption_Fee__c.setScale(0) + '</p>' : '';
        }

        if (animal.aos_Adoption_EOI_Required__c) {
            aboutMe += '<br><p><a style="color: #0000EE;" href="https://www.rspcansw.org.au/standalone-eoi-form">If you are interested in giving this wonderful pet a home, please <b>CLICK HERE</b> to visit our website and complete an expression of interest.</a></p>';
        }
        return aboutMe;
    }
}