force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adopted – Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted - Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Adopted – Offsite</fullName>
            </value>
            <value>
                <fullName>Adoption Pending/Hold on Property Check</fullName>
            </value>
            <value>
                <fullName>Available For Adoption</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – In Foster</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – No Web Presence</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Offsite</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Waiting Space</fullName>
            </value>
            <value>
                <fullName>Awaiting Behavioural Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Evaluation</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Retest</fullName>
            </value>
            <value>
                <fullName>Awaiting Desex</fullName>
            </value>
            <value>
                <fullName>Awaiting Euthanasia</fullName>
            </value>
            <value>
                <fullName>Awaiting Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Rescue</fullName>
            </value>
            <value>
                <fullName>Awaiting Spay/Neuter – In Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Surgery – Not Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Awaiting Transfer</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Vet Exam/Health Check</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Offsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Off Site</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Onsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal On Site</fullName>
            </value>
            <value>
                <fullName>Court Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Id__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Id__c</fullName>
    <externalId>true</externalId>
    <label>PetRescue_Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Location__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PetRescue Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Animals (PetRescue Location)</relationshipLabel>
    <relationshipName>aos_Animals_PetRescue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_PetRescue_Setting__mdt/aos_PetRescue_Setting__mdt.object-meta.xml
<CustomObject>
    <label>PetRescue Setting</label>
    <pluralLabel>PetRescue Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/aos_PetRescue_Setting__mdt/fields/aos_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>aos_Location_Id__c</fullName>
    <label>Location Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PetRescueSyncQAMetaProc.cls
public class PetRescueSyncQAMetaProc extends vertic_MetadataProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                // SObject Fields, e.g. Contact.Salutation
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        String recordId = this.request.getRequiredString('recordId');

        animalos__Animal__c animal = (animalos__Animal__c) vertic_Utils.arrays.firstOrException([
                SELECT Id, animalos__Status__c, aos_PetRescue_Id__c, aos_PetRescue_Location__c, animalos__Current_Site__c
                FROM animalos__Animal__c
                WHERE Id = :recordId
        ]);

        String status;

        vertic_Utils.objects.throwIfBlank(animal.animalos__Status__c, 'Status is required');

        if (animal.animalos__Status__c.containsIgnoreCase('Available for Adoption')) {
            status = 'active';
        }

        if (animal.animalos__Status__c.containsIgnoreCase('No Web Presence') || (!animal.animalos__Status__c.containsIgnoreCase('Available for Adoption') && !animal.animalos__Status__c.containsIgnoreCase('Adopted'))) {
            status = 'removed';
        }

        if (animal.animalos__Status__c.containsIgnoreCase('Adopted')) {
            status = 'rehomed';
        }

        Map<String, aos_PetRescue_Setting__mdt> petRescueSettings = aos_PetRescue_Setting__mdt.getAll();
        Set<String> locationIds = new Set<String>();
        for (String key : petRescueSettings.keySet()) {
            aos_PetRescue_Setting__mdt setting = petRescueSettings.get(key);
            locationIds.add('\'' + setting.aos_Location_Id__c + '\'');
        }

        this.response.put('locationIds', String.join(new List<String>(locationIds), ', '));
        this.response.addSelectOptions('statusOptions', new List<vertic_Structs.SelectOption>{
                new vertic_Structs.SelectOption('active', 'active'),
                new vertic_Structs.SelectOption('removed', 'removed'),
                new vertic_Structs.SelectOption('rehomed', 'rehomed'),
                new vertic_Structs.SelectOption('draft', 'draft')
        });
        this.response.put('status', status);
        this.response.put('locationId', animal.aos_PetRescue_Location__c ?? animal.animalos__Current_Site__c);
        this.response.getMapper().mapFromSObject('animal', animal);
    }
}