force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Block__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Block</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Block Animals</relationshipLabel>
    <relationshipName>Block_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Unit__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Unit</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Unit Animals</relationshipLabel>
    <relationshipName>Unit_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDTM_AnimalPartnersPortalReshareRecords.cls
global class TDTM_AnimalPartnersPortalReshareRecords extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert, animalos.TDTM.AfterUpdate {
    public void onAfterInsert(List<SObject> records) {
        this.reshareRecords(records, null);
    }

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        this.reshareRecords(records, (Map<Id, animalos__Animal__c>) oldMap);
    }

    public void reshareRecords(List<animalos__Animal__c> animals, Map<Id, animalos__Animal__c> existingAnimals) {
        Set<Id> locationIdsToBeProceeded = new Set<Id>();

        for (animalos__Animal__c animalVar : animals) {
            Boolean isInsert = Trigger.isInsert;
            Boolean isUpdate = Trigger.isUpdate && existingAnimals != null &&
                    existingAnimals.containsKey(animalVar.Id);
            Boolean isCurrentSiteUpdated = isUpdate &&
                    vertic_Utils.sObjects.isSomeFieldChanged(animalVar, existingAnimals.get(animalVar.Id), new List<SObjectField>{
                            animalos__Animal__c.animalos__Current_Site__c
                    });
            Boolean isCurrentBlockUpdated = isUpdate &&
                    vertic_Utils.sObjects.isSomeFieldChanged(animalVar, existingAnimals.get(animalVar.Id), new List<SObjectField>{
                            animalos__Animal__c.animalos__Current_Block__c
                    });
            Boolean isCurrentUnitUpdated = isUpdate &&
                    vertic_Utils.sObjects.isSomeFieldChanged(animalVar, existingAnimals.get(animalVar.Id), new List<SObjectField>{
                            animalos__Animal__c.animalos__Current_Unit__c
                    });

            //either inserted or updated to new location
            if (isInsert || isCurrentSiteUpdated) {
                if (String.isNotBlank(animalVar.animalos__Current_Site__c)) {
                    locationIdsToBeProceeded.add(animalVar.animalos__Current_Site__c);
                }
                if (isCurrentSiteUpdated && String.isNotBlank(existingAnimals.get(animalVar.Id).animalos__Current_Site__c)) {
                    locationIdsToBeProceeded.add(existingAnimals.get(animalVar.Id).animalos__Current_Site__c);
                }
            }

            if (isInsert || isCurrentBlockUpdated) {
                if (String.isNotBlank(animalVar.animalos__Current_Block__c)) {
                    locationIdsToBeProceeded.add(animalVar.animalos__Current_Block__c);
                }
                if (isCurrentBlockUpdated && String.isNotBlank(existingAnimals.get(animalVar.Id).animalos__Current_Block__c)) {
                    locationIdsToBeProceeded.add(existingAnimals.get(animalVar.Id).animalos__Current_Block__c);
                }
            }

            if (isInsert || isCurrentUnitUpdated) {
                if (String.isNotBlank(animalVar.animalos__Current_Unit__c)) {
                    locationIdsToBeProceeded.add(animalVar.animalos__Current_Unit__c);
                }
                if (isCurrentUnitUpdated && String.isNotBlank(existingAnimals.get(animalVar.Id).animalos__Current_Unit__c)) {
                    locationIdsToBeProceeded.add(existingAnimals.get(animalVar.Id).animalos__Current_Unit__c);
                }
            }
        }

        if (!locationIdsToBeProceeded.isEmpty()) {
            Set<Id> userIds = vertic_Utils.sObjects.getIdFieldValues([
                    SELECT Id,User__c
                    FROM Location_Volunteer__c
                    WHERE Location__c IN :locationIdsToBeProceeded
            ], Location_Volunteer__c.User__c);

            if(!userIds.isEmpty()) {
                PartnersPortalReshareRecordsProc.submitVAPsByUserIds(userIds);
            }
        }
    }
}