force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/aos_WildlifeAnimalIntakeChildsSubmitProc.cls
public with sharing class aos_WildlifeAnimalIntakeChildsSubmitProc extends aos_AbstractProcessor {

    private aos_UnitOfWork uow = new aos_UnitOfWork(new List<SObjectType>{
            animalos__Animal__c.SObjectType,
            animalos__Referral__c.SObjectType,
            animalos__Animal_Referral__c.SObjectType
    });

    public override aos_Response process(aos_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {
        try {
            animalos__Animal__c animal = new animalos__Animal__c();
            this.request.getMapper().mapToSObject('animal', animal);
            this.uow.registerUpsert(animal);

            animalos__Referral__c referral = new animalos__Referral__c();
            this.request.getMapper().mapToSObject('referral', referral);
            this.uow.registerNew(referral);

            animalos__Animal_Referral__c animalReferral = new animalos__Animal_Referral__c();
            if (this.request.has('animal.animalReferral')) {
                this.request.getMapper().mapToSObject('animal.animalReferral', animalReferral);
            }
            this.uow.registerNew(animalReferral, animalos__Animal_Referral__c.animalos__Animal__c, animal);
            this.uow.registerRelationship(animalReferral, animalos__Animal_Referral__c.animalos__Referral__c, referral);

            Savepoint sp = Database.setSavepoint();
            this.uow.commitWork();
            Database.rollback(sp);
        } catch (Exception ex) {
            this.response.put('errorMessage', ex.getMessage());
        }
    }

}