force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Attending_Vet__c.field-meta.xml
<CustomField>
    <fullName>aos_Attending_Vet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attending Vet</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Animals_Attending_Vet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Vet_Consult__c/animalos__Vet_Consult__c.object-meta.xml
<CustomObject>
    <label>Vet Consult</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Vet Consult ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vet Consults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Vet_Consult__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Vet Consults</relationshipLabel>
    <relationshipName>Vet_Consults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Vet_Consult__c/fields/animalos__Consult_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Consult_Type__c</fullName>
    <label>Consult Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Black Tag Exam</fullName>
            </value>
            <value>
                <fullName>Cat/Kitten Castration</fullName>
            </value>
            <value>
                <fullName>Cat Flank Spey</fullName>
            </value>
            <value>
                <fullName>Cattle</fullName>
            </value>
            <value>
                <fullName>Community Outreach Initial Consult</fullName>
            </value>
            <value>
                <fullName>Dog/Puppy Castration</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Critical Distress Consultation</fullName>
            </value>
            <value>
                <fullName>Euthanasia - General</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Owner requested/Council requested</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Standard protocol exit point</fullName>
            </value>
            <value>
                <fullName>Fungassay Result: POSITIVE / NEGATIVE</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Hair Matting</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Bird</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Poultry</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Reptile</fullName>
            </value>
            <value>
                <fullName>Intake Check - Koala</fullName>
            </value>
            <value>
                <fullName>Koala Examination</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Pig Clinical Exam</fullName>
            </value>
            <value>
                <fullName>Pocket Pet Intake</fullName>
            </value>
            <value>
                <fullName>Rabbit Intake</fullName>
            </value>
            <value>
                <fullName>Recheck</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Amphibian</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Bird</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Mammal</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Reptile</fullName>
            </value>
            <value>
                <fullName>Routine Cat and Kitten SPEY/ Pregnant cat spey</fullName>
            </value>
            <value>
                <fullName>Sheep/Goat/Alpaca</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TDTM_aos_VetConsultSetAnimalAttendingVet.cls
global class TDTM_aos_VetConsultSetAnimalAttendingVet extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert, animalos.TDTM.AfterUpdate {
    public void onAfterInsert(List<SObject> records) {
        this.setAnimalAttendingVet(records, null);
    }

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> existingRecords) {
        this.setAnimalAttendingVet(records, existingRecords);
    }

    private void setAnimalAttendingVet(List<SObject> records, Map<Id, SObject> existingRecords) {
        List<animalos__Vet_Consult__c> vetConsults = new List<animalos__Vet_Consult__c>();

        for (animalos__Vet_Consult__c vetConsult : (List<animalos__Vet_Consult__c>) records) {
            Boolean isCreated = Trigger.isInsert && existingRecords == null;
            Boolean isUpdated = Trigger.isUpdate && existingRecords != null && existingRecords.get(vetConsult.Id) != null &&
                    aos_Utils.sObjects.isSomeFieldChanged(
                            vetConsult,
                            existingRecords.get(vetConsult.Id),
                            new List<sObjectField>{
                                    animalos__Vet_Consult__c.OwnerId
                            }
                    );

            if ((isCreated || isUpdated) && vetConsult.animalos__Animal__c != null && String.isNotBlank(vetConsult.animalos__Consult_Type__c) && vetConsult.animalos__Consult_Type__c.containsIgnoreCase('Intake')) {
                vetConsults.add(vetConsult);
            }
        }

        if (!vetConsults.isEmpty()) {
            Set<Id> userIds = aos_Utils.sObjects.getIdFieldValues(vetConsults, animalos__Vet_Consult__c.OwnerId);

            Map<Id, User> usersByIds = new Map<Id, User>([
                    SELECT Id, Profile.Name
                    FROM User
                    WHERE Id IN :userIds
            ]);

            List<animalos__Animal__c> animalsToUpdate = new List<animalos__Animal__c>();
            Set<Id> animalIds = new Set<Id>();


            for (animalos__Vet_Consult__c vetConsult : vetConsults) {
                User userVar = usersByIds.get(vetConsult.OwnerId);

                if (userVar == null) {
                    continue;
                }

                if (userVar.Profile.Name.containsIgnoreCase('Clinic') && !animalIds.contains(vetConsult.animalos__Animal__c)) {
                    animalsToUpdate.add(new animalos__Animal__c(
                            Id = vetConsult.animalos__Animal__c,
                            aos_Attending_Vet__c = vetConsult.OwnerId
                    ));
                    animalIds.add(vetConsult.animalos__Animal__c);
                }
            }

            update animalsToUpdate;
        }
    }
}