force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>animalos__Microchip_Number__c</fullName>
    <label>Microchip Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Tag_Number__c.field-meta.xml
<CustomField>
    <fullName>aos_Tag_Number__c</fullName>
    <label>Tag Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Indemnity_Waiver__c/animalos__Animal_Indemnity_Waiver__c.object-meta.xml
<CustomObject>
    <label>Animal Indemnity Waiver</label>
    <nameField>
        <displayFormat>AIW{00000}</displayFormat>
        <label>Animal Indemnity Waiver ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Indemnity Waivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Indemnity_Waiver__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Indemnity Waivers</relationshipLabel>
    <relationshipName>Animal_Indemnity_Waivers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Indemnity_Waiver__c/fields/animalos__Animal_Indemnity_Waiver_Content__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Indemnity_Waiver_Content__c</fullName>
    <label>Animal Indemnity Waiver Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Indemnity_Waiver__c/fields/animalos__Indemnity_Waiver__c.field-meta.xml
<CustomField>
    <fullName>animalos__Indemnity_Waiver__c</fullName>
    <label>Indemnity Waiver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>animalos__Indemnity_Waiver__c.animalos__Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>animalos__Indemnity_Waiver__c</referenceTo>
    <relationshipLabel>Animal Indemnity Waivers</relationshipLabel>
    <relationshipName>Animal_Indemnity_Waivers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Indemnity_Waiver__c/animalos__Indemnity_Waiver__c.object-meta.xml
<CustomObject>
    <label>Indemnity Waiver</label>
    <nameField>
        <label>Indemnity Waiver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indemnity Waivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IndemnityWaiverDocumentQAMetaProc.cls
public with sharing class IndemnityWaiverDocumentQAMetaProc extends vertic_MetadataProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new MetadataRequest() : (MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{

        };

        super.process(this.request);
        this.initMetadata();
        this.initComponents();

        return this.response;
    }

    private void initMetadata() {
        vertic_MetadataProcessor.MetadataRequest request = new vertic_MetadataProcessor.MetadataRequest();

        this.recordId = this.request.getRequiredString('recordId');

        request.put('recordId', this.recordId);
        request.put('isVisualForce', true);

    }

    private void initComponents() {

        List<Object> components = new List<Object>();
        vertic_DTO dto = new vertic_DTO();

        animalos__Animal__c animal = (animalos__Animal__c) vertic_Utils.arrays.firstOrException([
            SELECT Id, Name, animalos__Animal_Name__c,
                    aos_Tag_Number__c, animalos__Primary_Breed__r.Name, animalos__Microchip_Number__c, (
                SELECT Id, animalos__Animal_Indemnity_Waiver_Content__c, animalos__Indemnity_Waiver__r.Name
                FROM animalos__Animal_Indemnity_Waivers__r
                ORDER BY CreatedDate ASC
            )
            FROM animalos__Animal__c
            WHERE Id = :this.recordId
        ], 'No animal with Id ' + this.recordId);

        vertic_AutoMapper autoMapper = new vertic_AutoMapper(dto)
            .getOptions()
            .setIsVisualforce(true)
            .setIsAllFields(true)
            .setDefaultFieldValue(' ')
            .getMapper()
            .mapFromSObject('animal', animal, new vertic_AutoMapper.BinderQueue(new AnimalBinder()));

        components.add(new Component.IndemnityWaiverDocument(
            dto = dto.getMap()
        ));

        this.response.dto.put('components', components);
        this.response.dto.put('head-component', new Component.IndemnityWaiverDocumentStyles());

    }

    public class AnimalBinder extends vertic_AutoMapper.AbstractBinder {

        public void bind(SObject animalVar, Map<String, Object> dtoMap) {
            animalos__Animal__c animal = (animalos__Animal__c) animalVar;

            dtoMap.put('animalBreed', animal.animalos__Primary_Breed__r == null ? '' : animal.animalos__Primary_Breed__r.Name);
            dtoMap.put('indemnityWaiverContent', animal.animalos__Animal_Indemnity_Waivers__r);

        }
    }
    /**
     * ==============================================================================================================
     *                                         STRUCTURES AND OVERRIDES
     * ==============================================================================================================
     */

    private vertic_Response tablesData;
    private String recordId;

}