force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Age_Group__c.field-meta.xml
<CustomField>
    <fullName>animalos__Age_Group__c</fullName>
    <label>Age Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Baby 0 - 8 wks</fullName>
            </value>
            <value>
                <fullName>Juvenile 8 wks - 6 mths</fullName>
            </value>
            <value>
                <fullName>Young Adult 6 mths - 1 yr</fullName>
            </value>
            <value>
                <fullName>Adult 1 yr - 8 yrs</fullName>
            </value>
            <value>
                <fullName>Senior 8 yrs+</fullName>
            </value>
            <value>
                <fullName>Egg</fullName>
            </value>
            <value>
                <fullName>Neonate</fullName>
            </value>
            <value>
                <fullName>Juvenile</fullName>
            </value>
            <value>
                <fullName>Sub-Adult</fullName>
            </value>
            <value>
                <fullName>Young Adult</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Hatchling</fullName>
            </value>
            <value>
                <fullName>Nestling</fullName>
            </value>
            <value>
                <fullName>Chick</fullName>
            </value>
            <value>
                <fullName>Fledgling</fullName>
            </value>
            <value>
                <fullName>Immature</fullName>
            </value>
            <value>
                <fullName>Mature/adult</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Class__c.field-meta.xml
<CustomField>
    <fullName>animalos__Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Exotic</fullName>
            </value>
            <value>
                <fullName>Livestock</fullName>
            </value>
            <value>
                <fullName>Small Animal</fullName>
            </value>
            <value>
                <fullName>Wildlife</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Incoming_Date__c.field-meta.xml
<CustomField>
    <fullName>animalos__Incoming_Date__c</fullName>
    <label>Incoming Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Shelter_ID__c.field-meta.xml
<CustomField>
    <fullName>animalos__Shelter_ID__c</fullName>
    <label>Shelter ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Is_New__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_New__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is New</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Class__c.field-meta.xml
<CustomField>
    <fullName>animalos__Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Exotic</fullName>
            </value>
            <value>
                <fullName>Livestock</fullName>
            </value>
            <value>
                <fullName>Small Animal</fullName>
            </value>
            <value>
                <fullName>Wildlife</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Capacity__c.field-meta.xml
<CustomField>
    <fullName>animalos__Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foster Locations</relationshipLabel>
    <relationshipName>Foster_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Parent_Block__c.field-meta.xml
<CustomField>
    <fullName>animalos__Parent_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Block</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Sub Locations</relationshipLabel>
    <relationshipName>Sub_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/aos_Online_Adoptions__c.field-meta.xml
<CustomField>
    <fullName>aos_Online_Adoptions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Online Adoptions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/animalos__Movement__c.object-meta.xml
<CustomObject>
    <label>Movement</label>
    <nameField>
        <displayFormat>M{00000}</displayFormat>
        <label>Movement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Current__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Location__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <formula>CASE(animalos__Location__r.RecordType.DeveloperName, &apos;Foster&apos;, &apos;Foster&apos;, &apos;Offsite&apos;, &apos;Offsite&apos;, &apos;House&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Setting__c/animalos__Setting__c.object-meta.xml
<CustomObject>
    <label>Setting</label>
    <nameField>
        <label>Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Setting__c/fields/animalos__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>animalos__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Setting__c/fields/animalos__Order__c.field-meta.xml
<CustomField>
    <fullName>animalos__Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/animalos__Setting__c/fields/animalos__Processor__c.field-meta.xml
<CustomField>
    <fullName>animalos__Processor__c</fullName>
    <label>Processor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/animalos__Setting__c/fields/animalos__Setting__c.field-meta.xml
<CustomField>
    <fullName>animalos__Setting__c</fullName>
    <label>Setting</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Setting__c/fields/animalos__SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__SObject_Type__c</fullName>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Setting__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/aos_Location_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Location Volunteer</label>
    <nameField>
        <displayFormat>LV{00000}</displayFormat>
        <label>Location Volunteer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Location__c.field-meta.xml
<CustomField>
    <fullName>aos_Location__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>Location_Volunteers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_User__c.field-meta.xml
<CustomField>
    <fullName>aos_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>aos_Location_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Location_Volunteer__c/fields/aos_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>aos_Volunteer__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location Volunteers</relationshipLabel>
    <relationshipName>aos_Volunteer_Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/aos_PartnersPortalTest.cls
@IsTest
private class aos_PartnersPortalTest {
    @IsTest static void testBehavior() {
        animalos.TDTM.setupTestHandlers(new List<animalos__Setting__c>{
                new animalos__Setting__c(
                        RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Setting__c.SObjectType, 'Trigger_Handler'),
                        Name = 'TDTM_aos_LocationVolunteerPopulateUserId',
                        animalos__Processor__c = 'TDTM_aos_LocationVolunteerPopulateUserId',
                        animalos__Is_Active__c = true,
                        animalos__Order__c = 1,
                        animalos__SObject_Type__c = 'Location_Volunteer__c'
                ),
                new animalos__Setting__c(
                        RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Setting__c.SObjectType, 'Trigger_Handler'),
                        Name = 'TDTM_aos_LocationVolunteerReshareRecords',
                        animalos__Processor__c = 'TDTM_aos_LocationVolunteerReshareRecords',
                        animalos__Is_Active__c = true,
                        animalos__Order__c = 2,
                        animalos__SObject_Type__c = 'Location_Volunteer__c'
                ),
                new animalos__Setting__c(
                        RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Setting__c.SObjectType, 'Trigger_Handler'),
                        Name = 'TDTM_aos_LocationCreateVolunteer',
                        animalos__Processor__c = 'TDTM_aos_LocationCreateVolunteer',
                        animalos__Is_Active__c = true,
                        animalos__Order__c = 1,
                        animalos__SObject_Type__c = 'animalos__Location__c'
                ),
                new animalos__Setting__c(
                        RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Setting__c.SObjectType, 'Trigger_Handler'),
                        Name = 'TDTM_aos_AnimalPartnersPortalReshare',
                        animalos__Processor__c = 'TDTM_aos_AnimalPartnersPortalReshare',
                        animalos__Is_Active__c = true,
                        animalos__Order__c = 1,
                        animalos__SObject_Type__c = 'animalos__Animal__c'
                ),
                new animalos__Setting__c(
                        RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Setting__c.SObjectType, 'Trigger_Handler'),
                        Name = 'TDTM_MovementAnimalLocations',
                        animalos__Processor__c = 'TDTM_MovementAnimalLocations',
                        animalos__Is_Active__c = true,
                        animalos__Order__c = 1,
                        animalos__SObject_Type__c = 'animalos__Movement__c'
                ),
                new animalos__Setting__c(
                        RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Setting__c.SObjectType, 'Trigger_Handler'),
                        Name = 'TDTM_aos_UserUpdateRelatedLocationVol',
                        animalos__Processor__c = 'TDTM_aos_UserUpdateRelatedLocationVol',
                        animalos__Is_Active__c = true,
                        animalos__Order__c = 1,
                        animalos__SObject_Type__c = 'User'
                ),
                new animalos__Setting__c(
                        RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Setting__c.SObjectType, 'Trigger_Handler'),
                        Name = 'TDTM_aos_UserDisableRelatedVolunteer',
                        animalos__Processor__c = 'TDTM_aos_UserDisableRelatedVolunteer',
                        animalos__Is_Active__c = true,
                        animalos__Order__c = 2,
                        animalos__SObject_Type__c = 'User'
                )
        });

        Contact contactVar = new Contact(
                LastName = 'Testing'
        );
        insert contactVar;

        Profile profileVar = [
                SELECT Id
                FROM Profile
                WHERE Name IN :PartnersPortalReshareRecordsProc.PARTNERS_PORTAL_PROFILE_NAMES AND Name != 'Customer Community Plus Login User'
                LIMIT 1
        ];

        User userVar = new User(
                ContactId = contactVar.Id,
                Alias = 'standard',
                Email = 'standarduser@testorg.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Testing',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = profileVar.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                Username = 'testuserforsecondresource@test.com'
        );
        insert userVar;

        Contact contactVar2 = new Contact(
                LastName = 'Testing 2'
        );
        insert contactVar2;

        User userVar2 = new User(
                ContactId = contactVar2.Id,
                Alias = 'alias2',
                Email = 'standarduser2@testorg.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Testing 2',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = profileVar.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                Username = 'testuserforsecondresource2@test.com'
        );
        insert userVar2;

        String siteRecordType = vertic_Utils.sObjects.recordTypeIdByAPIName(
                animalos__Location__c.SObjectType,
                'Site'
        );

        String fosterRecordType = vertic_Utils.sObjects.recordTypeIdByAPIName(
                animalos__Location__c.SObjectType,
                'Foster'
        );

        animalos__Location__c siteLocation = new animalos__Location__c(
                RecordTypeId = siteRecordType,
                Name = 'Test Site',
                aos_Online_Adoptions__c = true
        );
        insert siteLocation;

        animalos__Location__c siteLocation2 = new animalos__Location__c(
                RecordTypeId = siteRecordType,
                Name = 'Test Site 2',
                aos_Online_Adoptions__c = true
        );
        insert siteLocation2;

        //test TDTM_aos_LocationCreateVolunteer
        animalos__Location__c fosterLocation = new animalos__Location__c(
                RecordTypeId = fosterRecordType,
                Name = 'Test Foster',
                animalos__Parent_Block__c = siteLocation2.Id,
                animalos__Contact__c = contactVar.Id
        );
        insert fosterLocation;

        fosterLocation.animalos__Contact__c = contactVar2.Id;
        update fosterLocation;

        System.assert([SELECT Id FROM aos_Location_Volunteer__c WHERE aos_Volunteer__c = :contactVar2.Id AND aos_Location__c = :fosterLocation.Id].isEmpty() != true);
        System.assert([SELECT Id FROM aos_Location_Volunteer__c WHERE aos_Volunteer__c = :contactVar.Id AND aos_Location__c = :fosterLocation.Id].isEmpty() == true);

        List<aos_Location_Volunteer__c> allLocationVolunteers = [
                SELECT Id, aos_User__r.Name, aos_Location__r.RecordType.DeveloperName, aos_Location__r.Name, aos_Volunteer__r.Name, aos_User__c
                FROM aos_Location_Volunteer__c
        ];

        animalos__Breed__c animalBreed = new animalos__Breed__c(
                animalos__Class__c = 'Domestic',
                animalos__Type__c = 'Dog',
                Name = 'Test Breed'
        );
        insert animalBreed;

        animalos__Animal__c animal = new animalos__Animal__c(
                animalos__Animal_Name__c = 'Test',
                animalos__Incoming_Date__c = Datetime.now(),
                animalos__Class__c = 'Domestic',
                animalos__Type__c = 'Dog',
                aos_Is_New__c = false,
                animalos__Shelter_ID__c = '123123123ee',
                animalos__Current_Site__c = siteLocation.Id,
                animalos__Age_Group__c = 'Young Adult 6 mths - 1 yr',
                animalos__Primary_Breed__c = animalBreed.Id
        );
        insert animal;

        animalos__Animal__c animal2 = new animalos__Animal__c(
                animalos__Animal_Name__c = 'Test',
                animalos__Incoming_Date__c = Datetime.now(),
                animalos__Class__c = 'Domestic',
                animalos__Type__c = 'Dog',
                aos_Is_New__c = false,
                animalos__Current_Site__c = siteLocation2.Id,
                animalos__Age_Group__c = 'Young Adult 6 mths - 1 yr',
                animalos__Primary_Breed__c = animalBreed.Id,
                animalos__Shelter_ID__c = '123123'
        );
        insert animal2;

        //Test TDTM_aos_LocationVolunteerReshareRecords
        aos_Location_Volunteer__c locationVolunteerVar = new aos_Location_Volunteer__c(
                aos_Location__c = siteLocation.Id,
                aos_Volunteer__c = contactVar.Id
        );
        insert locationVolunteerVar;

        aos_Location_Volunteer__c locationVolunteerVar2 = new aos_Location_Volunteer__c(
                aos_Location__c = siteLocation2.Id,
                aos_Volunteer__c = contactVar2.Id
        );
        insert locationVolunteerVar2;

        System.assert([SELECT COUNT() FROM aos_Async_Process__c] == 2);

        //Test TDTM_aos_LocationVolunteerPopulateUserId
        locationVolunteerVar = [
                SELECT Id, aos_Location__c, aos_Volunteer__c, aos_User__c
                FROM aos_Location_Volunteer__c
                WHERE Id = :locationVolunteerVar.Id
        ];

        System.assertEquals(userVar.Id, locationVolunteerVar.aos_User__c);

        //Test TDTM_aos_AnimalPartnersPortalReshare
        animalos__Location__c blockLocation = new animalos__Location__c(
                RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Location__c.SObjectType, 'Block'),
                Name = 'Test Block',
                animalos__Parent_Block__c = siteLocation2.Id
        );
        insert blockLocation;

        animalos__Location__c unitLocation = new animalos__Location__c(
                RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Location__c.SObjectType, 'Unit'),
                Name = 'Test Unit',
                animalos__Parent_Block__c = blockLocation.Id,
                animalos__Capacity__c = 10
        );
        insert unitLocation;

        animalos__Movement__c movementVar = new animalos__Movement__c(
                animalos__Animal__c = animal.Id,
                animalos__Location__c = unitLocation.Id,
                animalos__Current__c = true,
                animalos__Start_Date_Time__c = Datetime.now()
        );
        insert movementVar;

        System.assert([SELECT COUNT() FROM aos_Async_Process__c] == 2);

        //Test PartnersPortalReshareRecordsProc
        aos_Location_Volunteer__c locationVolunteerBlockVar = new aos_Location_Volunteer__c(
                aos_Location__c = blockLocation.Id,
                aos_Volunteer__c = contactVar2.Id
        );
        insert locationVolunteerBlockVar;

        aos_Location_Volunteer__c locationVolunteerUnitVar = new aos_Location_Volunteer__c(
                aos_Location__c = unitLocation.Id,
                aos_Volunteer__c = contactVar2.Id
        );
        insert locationVolunteerUnitVar;

        animalos__Location__c offsiteLocation = new animalos__Location__c(
                RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Location__c.SObjectType, 'Offsite'),
                Name = 'Test Offsite'
        );
        insert offsiteLocation;

        aos_Location_Volunteer__c locationVolunteerOffsiteVar = new aos_Location_Volunteer__c(
                aos_Location__c = offsiteLocation.Id,
                aos_Volunteer__c = contactVar2.Id
        );
        insert locationVolunteerOffsiteVar;

        Test.startTest();
        Set<Id> vapIds = vertic_Utils.sObjects.getIdFieldValues([
                SELECT Id
                FROM aos_Async_Process__c
                WHERE aos_Group_Key__c = :userVar2.Id
                LIMIT 1
        ], aos_Async_Process__c.Id);
        vertic_AsyncProcessBatch.run(new List<Id>(vapIds));
        Test.stopTest();
        //both animalVar and animalVar2 should be shared with userVar2
        System.assertEquals(2, [SELECT COUNT() FROM animalos__Animal__Share WHERE UserOrGroupId = :userVar2.Id]);
        //all locations except siteLocation should be shared with userVar2
        System.assertEquals(5, [SELECT COUNT() FROM animalos__Location__Share WHERE UserOrGroupId = :userVar2.Id]);


        System.runAs(new User(Id = UserInfo.getUserId())) {
            userVar2.IsActive = false;
            update userVar2;

            System.assertEquals(0, [
                    SELECT COUNT()
                    FROM aos_Location_Volunteer__c
                    WHERE aos_Status__c = 'Active' AND aos_Volunteer__c = :userVar2.ContactId
            ]);
        }

    }
}