force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Most_Recent_Behaviour_Observation__c.field-meta.xml
<CustomField>
    <fullName>aos_Most_Recent_Behaviour_Observation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Most Recent Behaviour Observation</label>
    <referenceTo>animalos__Assessment__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/animalos__Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS{00000}</displayFormat>
        <label>Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Assessment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Assessment_Date_Time__c</fullName>
    <inlineHelpText>Date and Time of assessment</inlineHelpText>
    <label>Assessment Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AssessmentAssignRecentBehaviour.cls
global class TDTM_aos_AssessmentAssignRecentBehaviour extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert {

    public void onAfterInsert(List<SObject> records) {
        assignMostRecentBehaviourObservation(records);
    }

    private void assignMostRecentBehaviourObservation(List<SObject> records) {
        Set<Id> animalIds = aos_Utils.sObjects.getIdFieldValues(
            records,
            animalos__Assessment__c.animalos__Animal__c
        );

        Map<Id, SObject> animalsByIds = new Map<Id, SObject>([
            SELECT Id, aos_Most_Recent_Behaviour_Observation__c, aos_Most_Recent_Behaviour_Observation__r.animalos__Assessment_Date_Time__c
            FROM animalos__Animal__c
            WHERE Id IN :animalIds
        ]);

        Id behaviourObservationCanineRecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(
            animalos__Assessment__c.SObjectType,
            'Behaviour_Observation_Canine'
        );
        Id behaviourObservationFelineRecordTypeId = aos_Utils.sObjects.recordTypeIdByAPIName(
            animalos__Assessment__c.SObjectType,
            'Behaviour_Observation_Feline'
        );

        for (animalos__Assessment__c assessment : (List<animalos__Assessment__c>) records) {
            if (behaviourObservationCanineRecordTypeId.equals(assessment.RecordTypeId) || behaviourObservationFelineRecordTypeId.equals(assessment.RecordTypeId)) {
                animalos__Animal__c animal = (animalos__Animal__c) animalsByIds.get(assessment.animalos__Animal__c);

                if (animal != null) {
                    animal.aos_Most_Recent_Behaviour_Observation__c = animal.aos_Most_Recent_Behaviour_Observation__c == null ?
                        assessment.Id :
                        animal.aos_Most_Recent_Behaviour_Observation__r.animalos__Assessment_Date_Time__c > assessment.animalos__Assessment_Date_Time__c ?
                            animal.aos_Most_Recent_Behaviour_Observation__c :
                            assessment.Id;

                    animalsByIds.put(animal.Id, animal);
                }
            }
        }

        update animalsByIds.values();
    }
}