force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/animalos__Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS{00000}</displayFormat>
        <label>Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/fields/aos_Site__c.field-meta.xml
<CustomField>
    <fullName>aos_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>aos_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AssessmentUpdateSite.cls
global class TDTM_aos_AssessmentUpdateSite extends animalos.TDTM.Handler implements animalos.TDTM.BeforeInsert, animalos.TDTM.BeforeUpdate {

    public void onBeforeInsert(List<SObject> records) {
        updateAssessmentMonthsKnownAndSite(records);
    }

    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        updateAssessmentMonthsKnownAndSite(records);
    }

    private void updateAssessmentMonthsKnownAndSite(List<SObject> records) {
        Set<Id> animalIds = vertic_Utils.sObjects.getIdFieldValues(
            records,
            animalos__Assessment__c.animalos__Animal__c
        );

        Map<Id, SObject> animalsById = new Map<Id, SObject>([
            SELECT Id, animalos__Current_Site__c
            FROM animalos__Animal__c
            WHERE Id IN :animalIds
        ]);

        for (animalos__Assessment__c assessment : (List<animalos__Assessment__c>) records) {
            animalos__Animal__c animal = (animalos__Animal__c) animalsById.get(assessment.animalos__Animal__c);

            assessment.aos_Site__c = animal?.animalos__Current_Site__c;
        }
    }
}