force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/aos_Sync_All_Animals__c.field-meta.xml
<CustomField>
    <fullName>aos_Sync_All_Animals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync All Animals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/animalos__Movement__c.object-meta.xml
<CustomObject>
    <label>Movement</label>
    <nameField>
        <displayFormat>M{00000}</displayFormat>
        <label>Movement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Current__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Location__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <formula>CASE(animalos__Location__r.RecordType.DeveloperName, &apos;Foster&apos;, &apos;Foster&apos;, &apos;Offsite&apos;, &apos;Offsite&apos;, &apos;House&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_MovementAssignToIncomingAnimals.cls
global class TDTM_aos_MovementAssignToIncomingAnimals extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert {

    public void onAfterInsert(List<SObject> records) {
        handleAssignToIncomingAnimals(records, null);
    }

    private void handleAssignToIncomingAnimals(List<SObject> records, Map<Id, SObject> existingRecords) {
        List<animalos__Movement__c> movementsWithCondition = new List<animalos__Movement__c>();

        Set<Id> locationIds = aos_Utils.sObjects.getIdFieldValues(records, animalos__Movement__c.animalos__Location__c);

        Map<String, animalos__Location__c> locationsById = new Map<String, animalos__Location__c>([
            SELECT Id, Name, aos_Sync_All_Animals__c
            FROM animalos__Location__c
            WHERE Id IN :locationIds
                AND RecordType.DeveloperName != 'Foster'
                AND RecordType.DeveloperName != 'Offsite'
        ]);

        for (animalos__Movement__c movementItem : (List<animalos__Movement__c>) records) {
            if (movementItem.animalos__Location__c != null && movementItem.animalos__Current__c == true) {
                animalos__Location__c locationVar = locationsById.get(movementItem.animalos__Location__c);

                if (locationVar != null && movementItem.animalos__Location__c == locationVar.Id) {
                    movementsWithCondition.add(movementItem);
                }
            }
        }

        if (movementsWithCondition.isEmpty()) return;

        Set<Id> animalsIds = aos_Utils.sObjects.getIdFieldValues(movementsWithCondition, animalos__Movement__c.animalos__Animal__c);

        List<SObject> animalsRecords = [
            SELECT Id, animalos__Stage__c, animalos__Type__c
            FROM animalos__Animal__c
            WHERE Id IN :animalsIds
                AND animalos__Stage__c != 'Pre-Intake'
                AND animalos__Stage__c != 'Out'
        ];

        if (animalsRecords.isEmpty()) return;

        aos_AssignToIncomingAnimalsService.handleAssignToIncomingAnimals(animalsRecords);
    }
}