force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Behaviour_Flag__c.field-meta.xml
<CustomField>
    <fullName>animalos__Behaviour_Flag__c</fullName>
    <formula>IF(
ISBLANK(animalos__Behaviour_Flag_Condition__c),
IMAGE(LEFT($Api.Partner_Server_URL_620, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_620)) + &quot;resource/animalos__indicatorIcons/default.png&quot;,&quot;DEFAULT&quot;, 30, -1),
IF(
animalos__Behaviour_Flag_Condition__c = &quot;GREEN&quot;,
IMAGE(LEFT($Api.Partner_Server_URL_620, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_620)) + &quot;resource/animalos__indicatorIcons/green.png&quot;,&quot;GREEN&quot;, 30, -1),
IF(
animalos__Behaviour_Flag_Condition__c = &quot;YELLOW&quot;,
IMAGE(LEFT($Api.Partner_Server_URL_620, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_620)) + &quot;resource/animalos__indicatorIcons/yellow.png&quot;,&quot;YELLOW&quot;, 30, -1),
IF(
animalos__Behaviour_Flag_Condition__c = &quot;RED&quot;,
IMAGE(LEFT($Api.Partner_Server_URL_620, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_620)) + &quot;resource/animalos__indicatorIcons/red.png&quot;,&quot;RED&quot;, 30, -1),
&quot;&quot;
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Behaviour Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Behaviour_Flag_Condition__c.field-meta.xml
<CustomField>
    <fullName>animalos__Behaviour_Flag_Condition__c</fullName>
    <label>Behaviour Flag Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/animalos__Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS{00000}</displayFormat>
        <label>Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Assessment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Assessment_Date_Time__c</fullName>
    <inlineHelpText>Date and Time of assessment</inlineHelpText>
    <label>Assessment Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/fields/aos_Flags__c.field-meta.xml
<CustomField>
    <fullName>aos_Flags__c</fullName>
    <label>Flags</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AssessmentUpdateAnimalFlag.cls
global class TDTM_aos_AssessmentUpdateAnimalFlag extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert, animalos.TDTM.AfterUpdate {

    public void onAfterInsert(List<SObject> records) {
        updateAnimalFlag(records);
    }

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        updateAnimalFlag(records);
    }

    private void updateAnimalFlag(List<SObject> records) {
        Set<Id> animalIds = aos_Utils.sObjects.getIdFieldValues(
            records,
            animalos__Assessment__c.animalos__Animal__c
        );

        Map<String, Object> animalsByIds = aos_Utils.sObjects.getSObjectsByAnyFieldMap([
            SELECT Id, animalos__Type__c, animalos__Behaviour_Flag__c, animalos__Behaviour_Flag_Condition__c
            FROM animalos__Animal__c
            WHERE Id IN :animalIds
        ], animalos__Animal__c.Id);

        Map<String, Object> lastBehaviourObservationByAnimal = new Map<String, Object>();
        Map<String, Object> lastFelineBehaviourObservationByAnimal = new Map<String, Object>();
        Map<String, Object> lastBehaviourAssessmentByAnimal = new Map<String, Object>();

        for (animalos__Assessment__c assessment : [
            SELECT Id, aos_Flags__c, animalos__Animal__c, RecordType.DeveloperName
            FROM animalos__Assessment__c
            WHERE animalos__Animal__c IN :animalIds AND animalos__Assessment_Date_Time__c != NULL AND
            RecordType.DeveloperName IN ('aos_Behaviour_Observation_Canine', 'aos_Behaviour_Observation_Feline', 'aos_Behaviour_Evaluation_Canine', 'aos_Behaviour_Evaluation_Feline')
            ORDER BY animalos__Assessment_Date_Time__c ASC
        ]) {
            switch on assessment.RecordType.DeveloperName {
                when 'aos_Behaviour_Observation_Canine' {
                    lastBehaviourObservationByAnimal.put(assessment.animalos__Animal__c, assessment);
                }
                when 'aos_Behaviour_Observation_Feline' {
                    lastFelineBehaviourObservationByAnimal.put(assessment.animalos__Animal__c, assessment);
                }
                when 'aos_Behaviour_Evaluation_Canine', 'aos_Behaviour_Evaluation_Feline' {
                    lastBehaviourAssessmentByAnimal.put(assessment.animalos__Animal__c, assessment);
                }
            }
        }

        for (animalos__Animal__c animal : (List<animalos__Animal__c>) animalsByIds.values()) {
            animalos__Assessment__c behaviourObservation;
            animalos__Assessment__c behaviourAssessment = (animalos__Assessment__c) lastBehaviourAssessmentByAnimal.get(animal.Id);

            if ('Cat'.equals(animal.animalos__Type__c)) {
                behaviourObservation = (animalos__Assessment__c) lastFelineBehaviourObservationByAnimal.get(animal.Id);
            } else {
                behaviourObservation = (animalos__Assessment__c) lastBehaviourObservationByAnimal.get(animal.Id);
            }

            String behaviourObservationFlag = aos_AssessmentService.defineBehaviourFlag(behaviourObservation);
            String behaviourAssessmentFlag = aos_AssessmentService.defineBehaviourFlag(behaviourAssessment);

            if ('RED'.equals(behaviourAssessmentFlag) || 'RED'.equals(behaviourObservationFlag)) {
                animal.animalos__Behaviour_Flag_Condition__c = 'RED';
            } else if ('YELLOW'.equals(behaviourAssessmentFlag) || 'YELLOW'.equals(behaviourObservationFlag)) {
                animal.animalos__Behaviour_Flag_Condition__c = 'YELLOW';
            } else {
                animal.animalos__Behaviour_Flag_Condition__c = 'GREEN';
            }

            animalsByIds.put(animal.Id, animal);
        }

        update (List<SObject>) animalsByIds.values();
    }
}