force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/aos_Type__c.field-meta.xml
<CustomField>
    <fullName>aos_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TDTM_AnimalReferralSetAnimalType.cls
global class TDTM_AnimalReferralSetAnimalType extends animalos.TDTM.Handler implements animalos.TDTM.BeforeInsert {

    public void onBeforeInsert(List<SObject> records) {
        this.setAnimalType(records);
    }

    public void setAnimalType(List<SObject> records) {
        Set<Id> animalIds = vertic_Utils.sObjects.getIdFieldValues(records, animalos__Animal_Referral__c.animalos__Animal__c);

        Map<Id, animalos__Animal__c> animalsByIds = new Map<Id, animalos__Animal__c>([
                SELECT Id, animalos__Type__c
                FROM animalos__Animal__c
                WHERE Id IN :animalIds
        ]);

        for (animalos__Animal_Referral__c animalReferral : (List<animalos__Animal_Referral__c>) records) {
            animalos__Animal__c animal = animalsByIds.get(animalReferral.animalos__Animal__c);
            animalReferral.aos_Type__c = animal.animalos__Type__c;
        }
    }
}