force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Class__c.field-meta.xml
<CustomField>
    <fullName>animalos__Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Exotic</fullName>
            </value>
            <value>
                <fullName>Livestock</fullName>
            </value>
            <value>
                <fullName>Small Animal</fullName>
            </value>
            <value>
                <fullName>Wildlife</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Gender__c.field-meta.xml
<CustomField>
    <fullName>animalos__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Colour__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Colour__c</fullName>
    <label>Primary Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agouti</fullName>
            </value>
            <value>
                <fullName>Albino</fullName>
            </value>
            <value>
                <fullName>Appaloosa</fullName>
            </value>
            <value>
                <fullName>Apricot</fullName>
            </value>
            <value>
                <fullName>Badgerface</fullName>
            </value>
            <value>
                <fullName>Bay</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Belton</fullName>
            </value>
            <value>
                <fullName>Birchen</fullName>
            </value>
            <value>
                <fullName>Biscuit</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Black Brindle</fullName>
            </value>
            <value>
                <fullName>Black Brown</fullName>
            </value>
            <value>
                <fullName>Black Otter</fullName>
            </value>
            <value>
                <fullName>Black Tan</fullName>
            </value>
            <value>
                <fullName>Blenheim</fullName>
            </value>
            <value>
                <fullName>Blonde</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Blue Bicolour</fullName>
            </value>
            <value>
                <fullName>Blue Black</fullName>
            </value>
            <value>
                <fullName>Blue Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Cream Tortoiseshell</fullName>
            </value>
            <value>
                <fullName>Blue Eyed White</fullName>
            </value>
            <value>
                <fullName>Blue Fawn</fullName>
            </value>
            <value>
                <fullName>Blue Fawn Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Marten</fullName>
            </value>
            <value>
                <fullName>Blue Merle</fullName>
            </value>
            <value>
                <fullName>Blue Otter</fullName>
            </value>
            <value>
                <fullName>Blue Point</fullName>
            </value>
            <value>
                <fullName>Blue Roan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Secondary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Secondary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Secondary Breed)</relationshipLabel>
    <relationshipName>Animals_Secondary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Secondary_Colour__c.field-meta.xml
<CustomField>
    <fullName>animalos__Secondary_Colour__c</fullName>
    <label>Secondary Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agouti</fullName>
            </value>
            <value>
                <fullName>Albino</fullName>
            </value>
            <value>
                <fullName>Appaloosa</fullName>
            </value>
            <value>
                <fullName>Apricot</fullName>
            </value>
            <value>
                <fullName>Badgerface</fullName>
            </value>
            <value>
                <fullName>Bay</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Belton</fullName>
            </value>
            <value>
                <fullName>Birchen</fullName>
            </value>
            <value>
                <fullName>Biscuit</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Black Brindle</fullName>
            </value>
            <value>
                <fullName>Black Brown</fullName>
            </value>
            <value>
                <fullName>Black Otter</fullName>
            </value>
            <value>
                <fullName>Black Tan</fullName>
            </value>
            <value>
                <fullName>Blenheim</fullName>
            </value>
            <value>
                <fullName>Blonde</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Blue Bicolour</fullName>
            </value>
            <value>
                <fullName>Blue Black</fullName>
            </value>
            <value>
                <fullName>Blue Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Cream Tortoiseshell</fullName>
            </value>
            <value>
                <fullName>Blue Eyed White</fullName>
            </value>
            <value>
                <fullName>Blue Fawn</fullName>
            </value>
            <value>
                <fullName>Blue Fawn Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Marten</fullName>
            </value>
            <value>
                <fullName>Blue Merle</fullName>
            </value>
            <value>
                <fullName>Blue Otter</fullName>
            </value>
            <value>
                <fullName>Blue Point</fullName>
            </value>
            <value>
                <fullName>Blue Roan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Class__c.field-meta.xml
<CustomField>
    <fullName>animalos__Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Exotic</fullName>
            </value>
            <value>
                <fullName>Livestock</fullName>
            </value>
            <value>
                <fullName>Small Animal</fullName>
            </value>
            <value>
                <fullName>Wildlife</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/animalos__Movement__c.object-meta.xml
<CustomObject>
    <label>Movement</label>
    <nameField>
        <displayFormat>M{00000}</displayFormat>
        <label>Movement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <formula>CASE(animalos__Location__r.RecordType.DeveloperName, &apos;Foster&apos;, &apos;Foster&apos;, &apos;Offsite&apos;, &apos;Offsite&apos;, &apos;House&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Setting__c/animalos__Setting__c.object-meta.xml
<CustomObject>
    <label>Setting</label>
    <nameField>
        <label>Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Setting__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WildlifeAnimalIntakeMetaProc.cls
public with sharing class WildlifeAnimalIntakeMetaProc extends vertic_MetadataProcessor {

    private Set<String> animalLookupFields = new Set<String>{
            'animalos__Animal_Name__c',
            'animalos__Class__c',
            'animalos__Gender__c',
            'animalos__Type__c',
            'animalos__Primary_Breed__c',
            'animalos__Primary_Breed__r.Name',
            'animalos__Secondary_Breed__c',
            'animalos__Secondary_Breed__r.Name',
            'animalos__Primary_Colour__c',
            'animalos__Secondary_Colour__c',
            'animalos__Stage__c',
            'animalos__Status__c',
            'animalos__Age_Group__c',
            'animalos__Shelter_ID__c',
            'KRS_Number__c'
    };

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                animalos__Animal__c.animalos__Class__c,
                animalos__Animal__c.animalos__Primary_Colour__c,
                animalos__Animal__c.animalos__Secondary_Colour__c,
                animalos__Animal__c.animalos__Gender__c,
                animalos__Animal__c.animalos__Type__c,
                animalos__Animal__c.animalos__Age_Group__c,
                animalos__Movement__c.animalos__Movement_Reason__c
        };

        this.request.dependentFieldsBySObjectType = new Map<SObjectType, Map<SObjectField, SObjectField>>{
                animalos__Animal__c.SObjectType => new Map<SObjectField, SObjectField>{
                        animalos__Animal__c.animalos__Status__c => animalos__Animal__c.animalos__Stage__c,
                        animalos__Animal__c.animalos__Type__c => animalos__Animal__c.animalos__Class__c,
                        animalos__Animal__c.animalos__Age_Group__c => animalos__Animal__c.animalos__Type__c
                }
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {

        animalos__Referral__c referral = new animalos__Referral__c();
        this.request.getMapper().mapToSObject('referral', referral);
        this.response.getMapper().mapFromSObject('referral', referral);

        String referralRecordTypeDeveloperName = vertic_Utils.sObjects.recordTypeAPINameById(animalos__Referral__c.SObjectType, referral.RecordTypeId) ?? '';
        vertic_Utils.strings.throwIfBlank(referralRecordTypeDeveloperName, 'Referral Record Type is required.');

        this.response.put('animalLookupFields', String.join(new List<String>(this.animalLookupFields), ', '));
        this.response.put('hasEnhancedAccess', this.hasEnhancedAccess());
        this.response.put('recordTypeDeveloperName', referralRecordTypeDeveloperName);
        this.response.selectOptions.put('animalosStageOptions', vertic_Utils.picklists.getPicklistValuesAsSelectOptions(animalos__Animal__c.animalos__Stage__c));

        animalos__Setting__c startReferralSetting = (animalos__Setting__c) vertic_Utils.arrays.firstOrNull([
                SELECT Id, animalos__Setting__c
                FROM animalos__Setting__c
                WHERE RecordType.DeveloperName = 'Start_Referral'
                WITH USER_MODE
        ]);

        if (startReferralSetting == null || String.isBlank(startReferralSetting.animalos__Setting__c)) {
            return;
        }

        vertic_DTO settingDTO = new vertic_DTO(startReferralSetting.animalos__Setting__c);

        String blockCondition = settingDTO.getString('blockCondition');

        if (String.isNotBlank(blockCondition)) {
            List<String> conditions = new List<String>{
                    'RecordType.DeveloperName = \'Block\''
            };

            conditions.add(vertic_Utils.templates.compose(blockCondition, referral.getPopulatedFieldsAsMap(), false));

            animalos__Location__c blockLocation = (animalos__Location__c) vertic_Utils.arrays.firstOrNull(
                    Database.query(new fflib_QueryFactory(animalos__Location__c.SObjectType)
                            .setCondition(String.join(conditions, ' AND '))
                            .setLimit(1)
                            .toSOQL()
                    )
            );

            if (blockLocation != null) {
                this.response.put('defaultBlock', blockLocation.Id);
            }

        }

        List<String> inboundRecordTypes = settingDTO.getListAsStrings('inboundRecordTypes');
        Boolean isInboundRecordType = (inboundRecordTypes == null)
                || (inboundRecordTypes != null && !inboundRecordTypes.isEmpty() && inboundRecordTypes.contains(referralRecordTypeDeveloperName));

        this.response.put('isInboundRecordType', isInboundRecordType);

        if (isInboundRecordType) {
            this.response.selectOptions.put('animalosStageOptions', vertic_Utils.picklists.getPicklistValuesAsSelectOptions(
                    animalos__Animal__c.animalos__Stage__c,
                    new Set<String>{
                            'Out'
                    })
            );
        }

        this.initAnimalAdditionalFields(settingDTO.getDTO('additionalFields'), referralRecordTypeDeveloperName);
        this.initAnimalReferralAdditionalFields(settingDTO.getDTO('animalReferralFields'), referralRecordTypeDeveloperName);
    }

    private void initAnimalAdditionalFields(vertic_DTO fieldsSettingDTO, String referralRecordTypeDeveloperName) {
        Map<String, Map<String, Object>> animalFieldsMap = vertic_Utils.sObjects.getFieldsInfo(animalos__Animal__c.SObjectType);
        List<Map<String, Object>> additionalFieldsInfo = new List<Map<String, Object>>();
        List<vertic_DTO> animalAdditionalFields = fieldsSettingDTO.get(referralRecordTypeDeveloperName) == null ?
                fieldsSettingDTO.getDTOs('default') :
                fieldsSettingDTO.getDTOs(referralRecordTypeDeveloperName);

        for (vertic_DTO fieldSettingMap : animalAdditionalFields) {
            if (animalFieldsMap.containsKey(fieldSettingMap.getRequiredString('field'))) {
                this.animalLookupFields.add(fieldSettingMap.getString('field'));
                Map<String, Object> fieldMap = (animalFieldsMap.get(fieldSettingMap.getString('field'))).clone();
                additionalFieldsInfo.add(this.initField(fieldMap, fieldSettingMap.getMap()));
            }
        }

        this.response.put('additionalFields', additionalFieldsInfo);
        this.response.put('animalLookupFields', String.join(new List<String>(this.animalLookupFields), ', '));
    }

    private void initAnimalReferralAdditionalFields(vertic_DTO fieldsSettingDTO, String referralRecordTypeDeveloperName) {
        Map<String, Map<String, Object>> animalReferralFieldsMap = vertic_Utils.sObjects.getFieldsInfo(animalos__Animal_Referral__c.SObjectType);
        List<Map<String, Object>> animalReferralFieldsInfo = new List<Map<String, Object>>();
        List<vertic_DTO> fieldsSetting = fieldsSettingDTO.get(referralRecordTypeDeveloperName) == null ?
                fieldsSettingDTO.getDTOs('default') :
                fieldsSettingDTO.getDTOs(referralRecordTypeDeveloperName);

        for (vertic_DTO fieldSettingMap : fieldsSetting) {
            if (animalReferralFieldsMap.containsKey(fieldSettingMap.getRequiredString('field'))) {
                Map<String, Object> fieldMap = (animalReferralFieldsMap.get(fieldSettingMap.getString('field'))).clone();
                animalReferralFieldsInfo.add(this.initField(fieldMap, fieldSettingMap.getMap()));
            }
        }

        this.response.put('animalReferralFields', animalReferralFieldsInfo);
    }

    private Map<String, Object> initField(Map<String, Object> fieldMap, Map<String, Object> recordTypeFieldSettingMap) {

        for (String attr : recordTypeFieldSettingMap.keySet()) {
            fieldMap.put(attr, recordTypeFieldSettingMap.get(attr));
        }
        fieldMap.put('required', (Boolean) fieldMap.get('required') || (Boolean) recordTypeFieldSettingMap.get('required'));

        if (recordTypeFieldSettingMap.containsKey('defaultValue')) {
            String defaultValueMergeField = String.valueOf(recordTypeFieldSettingMap.get('defaultValue'));

            switch on defaultValueMergeField {
                when '{!NOW}' {
                    fieldMap.put('defaultValue', Datetime.now());
                }
                when '{!TODAY}' {
                    fieldMap.put('defaultValue', Date.today());
                }
            }
        }
        return fieldMap;
    }

    public Boolean hasEnhancedAccess() {
        return [
                SELECT COUNT()
                FROM PermissionSetAssignment
                WHERE AssigneeId = :UserInfo.getUserId()
                AND PermissionSet.Name = 'AnimalOS_Start_Referral_Enhanced_Access'
        ] > 0;
    }
}