force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Animal_Released__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal_Released__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Animal Released</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/aos_Shelter_Email__c.field-meta.xml
<CustomField>
    <fullName>aos_Shelter_Email__c</fullName>
    <label>Shelter Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AnimalReadyForReleaseNotif.cls
global class TDTM_aos_AnimalReadyForReleaseNotif extends animalos.TDTM.Handler implements animalos.TDTM.AfterUpdate {

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        sendReadyForReleaseNotification(records, oldMap);
    }

    private void sendReadyForReleaseNotification(List<SObject> records, Map<Id, SObject> existingRecords) {

        List<animalos__Animal__c> animalsReadyForRelease = new List<animalos__Animal__c>();

        for (animalos__Animal__c animal : (List<animalos__Animal__c>) records) {
            animalos__Animal__c existingAnimal = (animalos__Animal__c) existingRecords.get(animal.Id);
            if (animal.animalos__Current_Site__c != null && animal.aos_Animal_Released__c && vertic_Utils.sObjects.isSomeFieldChanged(
                animal, existingAnimal, new List<SObjectField>{
                    animalos__Animal__c.aos_Animal_Released__c
                }
            )) {
                animalsReadyForRelease.add(animal);
            }
        }

        if (!animalsReadyForRelease.isEmpty()) {

            EmailTemplate animalReadyForReleaseEmailTemplate = (EmailTemplate) vertic_Utils.arrays.firstOrNull([
                SELECT Id, DeveloperName, Name
                FROM EmailTemplate
                WHERE DeveloperName = 'Animal_Released_Notification_1677242995294'
            ]);

            if (animalReadyForReleaseEmailTemplate == null) {
                return;
            }

            Set<Id> shelterIds = vertic_Utils.sObjects.getIdFieldValues(animalsReadyForRelease, animalos__Animal__c.animalos__Current_Site__c);

            Map<Id, animalos__Location__c> siteLocationsById = new Map<Id, animalos__Location__c>([
                SELECT Id, aos_Shelter_Email__c
                FROM animalos__Location__c
                WHERE Id IN :shelterIds
            ]);

            if (UserInfo.getUserId() != null) {
                vertic_AsyncProcess asyncProcess = new vertic_AsyncProcess();

                for (animalos__Animal__c animal : animalsReadyForRelease) {
                    Messaging.SingleEmailMessage emailMessage = Messaging.renderStoredEmailTemplate(
                        animalReadyForReleaseEmailTemplate.Id,
                        UserInfo.getUserId(),
                        animal.Id
                    );

                    animalos__Location__c siteLocation = siteLocationsById.get(animal.animalos__Current_Site__c);

                    if (!String.isBlank(siteLocation.aos_Shelter_Email__c)) {
                        asyncProcess.add(
                            new vertic_SendEmailProc.EmailAsyncProcess(
                                emailMessage.htmlBody,
                                new List<String>{
                                    siteLocation.aos_Shelter_Email__c
                                })
                                .setSaveAsActivity(false)
                                .setOrgWideEmail('events@rspcansw.org.au')
                                .setSubject(emailMessage.getSubject())
                                .toAsyncProcess());
                    }
                }

                asyncProcess.enqueue();
            }
        }
    }
}