force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Adoption_Fee__c.field-meta.xml
<CustomField>
    <fullName>animalos__Adoption_Fee__c</fullName>
    <label>Adoption Fee</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>animalos__Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Gender__c.field-meta.xml
<CustomField>
    <fullName>animalos__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>animalos__Microchip_Number__c</fullName>
    <label>Microchip Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Neutered_Spayed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Neutered_Spayed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Neutered/Spayed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Size__c.field-meta.xml
<CustomField>
    <fullName>animalos__Size__c</fullName>
    <formula>TEXT(animalos__Primary_Breed__r.animalos__Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_About_Me_PetRescue__c.field-meta.xml
<CustomField>
    <fullName>aos_About_Me_PetRescue__c</fullName>
    <label>About Me (PetRescue)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Age_Restriction__c.field-meta.xml
<CustomField>
    <fullName>aos_Age_Restriction__c</fullName>
    <inlineHelpText>How does this animal relate to people of different ages?</inlineHelpText>
    <label>Age Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no known child related issues</fullName>
                <label>All ages</label>
            </value>
            <value>
                <fullName>6 years +</fullName>
            </value>
            <value>
                <fullName>12 years +</fullName>
            </value>
            <value>
                <fullName>15 +</fullName>
            </value>
            <value>
                <fullName>adult household only</fullName>
                <label>Adult household</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Crossbreed__c.field-meta.xml
<CustomField>
    <fullName>aos_Crossbreed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Crossbreed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Home_Requirements__c.field-meta.xml
<CustomField>
    <fullName>aos_Home_Requirements__c</fullName>
    <inlineHelpText>How much company would be best for this dog?</inlineHelpText>
    <label>Home Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Someone home most/all of the time</fullName>
            </value>
            <value>
                <fullName>Someone working average work hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Id__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Id__c</fullName>
    <externalId>true</externalId>
    <label>PetRescue_Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Location__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PetRescue Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Animals (PetRescue Location)</relationshipLabel>
    <relationshipName>aos_Animals_PetRescue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_PetRescue_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Status__c</fullName>
    <label>PetRescue Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
            </value>
            <value>
                <fullName>rehomed</fullName>
            </value>
            <value>
                <fullName>removed</fullName>
            </value>
            <value>
                <fullName>draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Senior_Pet__c.field-meta.xml
<CustomField>
    <fullName>aos_Senior_Pet__c</fullName>
    <formula>IF(IF( NOT( ISBLANK( animalos__Date_of_Birth__c ) ) , IF( DATE( 2000 , MONTH( animalos__Date_of_Birth__c ) , DAY( animalos__Date_of_Birth__c ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ), YEAR (Today()) - YEAR ( animalos__Date_of_Birth__c ), YEAR (Today()) - YEAR ( animalos__Date_of_Birth__c ) -1 ), 0) &gt; 8, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Senior Pet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Size__c.field-meta.xml
<CustomField>
    <fullName>animalos__Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Extra Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/fields/aos_PetRescue_Name__c.field-meta.xml
<CustomField>
    <fullName>aos_PetRescue_Name__c</fullName>
    <label>PetRescue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/aos_AdoptAPet_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>aos_AdoptAPet_Location_Name__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Adoption Website Location Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/aos_Postcode__c.field-meta.xml
<CustomField>
    <fullName>aos_Postcode__c</fullName>
    <label>Postcode</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Details__c.field-meta.xml
<CustomField>
    <fullName>aos_Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Retrying</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
                <isActive>false</isActive>
                <label>Processing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/aos_OneDrive_File__c.object-meta.xml
<CustomObject>
    <label>OneDrive File</label>
    <nameField>
        <label>OneDrive File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OneDrive Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_File_ID__c.field-meta.xml
<CustomField>
    <fullName>aos_File_ID__c</fullName>
    <label>File ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_Postcode__c/aos_Postcode__c.object-meta.xml
<CustomObject>
    <description>Reference list of QLD Postcodes</description>
    <label>Postcode</label>
    <nameField>
        <label>Postcode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Postcode__c/fields/aos_Postcode__c.field-meta.xml
<CustomField>
    <fullName>aos_Postcode__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnimalToPetRescueProc.cls
public without sharing class AnimalToPetRescueProc extends vertic_AbstractProcessor implements vertic_Structs.IAsyncPostProcessing {

    private String recordId;
    private String locationId;
    private animalos__Animal__c animal;
    private animalos__Location__c location;
    private vertic_UnitOfWork uow = new vertic_UnitOfWork(new List<SObjectType>{
            animalos__Animal__c.SObjectType
    });
    private String respBody;
    private Integer responseStatusCode;
    private Set<String> oneDriveFileFields = new Set<String>{
            'Id', 'Is_Primary__c', 'Is_Public__c', 'File_ID__c'
    };

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.initRecord();
        this.sync();

        animalos.TDTM.getTriggerSObjectTypeEvent(animalos__Animal__c.SObjectType).disableAll();
        this.uow.commitWork();

        return this.response;
    }

    private void initRecord() {
        this.locationId = this.request.getRequiredString('locationId');
        this.recordId = this.request.getRequiredString('recordId');
        fflib_QueryFactory queryFactory = new fflib_QueryFactory(animalos__Animal__c.SObjectType);
        queryFactory.selectFields(animalos__Animal__c.getSObjectType().getDescribe().fields.getMap().keySet().clone());
        queryFactory.selectField('animalos__Primary_Breed__r.Name');
        queryFactory.selectField('animalos__Primary_Breed__r.PetRescue_Name__c');
        queryFactory.selectField('animalos__Primary_Breed__r.animalos__Size__c');
        queryFactory.setCondition('Id = :recordId');

        fflib_QueryFactory subQueryFactory = queryFactory.subselectQuery(aos_OneDrive_File__c.SObjectType);
        subQueryFactory.selectFields(this.oneDriveFileFields);
        subQueryFactory.setCondition(
                String.join(
                        new List<String>{
                                '(Is_Primary__c = TRUE OR Is_Public__c = TRUE)',
                                'Folder_Name__c LIKE \'%photos%\'',
                                'Is_Deleted__c = FALSE'
                        },
                        ' AND '
                )
        );
        subQueryFactory.setOrdering(aos_OneDrive_File__c.aos_Is_Primary__c, fflib_QueryFactory.SortOrder.DESCENDING);

        this.animal = (animalos__Animal__c) vertic_Utils.arrays.firstOrException(Database.query(queryFactory.toSOQL()));
        this.location = (animalos__Location__c) vertic_Utils.arrays.firstOrException([
                SELECT Id, Name, aos_Postcode__c, aos_AdoptAPet_Location_Name__c
                FROM animalos__Location__c
                WHERE Id = :this.locationId
        ]);
    }

    private void sync() {
        Map<String, Object> animalData = new Map<String, Object>{
                'shelter_code' => this.location.aos_AdoptAPet_Location_Name__c,
                'name' => this.animal.animalos__Animal_Name__c,
                'adoption_fee' => vertic_Utils.objects.defaultIfNull('$' + String.valueOf(animal.animalos__Adoption_Fee__c), 'N/A'),
                'mix' => this.animal.aos_Crossbreed__c,
                'date_of_birth' => String.valueOf(this.animal.animalos__Date_of_Birth__c),
                'desexed' => this.animal.animalos__Neutered_Spayed__c,
                'microchip_number' => this.animal.animalos__Microchip_Number__c,
                'personality' => String.isNotBlank(this.animal.aos_About_Me_PetRescue__c) ? this.animal.aos_About_Me_PetRescue__c.replace('<p>', '--n ').stripHtmlTags().replaceAll('--n ', '\n\n') : 'N/A',
                'location_postcode' => this.location.aos_Postcode__c,
                'contact_preferred_method' => 'phone',
                'breed_names' => new List<String>{
                        String.isNotBlank(this.animal.animalos__Primary_Breed__r.aos_PetRescue_Name__c) ? this.animal.animalos__Primary_Breed__r.aos_PetRescue_Name__c : this.animal.animalos__Primary_Breed__r.Name
                },
                'wormed' => true,
                'heart_worm_treated' => true,
                'vaccinated' => true
        };

        String status = this.request.getString('status');
        animalData.put('status', 'draft');

        if ('Male'.equals(this.animal.animalos__Gender__c)) {
            animalData.put('gender', 'male');
        } else if ('Female'.equals(this.animal.animalos__Gender__c)) {
            animalData.put('gender', 'female');
        }

        if ('Kitten'.equals(this.animal.animalos__Type__c)) {
            animalData.put('species_name', 'Cat');
        } else if ('Puppy'.equals(this.animal.animalos__Type__c)) {
            animalData.put('species_name', 'Dog');
        } else {
            animalData.put('species_name', this.animal.animalos__Type__c);
        }

        if ('6 years +'.equals(this.animal.aos_Age_Restriction__c)) {
            animalData.put('incompatible_with_kids_under_5', true);
            animalData.put('incompatible_with_kids_6_to_12', false);
        } else if ('12 years +'.equals(this.animal.aos_Age_Restriction__c)
                || '15 +'.equals(this.animal.aos_Age_Restriction__c)
                || 'Adult household'.equals(this.animal.aos_Age_Restriction__c)
        ) {
            animalData.put('incompatible_with_kids_under_5', true);
            animalData.put('incompatible_with_kids_6_to_12', true);
        } else if ('All ages'.equals(this.animal.aos_Age_Restriction__c)) {
            animalData.put('incompatible_with_kids_under_5', false);
            animalData.put('incompatible_with_kids_6_to_12', false);
        }

        if ('Someone home most/all of the time'.equals(this.animal.aos_Home_Requirements__c)) {
            animalData.put('needs_constant_care', true);
        }

        if ('Dog'.equals(this.animal.animalos__Type__c) || 'Puppy'.equals(this.animal.animalos__Type__c)) {
            animalData.put('senior', this.animal.aos_Senior_Pet__c);

            if (this.animal.animalos__Primary_Breed__c != null) {
                animalData.put('size', this.animal.animalos__Primary_Breed__r.animalos__Size__c.toLowerCase());

                if ('Extra Large'.equals(this.animal.animalos__Primary_Breed__r.animalos__Size__c)) {
                    animalData.put('size', 'large');
                }
            }
        }

        if ('Cat'.equals(animal.animalos__Type__c) || 'Kitten'.equals(animal.animalos__Type__c)) {
            animalData.put('intake_origin', 'shelter_transfer');
            animalData.put('coat', 'medium_coat');
        }

        if (!this.animal.aos_OneDrive_Files__r.isEmpty()) {
            List<aos_OneDrive_File__c> oneDriveFiles = animal.aos_OneDrive_Files__r;
            List<String> photoUrls = new List<String>();

            Map<String, Object> drivesMap = OneDriveUtils.getDrives();
            String driveId = (String) drivesMap.get('Adoption');

            for (aos_OneDrive_File__c oneDriveFile : oneDriveFiles) {
                String publicUrl = OneDriveUtils.getFileThumbnail(driveId, oneDriveFile.aos_File_ID__c);
                if (oneDriveFile.aos_Is_Primary__c) {
                    animalData.put('featured_photo_url', publicUrl);
                }
                photoUrls.add(publicUrl);
            }

            animalData.put('photo_urls', photoUrls);
        }

        removeNullValuesFromMap(animalData);

        HttpResponse response;
        if (String.isNotBlank(this.animal.aos_PetRescue_Id__c)) {
            if ('rehomed'.equals(status) || 'removed'.equals(status)) {
                response = PetRescue.listings.doUpdate(this.animal.aos_PetRescue_Id__c, new Map<String, Object>{
                        'status' => status
                }, this.locationId);
            } else {
                response = PetRescue.listings.doUpdate(this.animal.aos_PetRescue_Id__c, animalData, this.locationId);
            }
        } else {
            response = PetRescue.listings.create(animalData, this.locationId);
        }

        try {
            this.respBody = JSON.serializePretty(JSON.deserializeUntyped(response.getBody()));
            this.responseStatusCode = response.getStatusCode();

            if (response.getStatusCode() != 200) {
                return;
            }

            vertic_DTO dto = new vertic_DTO(response.getBody());

            animalos__Animal__c animal = new animalos__Animal__c(Id = this.animal.Id);

            if (animal.aos_PetRescue_Location__c == null) {
                animal.aos_PetRescue_Location__c = this.locationId;
            }

            if (String.isBlank(this.animal.aos_PetRescue_Id__c)) {
                animal.aos_PetRescue_Id__c = dto.getString('id');
            }

            animal.aos_PetRescue_Status__c = dto.getString('status');

            this.uow.registerUpsert(animal);
        } catch (Exception e) {
            this.respBody = response.getBody();
        }
    }

    public aos_Async_Process__c postProcess(aos_Async_Process__c asyncProcess) {
        asyncProcess.aos_Details__c = this.respBody;
        System.debug(this.responseStatusCode);
        if (this.responseStatusCode != 200) {
            asyncProcess.aos_Status__c = 'Failed';
        }
        return asyncProcess;
    }

    private static void removeNullValuesFromMap(Map<String, Object> data) {
        if (data == null) return;

        for (String key : data.keySet()) {
            if (data.get(key) == null) {
                data.remove(key);
            }
        }
    }
}