force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Action__c/animalos__Animal_Action__c.object-meta.xml
<CustomObject>
    <label>Animal Action</label>
    <nameField>
        <displayFormat>AA{00000}</displayFormat>
        <label>Animal Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Action_Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Action_Status__c</fullName>
    <label>Action Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Not Given</fullName>
            </value>
            <value>
                <fullName>Given - See Comments</fullName>
            </value>
            <value>
                <fullName>Given</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Actions</relationshipLabel>
    <relationshipName>Animal_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Date_Time_of_Action__c.field-meta.xml
<CustomField>
    <fullName>animalos__Date_Time_of_Action__c</fullName>
    <label>Date/Time of Action</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Animal Actions</relationshipLabel>
    <relationshipName>Animal_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Vet_Consult__c/animalos__Vet_Consult__c.object-meta.xml
<CustomObject>
    <label>Vet Consult</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Vet Consult ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vet Consults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Vet_Consult__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Vet Consults</relationshipLabel>
    <relationshipName>Vet_Consults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateAnimalActionsQAMetaProc.cls
public class CreateAnimalActionsQAMetaProc extends vertic_MetadataProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                animalos__Animal_Action__c.animalos__Action_Status__c
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        this.initRecords();
        this.initRecordTypeOptions();
    }

    private void initRecords() {
        String recordId = this.request.getRequiredString('recordId');

        animalos__Animal__c animal = (animalos__Animal__c) vertic_Utils.arrays.firstOrException([
                SELECT Id
                FROM animalos__Animal__c
                WHERE Id IN (
                        SELECT animalos__Animal__c
                        FROM animalos__Vet_Consult__c
                        WHERE Id = :recordId
                )
        ]);

        this.response.put('animalId', animal.Id);

        this.response.getMapper().mapFromListSObjects('animalActions', new List<animalos__Animal_Action__c>{
                new animalos__Animal_Action__c(
                        animalos__Animal__c = animal.Id,
                        animalos__Action_Status__c = 'Scheduled',
                        animalos__Date_Time_of_Action__c = Datetime.now(),
                        animalos__Vet_Consult__c = recordId
                )
        });
    }

    private void initRecordTypeOptions() {
        List<vertic_Structs.SelectOption> recordTypeOptions = new List<vertic_Structs.SelectOption>();

        for (RecordTypeInfo recordTypeInfo : animalos__Animal_Action__c.SObjectType.getDescribe().recordTypeInfos) {
            if (!'Master'.equals(recordTypeInfo.getDeveloperName()) && recordTypeInfo.isActive() && recordTypeInfo.isAvailable()) {
                recordTypeOptions.add(new vertic_Structs.SelectOption(recordTypeInfo.getRecordTypeId(), recordTypeInfo.getName()));
            }
        }

        this.response.addSelectOptions('recordTypeOptions', recordTypeOptions);
    }

}