force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Animal_is_Ready_for_Release__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal_is_Ready_for_Release__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Animal is Ready for Release</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Animal_Released__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal_Released__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Animal Released</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Animal_Released_By__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal_Released_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Released By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Released_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Declared_Ready_For_Release__c.field-meta.xml
<CustomField>
    <fullName>aos_Declared_Ready_For_Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Declared Ready For Release</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Declared_Animals_Ready_For_Release</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_AnimalReleasedFields.cls
global class TDTM_aos_AnimalReleasedFields extends animalos.TDTM.Handler implements animalos.TDTM.BeforeUpdate {

    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        handleAnimalReleasedFieldsChange(records, oldMap);
    }

    private void handleAnimalReleasedFieldsChange(List<SObject> records, Map<Id, SObject> existingRecords) {
        for (animalos__Animal__c animal : (List<animalos__Animal__c>) records) {
            animalos__Animal__c existingAnimal = (animalos__Animal__c) existingRecords.get(animal.Id);
            if (animal.aos_Animal_Released__c && aos_Utils.sObjects.isSomeFieldChanged(
                animal, existingAnimal, new List<SObjectField>{
                    animalos__Animal__c.aos_Animal_Released__c
                }
            )) {
                animal.aos_Animal_Released_By__c = UserInfo.getUserId();
            }
            if (animal.aos_Animal_is_Ready_for_Release__c && aos_Utils.sObjects.isSomeFieldChanged(
                animal, existingAnimal, new List<SObjectField>{
                    animalos__Animal__c.aos_Animal_is_Ready_for_Release__c
                }
            )) {
                animal.aos_Declared_Ready_For_Release__c = UserInfo.getUserId();
            }
        }
    }
}