force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>animalos__Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/aos_Scheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>aos_Scheduled_Date_Time__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <formula>animalos__Referral__r.animalos__Scheduled_Date_Time__c</formula>
    <label>Scheduled Date/ Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/aos_Type__c.field-meta.xml
<CustomField>
    <fullName>aos_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/aos_UpdateAnimalReferralTypeBatch.cls
global class aos_UpdateAnimalReferralTypeBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, animalos__Animal__r.animalos__Type__c, animalos__Animal__r.animalos__Date_of_Birth__c, ' +
                'aos_Scheduled_Date_Time__c ' +
                'FROM animalos__Animal_Referral__c ' +
                'WHERE animalos__Animal__c != NULL AND animalos__Animal__r.animalos__Type__c != NULL AND aos_Type__c = NULL'
        );
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        for (animalos__Animal_Referral__c animalReferral : (List<animalos__Animal_Referral__c>) scope) {
            animalos__Animal__c animal = animalReferral.animalos__Animal__r;

            animalReferral.aos_Type__c = animal.animalos__Type__c;

            Boolean isDogOrCat = 'Dog'.equals(animal.animalos__Type__c) || 'Cat'.equals(animal.animalos__Type__c);
            Boolean enteredLessThanInSixMonths = animal.animalos__Date_of_Birth__c != null && animalReferral.aos_Scheduled_Date_Time__c != null
                    && animal.animalos__Date_of_Birth__c.monthsBetween(animalReferral.aos_Scheduled_Date_Time__c.date()) < 6;

            if (isDogOrCat && enteredLessThanInSixMonths) {
                animalReferral.aos_Type__c = 'Dog'.equals(animal.animalos__Type__c) ? 'Puppy' : 'Kitten';
            }
        }

        update scope;
    }

    global void finish(Database.BatchableContext BC) {
    }

}