force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Days_in_Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Days_in_Status__c</fullName>
    <formula>TODAY() - animalos__Status_Changed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/aos_Days_in_Care__c.field-meta.xml
<CustomField>
    <fullName>aos_Days_in_Care__c</fullName>
    <label>Days in Care</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/animalos__Log__c/animalos__Log__c.object-meta.xml
<CustomObject>
    <label>AnimalOS Log</label>
    <nameField>
        <displayFormat>AL{00000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AnimalOS Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Log_Details__c.field-meta.xml
<CustomField>
    <fullName>animalos__Log_Details__c</fullName>
    <label>Log Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Process__c.field-meta.xml
<CustomField>
    <fullName>animalos__Process__c</fullName>
    <label>Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Log__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Home Inspection</fullName>
            </value>
            <value>
                <fullName>Veterinary Check</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Trial Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Adopted Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Input</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/animalos__Status_Tracking__c.object-meta.xml
<CustomObject>
    <label>Status Tracking</label>
    <nameField>
        <displayFormat>ST{00000}</displayFormat>
        <label>Status Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Status Tracking</relationshipLabel>
    <relationshipName>Status_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Animal_Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Referral</label>
    <referenceTo>animalos__Animal_Referral__c</referenceTo>
    <relationshipLabel>Status Tracking</relationshipLabel>
    <relationshipName>Status_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Days_in_Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Days_in_Status__c</fullName>
    <formula>IF( ISBLANK( animalos__End_Date_Time__c ), NOW() - animalos__Start_Date_Time__c, animalos__End_Date_Time__c - animalos__Start_Date_Time__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Status</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Status Tracking</relationshipLabel>
    <relationshipName>Status_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/aos_CalcRollupsAnimalReferralStatusTrack.cls
global class aos_CalcRollupsAnimalReferralStatusTrack extends animalos.vertic_SequentialScheduledBatch {

    public override Database.QueryLocator getLocator() {
        List<String> conditions = new List<String>();

        if (String.isNotBlank(this.sequentialBatchSetting.animalos__Conditions__c)) {
            conditions.add('(' + sequentialBatchSetting.animalos__Conditions__c + ')');
        }

        return Database.getQueryLocator(
                new aos_QueryFactory(((SObject) Type.forName(this.sequentialBatchSetting.animalos__SObject_Type__c).newInstance()).getSObjectType())
                        .selectFields(
                                animalos__Animal_Referral__c.SObjectType.getDescribe().fields.getMap().keySet()
                        )
                        .setCondition(String.join(conditions, ' AND ')).toSOQL()
        );
    }

    global override void process(List<SObject> records) {
        try {
            Set<Id> animalIds = aos_Utils.sObjects.getIdFieldValues(records, 'animalos__Animal__c');
            Set<Id> referralIds = aos_Utils.sObjects.getIdFieldValues(records, 'animalos__Referral__c');
            List<animalos__Animal_Referral__c> animalReferralsToUpdate = new List<animalos__Animal_Referral__c>();

            List<animalos__Status_Tracking__c> statusTrackingRecords = [
                    SELECT Id, animalos__Days_in_Status__c, animalos__Referral__c, animalos__Animal__c
                    FROM animalos__Status_Tracking__c
                    WHERE animalos__Animal__c IN :animalIds AND animalos__Referral__c IN :referralIds
                    AND animalos__Animal__c != NULL AND animalos__Referral__c != NULL
                    AND animalos__Stage__c != 'Out'
                    AND RecordType.DeveloperName = 'Generic'
            ];

            Map<String, List<animalos__Status_Tracking__c>> statusTrackingRecordsByAnimalReferralIds = new Map<String, List<animalos__Status_Tracking__c>>();

            for (animalos__Status_Tracking__c statusTrackingRecord : statusTrackingRecords) {
                if (!statusTrackingRecordsByAnimalReferralIds.containsKey('' + statusTrackingRecord.animalos__Referral__c + statusTrackingRecord.animalos__Animal__c)) {
                    statusTrackingRecordsByAnimalReferralIds.put('' + statusTrackingRecord.animalos__Referral__c + statusTrackingRecord.animalos__Animal__c, new List<animalos__Status_Tracking__c>());
                }
                statusTrackingRecordsByAnimalReferralIds.get('' + statusTrackingRecord.animalos__Referral__c + statusTrackingRecord.animalos__Animal__c).add(statusTrackingRecord);
            }

            for (animalos__Animal_Referral__c animalReferral : (List<animalos__Animal_Referral__c>) records) {
                List<animalos__Status_Tracking__c> relatedStatusTrackingRecords = statusTrackingRecordsByAnimalReferralIds.get('' + animalReferral.animalos__Referral__c + animalReferral
                        .animalos__Animal__c);

                if (relatedStatusTrackingRecords == null || relatedStatusTrackingRecords.isEmpty()) {
                    continue;
                }

                Decimal daysInStatus = 0;
                for (animalos__Status_Tracking__c statusTrackingRecord : relatedStatusTrackingRecords) {
                    daysInStatus += aos_Utils.objects.defaultIfNull(statusTrackingRecord.animalos__Days_in_Status__c, 0);
                }

                animalReferral.aos_Days_in_Care__c = daysInStatus;
                animalReferralsToUpdate.add(animalReferral);
            }

            if(!animalReferralsToUpdate.isEmpty()) {
                update animalReferralsToUpdate;
            }
        } catch(Exception ex) {
            insert new animalos__Log__c(
                    animalos__Type__c = 'Error',
                    animalos__Log_Details__c = ex.getMessage() + '\n' + ex.getStackTraceString(),
                    animalos__Process__c = 'CalcRollupsAnimalReferralStatusTracking'
            );
        }
    }
}