force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Age_Group__c.field-meta.xml
<CustomField>
    <fullName>animalos__Age_Group__c</fullName>
    <label>Age Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Baby 0 - 8 wks</fullName>
            </value>
            <value>
                <fullName>Juvenile 8 wks - 6 mths</fullName>
            </value>
            <value>
                <fullName>Young Adult 6 mths - 1 yr</fullName>
            </value>
            <value>
                <fullName>Adult 1 yr - 8 yrs</fullName>
            </value>
            <value>
                <fullName>Senior 8 yrs+</fullName>
            </value>
            <value>
                <fullName>Egg</fullName>
            </value>
            <value>
                <fullName>Neonate</fullName>
            </value>
            <value>
                <fullName>Juvenile</fullName>
            </value>
            <value>
                <fullName>Sub-Adult</fullName>
            </value>
            <value>
                <fullName>Young Adult</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Hatchling</fullName>
            </value>
            <value>
                <fullName>Nestling</fullName>
            </value>
            <value>
                <fullName>Chick</fullName>
            </value>
            <value>
                <fullName>Fledgling</fullName>
            </value>
            <value>
                <fullName>Immature</fullName>
            </value>
            <value>
                <fullName>Mature/adult</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Class__c.field-meta.xml
<CustomField>
    <fullName>animalos__Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Exotic</fullName>
            </value>
            <value>
                <fullName>Livestock</fullName>
            </value>
            <value>
                <fullName>Small Animal</fullName>
            </value>
            <value>
                <fullName>Wildlife</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>animalos__Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adopted – Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted - Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Adopted – Offsite</fullName>
            </value>
            <value>
                <fullName>Adoption Pending/Hold on Property Check</fullName>
            </value>
            <value>
                <fullName>Available For Adoption</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – In Foster</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – No Web Presence</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Offsite</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Waiting Space</fullName>
            </value>
            <value>
                <fullName>Awaiting Behavioural Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Evaluation</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Retest</fullName>
            </value>
            <value>
                <fullName>Awaiting Desex</fullName>
            </value>
            <value>
                <fullName>Awaiting Euthanasia</fullName>
            </value>
            <value>
                <fullName>Awaiting Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Rescue</fullName>
            </value>
            <value>
                <fullName>Awaiting Spay/Neuter – In Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Surgery – Not Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Awaiting Transfer</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Vet Exam/Health Check</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Offsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Off Site</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Onsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal On Site</fullName>
            </value>
            <value>
                <fullName>Court Hold</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Is_New__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_New__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is New</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/animalos__Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS{00000}</displayFormat>
        <label>Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <formula>animalos__Animal__r.animalos__Animal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Assessment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Assessment_Date_Time__c</fullName>
    <inlineHelpText>Date and Time of assessment</inlineHelpText>
    <label>Assessment Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Assessment__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Class__c.field-meta.xml
<CustomField>
    <fullName>animalos__Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Exotic</fullName>
            </value>
            <value>
                <fullName>Livestock</fullName>
            </value>
            <value>
                <fullName>Small Animal</fullName>
            </value>
            <value>
                <fullName>Wildlife</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_Assessment_Score__c/aos_Assessment_Score__c.object-meta.xml
<CustomObject>
    <label>Assessment Score</label>
    <nameField>
        <label>Assessment Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Assessment_Score__c/fields/aos_Assessment__c.field-meta.xml
<CustomField>
    <fullName>aos_Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>animalos__Assessment__c</referenceTo>
    <relationshipLabel>Assessment Scores</relationshipLabel>
    <relationshipName>Assessment_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_Assessment_Score__c/fields/aos_Score__c.field-meta.xml
<CustomField>
    <fullName>aos_Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/aos_Assessment_Score__c/fields/aos_Score_Category__c.field-meta.xml
<CustomField>
    <fullName>aos_Score_Category__c</fullName>
    <label>Score Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Behaviour in kennel or yard</fullName>
            </value>
            <value>
                <fullName>Eating</fullName>
            </value>
            <value>
                <fullName>Kennel Overnight</fullName>
            </value>
            <value>
                <fullName>Leaving kennel</fullName>
            </value>
            <value>
                <fullName>Meeting a person out of the kennel</fullName>
            </value>
            <value>
                <fullName>Placing lead/harness on</fullName>
            </value>
            <value>
                <fullName>Response to interacting with person</fullName>
            </value>
            <value>
                <fullName>Resting during day</fullName>
            </value>
            <value>
                <fullName>Seeing another dog out of kennel</fullName>
            </value>
            <value>
                <fullName>Walking on lead</fullName>
            </value>
            <value>
                <fullName>When first given a toy</fullName>
            </value>
            <value>
                <fullName>When person at front of kennel</fullName>
            </value>
            <value>
                <fullName>When person entering kennel or yard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalcRollupsAssessmentTotalScoreTest.cls
@IsTest
private class CalcRollupsAssessmentTotalScoreTest {

    @IsTest
    static void calculatesTotalScoreFromAssessmentScores() {
        // Minimal animal to satisfy potential lookups on Assessment
        animalos__Breed__c breed = new animalos__Breed__c(
                animalos__Type__c = 'Dog',
                Name = 'Test Breed'
        );
        insert breed;

        animalos__Animal__c animal = new animalos__Animal__c(
                animalos__Animal_Name__c = 'Test Animal',
                animalos__Class__c = 'Domestic',
                animalos__Type__c = 'Dog',
                animalos__Age_Group__c = 'Young Adult 6 mths - 1 yr',
                animalos__Date_of_Birth__c = Date.today(),
                animalos__Stage__c = 'Pre-Intake',
                animalos__Status__c = 'Information',
                aos_Is_New__c = false,
                animalos__Primary_Breed__c = breed.Id
        );
        insert animal;

        // Create an Assessment record. Keep fields minimal and avoid trigger side-effects by disabling domain events on update in batch.
        animalos__Assessment__c assessment = new animalos__Assessment__c(
                animalos__Animal__c = animal.Id,
                animalos__Assessment_Date_Time__c = Datetime.now()
        );
        insert assessment;

        // Create related Assessment Score records that the rollup will sum
        List<aos_Assessment_Score__c> scores = new List<aos_Assessment_Score__c>{
                new aos_Assessment_Score__c(
                        aos_Assessment__c = assessment.Id,
                        aos_Score__c = 3,
                        Name = 'Cat 1',
                        aos_Score_Category__c = 'Cat 1'
                ),
                new aos_Assessment_Score__c(
                        aos_Assessment__c = assessment.Id,
                        aos_Score__c = 7,
                        Name = 'Cat 2',
                        aos_Score_Category__c = 'Cat 2'
                )
        };
        insert scores;

        // Execute the batch directly calling process with our assessment in scope
        Test.startTest();
        new CalcRollupsAssessmentTotalScore().process(new List<SObject>{ assessment });
        Test.stopTest();

        // Verify total score is the sum of child scores (3 + 7 = 10)
        assessment = [SELECT Id, animalos__Total_Score__c FROM animalos__Assessment__c WHERE Id = :assessment.Id];
        System.assertEquals(10, assessment.animalos__Total_Score__c);
    }

    @IsTest
    static void handlesNoScoresAsZero() {
        animalos__Breed__c breed = new animalos__Breed__c(
                animalos__Type__c = 'Dog',
                Name = 'Test Breed'
        );
        insert breed;

        animalos__Animal__c animal = new animalos__Animal__c(
                animalos__Animal_Name__c = 'Test Animal',
                animalos__Class__c = 'Domestic',
                animalos__Type__c = 'Dog',
                animalos__Age_Group__c = 'Young Adult 6 mths - 1 yr',
                animalos__Date_of_Birth__c = Date.today(),
                animalos__Stage__c = 'Pre-Intake',
                animalos__Status__c = 'Information',
                aos_Is_New__c = false,
                animalos__Primary_Breed__c = breed.Id
        );
        insert animal;

        animalos__Assessment__c assessment = new animalos__Assessment__c(
                animalos__Animal__c = animal.Id,
                animalos__Assessment_Date_Time__c = Datetime.now()
        );
        insert assessment;

        Test.startTest();
        new CalcRollupsAssessmentTotalScore().process(new List<SObject>{ assessment });
        Test.stopTest();

        assessment = [SELECT Id, animalos__Total_Score__c FROM animalos__Assessment__c WHERE Id = :assessment.Id];
        System.assertEquals(0, assessment.animalos__Total_Score__c);
    }
}