force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Incoming_Date__c.field-meta.xml
<CustomField>
    <fullName>animalos__Incoming_Date__c</fullName>
    <label>Incoming Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adopted – Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted - Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Adopted – Offsite</fullName>
            </value>
            <value>
                <fullName>Adoption Pending/Hold on Property Check</fullName>
            </value>
            <value>
                <fullName>Available For Adoption</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – In Foster</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – No Web Presence</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Offsite</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Waiting Space</fullName>
            </value>
            <value>
                <fullName>Awaiting Behavioural Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Evaluation</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Retest</fullName>
            </value>
            <value>
                <fullName>Awaiting Desex</fullName>
            </value>
            <value>
                <fullName>Awaiting Euthanasia</fullName>
            </value>
            <value>
                <fullName>Awaiting Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Rescue</fullName>
            </value>
            <value>
                <fullName>Awaiting Spay/Neuter – In Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Surgery – Not Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Awaiting Transfer</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Vet Exam/Health Check</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Offsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Off Site</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Onsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal On Site</fullName>
            </value>
            <value>
                <fullName>Court Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foster Locations</relationshipLabel>
    <relationshipName>Foster_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/animalos__Movement__c.object-meta.xml
<CustomObject>
    <label>Movement</label>
    <nameField>
        <displayFormat>M{00000}</displayFormat>
        <label>Movement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Current__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Location__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Movements</relationshipLabel>
    <relationshipName>Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Movement__c/fields/animalos__Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Start_Date_Time__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Entry_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Entry_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entry Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>animalos__Location__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>animalos__Location__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Offsite</value>
        </filterItems>
        <filterItems>
            <field>animalos__Location__c.animalos__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Outbound_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Outbound_Type__c</fullName>
    <label>Outbound Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agency Outgoing</fullName>
            </value>
            <value>
                <fullName>Council</fullName>
            </value>
            <value>
                <fullName>Emergency Boarding Returned to Owner</fullName>
            </value>
            <value>
                <fullName>Reclaimed</fullName>
            </value>
            <value>
                <fullName>Returned Protective Custody Animal</fullName>
            </value>
            <value>
                <fullName>Returned Surrender</fullName>
            </value>
            <value>
                <fullName>Returned to Habitat</fullName>
            </value>
            <value>
                <fullName>Transfer Out to Council</fullName>
            </value>
            <value>
                <fullName>Transfer Out - To Rescue</fullName>
            </value>
            <value>
                <fullName>Transfer Out - Wildlife Carer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Referral_Organisation__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals (Referral Organisation)</relationshipLabel>
    <relationshipName>Referrals_Referral_Organisation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Home Inspection</fullName>
            </value>
            <value>
                <fullName>Veterinary Check</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Trial Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Adopted Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Input</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/aos_WildlifeAnimalIntakeSubmitProc.cls
public with sharing class aos_WildlifeAnimalIntakeSubmitProc extends vertic_AbstractProcessor implements vertic_Structs.IRollbackable {

    private animalos__Referral__c referral = new animalos__Referral__c();
    private Boolean isInboundRecordType;

    private vertic_UnitOfWork uow = new vertic_UnitOfWork(new List<SObjectType>{
            animalos__Referral__c.SObjectType,
            animalos__Animal__c.SObjectType,
            animalos__Animal_Referral__c.SObjectType,
            animalos__Movement__c.SObjectType
    });

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {
        this.isInboundRecordType = this.request.has('isInboundRecordType') && this.request.getBoolean('isInboundRecordType');

        this.mapReferral();

        if (this.isInboundRecordType) {
            this.mapAnimalsAndMovements();
        } else {
            this.mapAnimals();
        }

        this.uow.commitWork();
        this.response.put('referralId', this.referral.Id);
    }

    private void mapReferral() {
        this.request.getMapper().mapToSObject('referral', this.referral);

        Set<String> referralNameParts = new Set<String>();

        if (this.referral.animalos__Contact__c != null) {
            Contact contactVar = (Contact) vertic_Utils.arrays.firstOrNull([
                    SELECT Id, Name
                    FROM Contact
                    WHERE Id = :this.referral.animalos__Contact__c
                    WITH SECURITY_ENFORCED
            ]);

            referralNameParts.add(contactVar?.Name);
        }

        if (this.referral.animalos__Referral_Organisation__c != null) {
            Account accountVar = (Account) vertic_Utils.arrays.firstOrNull([
                    SELECT Id, Name
                    FROM Account
                    WHERE Id = :this.referral.animalos__Referral_Organisation__c
                    WITH SECURITY_ENFORCED
            ]);

            referralNameParts.add(accountVar?.Name);
        }

        if (this.referral.animalos__Entry_Site__c != null) {
            animalos__Location__c locationVar = (animalos__Location__c) vertic_Utils.arrays.firstOrNull([
                    SELECT Id, Name
                    FROM animalos__Location__c
                    WHERE Id = :this.referral.animalos__Entry_Site__c
                    WITH SECURITY_ENFORCED
            ]);

            referralNameParts.add(locationVar?.Name);
        }

        referralNameParts.add(vertic_Utils.sObjects.recordTypeNameById(animalos__Referral__c.SObjectType, this.referral.RecordTypeId));
        String referralName = String.join(new List<String>(referralNameParts), ' ');
        this.referral.Name = referralName.length() > 80 ? referralName.left(77) + '...' : referralName;

        this.uow.registerNew(this.referral);
    }

    private void mapAnimals() {
        List<animalos__Animal__c> animals = this.request.getMapper().mapToListSObjects('animals', animalos__Animal__c.SObjectType);
        List<vertic_DTO> animalsDTOs = this.request.getDTOs('animals');
        String outboundAnimalRecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Referral__c.SObjectType, 'Outbound_Animal');
        Boolean isReferralRecordTypeEqualsOutboundAnimal = outboundAnimalRecordTypeId.equals(this.referral.RecordTypeId);

        for (vertic_DTO animalDTO : animalsDTOs) {
            animalos__Animal__c animal = new animalos__Animal__c();
            animalDTO.getMapper().mapToSObject(animal);
            if (animal.Id == null || (animal.Id != null && this.isInboundRecordType)) {
                animal.animalos__Incoming_Date__c = Datetime.now();
            }

            if (isReferralRecordTypeEqualsOutboundAnimal) {
                animal.animalos__Stage__c = 'Out';
                animal.animalos__Status__c = this.referral.animalos__Outbound_Type__c;
            }

            this.uow.registerUpsert(animal);

            animalos__Animal_Referral__c animalReferral = new animalos__Animal_Referral__c();
            if(animalDTO.has('animalReferral')) {
                animalDTO.getMapper().mapToSObject('animalReferral', animalReferral);
            }

            this.uow.registerNew(animalReferral, animalos__Animal_Referral__c.animalos__Animal__c, animal);
            this.uow.registerRelationship(animalReferral, animalos__Animal_Referral__c.animalos__Referral__c, this.referral);
        }

        if (isReferralRecordTypeEqualsOutboundAnimal) {
            List<animalos__Movement__c> movements = [
                    SELECT Id
                    FROM animalos__Movement__c
                    WHERE animalos__Animal__c IN :animals
                    AND animalos__Current__c = TRUE
                    WITH SECURITY_ENFORCED
            ];

            for (animalos__Movement__c movement : movements) {
                movement.animalos__Current__c = false;
            }

            if (!movements.isEmpty()) {
                update movements;
            }
        }
    }

    private void mapAnimalsAndMovements() {
        List<vertic_DTO> movementsDTOs = this.request.getDTOs('movements');
        List<animalos__Animal__c> animals = new List<animalos__Animal__c>();

        for (vertic_DTO movementDTO : movementsDTOs) {
            animalos__Animal__c animal = new animalos__Animal__c();
            movementDTO.getMapper().mapToSObject('animalos__Animal__r', animal);

            if (animal.Id != null) {
                animals.add(animal);
            }

            if (animal.Id == null || (animal.Id != null && this.isInboundRecordType)) {
                animal.animalos__Incoming_Date__c = Datetime.now();
            }

            this.uow.registerUpsert(animal);
            this.uow.registerRelationship(animal, animalos__Animal__c.animalos__Current_Referral__c, this.referral);

            animalos__Animal_Referral__c animalReferral = new animalos__Animal_Referral__c();
            if(movementDTO.has('animalos__Animal__r.animalReferral')) {
                movementDTO.getMapper().mapToSObject('animalos__Animal__r.animalReferral', animalReferral);
            }
            this.uow.registerNew(animalReferral, animalos__Animal_Referral__c.animalos__Animal__c, animal);
            this.uow.registerRelationship(animalReferral, animalos__Animal_Referral__c.animalos__Referral__c, this.referral);

            if (!'Pre-Intake'.equals(animal.animalos__Stage__c)) {
                animalos__Movement__c movement = new animalos__Movement__c();
                movementDTO.getMapper().mapToSObject(movement);
                movement.animalos__Start_Date_Time__c = Datetime.now();

                this.uow.registerNew(movement, animalos__Movement__c.animalos__Animal__c, animal);
            }
        }

        List<animalos__Movement__c> movements = [
                SELECT Id
                FROM animalos__Movement__c
                WHERE animalos__Animal__c IN :animals
                AND animalos__Current__c = TRUE
                WITH SECURITY_ENFORCED
        ];

        for (animalos__Movement__c movement : movements) {
            movement.animalos__Current__c = false;
        }

        if (!movements.isEmpty()) {
            update movements;
        }
    }

}