force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Calculated_Age__c.field-meta.xml
<CustomField>
    <fullName>animalos__Calculated_Age__c</fullName>
    <formula>IF(
  NOT(ISBLANK(animalos__Deceased_Date__c)),
  IF(
    NOT(ISBLANK(animalos__Date_of_Birth__c)),
    TEXT(FLOOR((DATEVALUE(animalos__Deceased_Date__c) - animalos__Date_of_Birth__c) / 365.25)) &amp; &apos; Years &apos; &amp;
    TEXT(FLOOR(MOD((DATEVALUE(animalos__Deceased_Date__c) - animalos__Date_of_Birth__c), 365.25) / 30.44)) &amp; &apos; Months &apos; &amp;
    TEXT(FLOOR(MOD(MOD((DATEVALUE(animalos__Deceased_Date__c) - animalos__Date_of_Birth__c), 365.25), 30.44))) &amp; &apos; Days&apos;,
    NULL
  ),
  IF(
    NOT(ISBLANK(animalos__Date_of_Birth__c)),
    TEXT(FLOOR((TODAY() - animalos__Date_of_Birth__c) / 365.25)) &amp; &apos; Years &apos; &amp;
    TEXT(FLOOR(MOD((TODAY() - animalos__Date_of_Birth__c), 365.25) / 30.44)) &amp; &apos; Months &apos; &amp;
    TEXT(FLOOR(MOD(MOD((TODAY() - animalos__Date_of_Birth__c), 365.25), 30.44))) &amp; &apos; Days&apos;,
    NULL
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Weight__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Weight__c</fullName>
    <label>Current Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Gender__c.field-meta.xml
<CustomField>
    <fullName>animalos__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>animalos__Microchip_Number__c</fullName>
    <label>Microchip Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Neutered_Spayed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Neutered_Spayed_Date_Time__c</fullName>
    <label>Neutered/Spayed Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Colour__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Colour__c</fullName>
    <label>Primary Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agouti</fullName>
            </value>
            <value>
                <fullName>Albino</fullName>
            </value>
            <value>
                <fullName>Appaloosa</fullName>
            </value>
            <value>
                <fullName>Apricot</fullName>
            </value>
            <value>
                <fullName>Badgerface</fullName>
            </value>
            <value>
                <fullName>Bay</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Belton</fullName>
            </value>
            <value>
                <fullName>Birchen</fullName>
            </value>
            <value>
                <fullName>Biscuit</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Black Brindle</fullName>
            </value>
            <value>
                <fullName>Black Brown</fullName>
            </value>
            <value>
                <fullName>Black Otter</fullName>
            </value>
            <value>
                <fullName>Black Tan</fullName>
            </value>
            <value>
                <fullName>Blenheim</fullName>
            </value>
            <value>
                <fullName>Blonde</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Blue Bicolour</fullName>
            </value>
            <value>
                <fullName>Blue Black</fullName>
            </value>
            <value>
                <fullName>Blue Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Cream Tortoiseshell</fullName>
            </value>
            <value>
                <fullName>Blue Eyed White</fullName>
            </value>
            <value>
                <fullName>Blue Fawn</fullName>
            </value>
            <value>
                <fullName>Blue Fawn Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Marten</fullName>
            </value>
            <value>
                <fullName>Blue Merle</fullName>
            </value>
            <value>
                <fullName>Blue Otter</fullName>
            </value>
            <value>
                <fullName>Blue Point</fullName>
            </value>
            <value>
                <fullName>Blue Roan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Secondary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Secondary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Secondary Breed)</relationshipLabel>
    <relationshipName>Animals_Secondary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Secondary_Colour__c.field-meta.xml
<CustomField>
    <fullName>animalos__Secondary_Colour__c</fullName>
    <label>Secondary Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agouti</fullName>
            </value>
            <value>
                <fullName>Albino</fullName>
            </value>
            <value>
                <fullName>Appaloosa</fullName>
            </value>
            <value>
                <fullName>Apricot</fullName>
            </value>
            <value>
                <fullName>Badgerface</fullName>
            </value>
            <value>
                <fullName>Bay</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Belton</fullName>
            </value>
            <value>
                <fullName>Birchen</fullName>
            </value>
            <value>
                <fullName>Biscuit</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Black Brindle</fullName>
            </value>
            <value>
                <fullName>Black Brown</fullName>
            </value>
            <value>
                <fullName>Black Otter</fullName>
            </value>
            <value>
                <fullName>Black Tan</fullName>
            </value>
            <value>
                <fullName>Blenheim</fullName>
            </value>
            <value>
                <fullName>Blonde</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Blue Bicolour</fullName>
            </value>
            <value>
                <fullName>Blue Black</fullName>
            </value>
            <value>
                <fullName>Blue Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Cream Tortoiseshell</fullName>
            </value>
            <value>
                <fullName>Blue Eyed White</fullName>
            </value>
            <value>
                <fullName>Blue Fawn</fullName>
            </value>
            <value>
                <fullName>Blue Fawn Brindle</fullName>
            </value>
            <value>
                <fullName>Blue Marten</fullName>
            </value>
            <value>
                <fullName>Blue Merle</fullName>
            </value>
            <value>
                <fullName>Blue Otter</fullName>
            </value>
            <value>
                <fullName>Blue Point</fullName>
            </value>
            <value>
                <fullName>Blue Roan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Shelter_ID__c.field-meta.xml
<CustomField>
    <fullName>animalos__Shelter_ID__c</fullName>
    <label>Shelter ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Location__c/animalos__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Location__c/fields/aos_Postcode__c.field-meta.xml
<CustomField>
    <fullName>aos_Postcode__c</fullName>
    <label>Postcode</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/aos_Site_Phone__c.field-meta.xml
<CustomField>
    <fullName>aos_Site_Phone__c</fullName>
    <label>Site Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/aos_State__c.field-meta.xml
<CustomField>
    <fullName>aos_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
                <isActive>false</isActive>
                <label>QLD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/aos_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>aos_Street_Address__c</fullName>
    <label>Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Location__c/fields/aos_Suburb__c.field-meta.xml
<CustomField>
    <fullName>aos_Suburb__c</fullName>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Postcode__c/aos_Postcode__c.object-meta.xml
<CustomObject>
    <description>Reference list of QLD Postcodes</description>
    <label>Postcode</label>
    <nameField>
        <label>Postcode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Postcode__c/fields/aos_Postcode__c.field-meta.xml
<CustomField>
    <fullName>aos_Postcode__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_Postcode__c/fields/aos_State__c.field-meta.xml
<CustomField>
    <fullName>aos_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Australian_States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/aos_Postcode__c/fields/aos_Suburb__c.field-meta.xml
<CustomField>
    <fullName>aos_Suburb__c</fullName>
    <complianceGroup>Not Categorized</complianceGroup>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/aos_DesexedCertificateQAMetaProc.cls
public class aos_DesexedCertificateQAMetaProc  extends aos_MetadataProcessor {

    public override aos_Response process(aos_Request request) {
        this.request = request == null ? new aos_MetadataProcessor.MetadataRequest() : (aos_MetadataProcessor.MetadataRequest) request;

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        String animalId = this.request.getRequiredString('animalId');

        List<Object> components = new List<Object>();

        List<animalos__Animal__c> animals = [
                SELECT
                    Id
                    ,Name
                    ,animalos__Animal_Name__c
                    ,animalos__Calculated_Age__c
                    ,animalos__Current_Site__c
                    ,animalos__Current_Site__r.Name
                    ,animalos__Current_Site__r.aos_Postcode__c
                    ,animalos__Current_Site__r.aos_Site_Phone__c
                    ,animalos__Current_Site__r.aos_State__c
                    ,animalos__Current_Site__r.aos_Street_Address__c
                    ,animalos__Current_Site__r.aos_Suburb__c
                    ,animalos__Current_Weight__c
                    ,animalos__Gender__c
                    ,animalos__Microchip_Number__c
                    ,animalos__Neutered_Spayed_Date_Time__c
                    ,animalos__Primary_Breed__r.Name
                    ,animalos__Primary_Colour__c
                    ,animalos__Secondary_Breed__r.Name
                    ,animalos__Secondary_Colour__c
                    ,animalos__Shelter_ID__c
                    ,animalos__Type__c
                    ,aos_Crossbreed__c
                    ,aos_Neutered_Spayed_By__c
                    ,aos_Neutered_Spayed_By__r.Name
                FROM animalos__Animal__c
                WHERE Id = :animalId
        ];

        String fileName;

        for (animalos__Animal__c animal : animals) {

            Map<String, Object> dto = new Map<String, Object>();

            dto.put('animal', animal);

            components.add(new Component.aos_DesexedCertificate(
                dto = dto
            ));

            if (fileName == null) {
                fileName = 'Desexed Certificate - ' + animal.Name;
            } else {
                fileName += '_' + animal.Name;
            }
        }

        fileName = fileName.left(80);

        if (ApexPages.currentPage() != null) {
            ApexPages.currentPage()
                    .getHeaders()
                    .put('content-disposition', 'filename=' + fileName + '.pdf');
        }

        this.response.dto.put('components', components);
        this.response.dto.put('head-component', new Component.aos_DesexedCertificateStyles());
    }
}