force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Gender__c.field-meta.xml
<CustomField>
    <fullName>animalos__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Primary_Breed__c.field-meta.xml
<CustomField>
    <fullName>animalos__Primary_Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Breed</label>
    <referenceTo>animalos__Breed__c</referenceTo>
    <relationshipLabel>Animals (Primary Breed)</relationshipLabel>
    <relationshipName>Animals_Primary_Breed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Indemnity_Waiver__c/animalos__Animal_Indemnity_Waiver__c.object-meta.xml
<CustomObject>
    <label>Animal Indemnity Waiver</label>
    <nameField>
        <displayFormat>AIW{00000}</displayFormat>
        <label>Animal Indemnity Waiver ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Indemnity Waivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Indemnity_Waiver__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Indemnity Waivers</relationshipLabel>
    <relationshipName>Animal_Indemnity_Waivers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Indemnity_Waiver__c/fields/animalos__Indemnity_Waiver__c.field-meta.xml
<CustomField>
    <fullName>animalos__Indemnity_Waiver__c</fullName>
    <label>Indemnity Waiver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>animalos__Indemnity_Waiver__c.animalos__Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>animalos__Indemnity_Waiver__c</referenceTo>
    <relationshipLabel>Animal Indemnity Waivers</relationshipLabel>
    <relationshipName>Animal_Indemnity_Waivers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Breed__c/animalos__Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Breed__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Indemnity_Waiver__c/animalos__Indemnity_Waiver__c.object-meta.xml
<CustomObject>
    <label>Indemnity Waiver</label>
    <nameField>
        <label>Indemnity Waiver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indemnity Waivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Indemnity_Waiver__c/fields/animalos__Content__c.field-meta.xml
<CustomField>
    <fullName>animalos__Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Indemnity_Waiver__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Behaviour</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/aos_IndemnityWaiverDocumentQAMetaTest.cls
@IsTest
private class aos_IndemnityWaiverDocumentQAMetaTest {
    @IsTest
    static void testBehavior() {

        animalos__Breed__c animalBreed = new animalos__Breed__c(
            animalos__Type__c = 'Dog',
            Name = 'Test Breed'
        );
        insert animalBreed;


        animalos__Animal__c animal = new animalos__Animal__c(
            animalos__Gender__c = 'Male',
            animalos__Primary_Breed__c = animalBreed.Id
        );
        insert animal;

        animalos__Indemnity_Waiver__c indemnityWaiver = new animalos__Indemnity_Waiver__c(
            Name = 'Test',
            animalos__Content__c = 'Test'
        );
        insert indemnityWaiver;

        animalos__Animal_Indemnity_Waiver__c animalIndemnityWaiver = new animalos__Animal_Indemnity_Waiver__c(
            animalos__Indemnity_Waiver__c = indemnityWaiver.Id,
            animalos__Animal__c = animal.Id
        );
        insert animalIndemnityWaiver;

        vertic_Response response = new IndemnityWaiverDocumentQAMetaProc().process(new Map<String, Object>{
            'recordId' => animal.Id
        });

        System.assert(response.isValid);
    }
}