force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Site Animals</relationshipLabel>
    <relationshipName>Site_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Incoming_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Incoming_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incoming Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipLabel>Incoming Animals</relationshipLabel>
    <relationshipName>Incoming_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Outgoing_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Outgoing_Site__c</fullName>
    <label>Outgoing Site</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/animalos__Animal_Referral__c.object-meta.xml
<CustomObject>
    <label>Animal Referral</label>
    <nameField>
        <displayFormat>AR{00000}</displayFormat>
        <label>Animal Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Referral__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Animal Referrals</relationshipLabel>
    <relationshipName>Animal_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Referral__c/animalos__Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Referral__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Home Inspection</fullName>
            </value>
            <value>
                <fullName>Veterinary Check</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Trial Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Adopted Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Input</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/animalos__Status_Tracking__c.object-meta.xml
<CustomObject>
    <label>Status Tracking</label>
    <nameField>
        <displayFormat>ST{00000}</displayFormat>
        <label>Status Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Status Tracking</relationshipLabel>
    <relationshipName>Status_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Animal_Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Referral</label>
    <referenceTo>animalos__Animal_Referral__c</referenceTo>
    <relationshipLabel>Status Tracking</relationshipLabel>
    <relationshipName>Status_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Animal_Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Status__c</fullName>
    <label>Animal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Animal_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Type__c</fullName>
    <label>Animal Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Current_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Current_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipName>Current_Site_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Generic_Status_Tracking__c.field-meta.xml
<CustomField>
    <fullName>animalos__Generic_Status_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Generic Status Tracking</label>
    <referenceTo>animalos__Status_Tracking__c</referenceTo>
    <relationshipLabel>Monthly Status Tracking Records</relationshipLabel>
    <relationshipName>Monthly_Status_Tracking_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Incoming_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Incoming_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incoming Site</label>
    <referenceTo>animalos__Location__c</referenceTo>
    <relationshipName>Incoming_Site_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Month__c.field-meta.xml
<CustomField>
    <fullName>animalos__Month__c</fullName>
    <label>Month</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Outgoing_Site__c.field-meta.xml
<CustomField>
    <fullName>animalos__Outgoing_Site__c</fullName>
    <label>Outgoing Site</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Referral__c.field-meta.xml
<CustomField>
    <fullName>animalos__Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral</label>
    <referenceTo>animalos__Referral__c</referenceTo>
    <relationshipLabel>Status Tracking</relationshipLabel>
    <relationshipName>Status_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Status_Tracking__c/fields/animalos__Year__c.field-meta.xml
<CustomField>
    <fullName>animalos__Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecreateMonthlyStatusTrackingBatch.cls
global class RecreateMonthlyStatusTrackingBatch extends vertic_AbstractProcessor implements Database.Batchable<SObject> {

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        if (!this.request.has('recordId') && !this.request.has('animalId') && !this.request.has('recordIds')) {
            throw new vertic_Structs.MissingDataException('Provide either Animal Id or Generic Status Tracking Id(s)');
        }

        List<animalos__Status_Tracking__c> records = [
                SELECT Id, animalos__Start_Date_Time__c, animalos__End_Date_Time__c, animalos__Animal__c, animalos__Animal_Status__c, animalos__Stage__c,
                        animalos__Referral__c, animalos__Animal_Referral__c, animalos__Incoming_Site__c, animalos__Current_Site__c, animalos__Outgoing_Site__c, animalos__Animal_Type__c
                FROM animalos__Status_Tracking__c
                WHERE (Id = :this.request.getString('recordId')
                OR Id IN :this.request.getListAsStrings('recordIds')
                OR animalos__Animal__c = :this.request.getString('animalId'))
                AND RecordType.DeveloperName = 'Generic'
        ];

        this.run(records);
        return this.response;
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(this.query);
    }

    public String query = 'SELECT Id, animalos__Start_Date_Time__c, animalos__End_Date_Time__c, animalos__Animal__c, animalos__Animal_Status__c, animalos__Stage__c,animalos__Referral__c, ' +
            'animalos__Animal_Referral__c, animalos__Incoming_Site__c, animalos__Current_Site__c, animalos__Outgoing_Site__c, animalos__Animal_Type__c ' +
            'FROM animalos__Status_Tracking__c ' +
            'WHERE RecordType.DeveloperName = \'Generic\' AND animalos__Start_Date_Time__c != NULL ' +
            'ORDER BY animalos__Animal__c';

    public RecreateMonthlyStatusTrackingBatch setQuery(String query) {
        this.query = query;
        return this;
    }

    public void execute(Database.BatchableContext BC, List<SObject> records) {
        if (records[0].getSObjectType() == animalos__Animal__c.SObjectType) {
            this.run([
                    SELECT Id, animalos__Start_Date_Time__c, animalos__End_Date_Time__c, animalos__Animal__c, animalos__Animal_Status__c, animalos__Stage__c, animalos__Referral__c, animalos__Animal_Referral__c, animalos__Incoming_Site__c, animalos__Current_Site__c, animalos__Outgoing_Site__c, animalos__Animal_Type__c
                    FROM animalos__Status_Tracking__c
                    WHERE RecordType.DeveloperName = 'Generic'
                    AND animalos__Start_Date_Time__c != NULL
                    AND animalos__Animal__c IN :records
                    ORDER BY animalos__Animal__c
            ]);
        } else if (records[0].getSObjectType() == animalos__Status_Tracking__c.SObjectType) {
            this.run((List<animalos__Status_Tracking__c>) records);
        } else {
            throw new vertic_Structs.MissingDataException('Invalid SObject Type');
        }
    }

    public void run(List<animalos__Status_Tracking__c> genericStatusTrackingRecords) {
        try {
            animalos.TDTM.getTriggerSObjectTypeEvent(animalos__Status_Tracking__c.SObjectType).disableAll();

            delete [
                    SELECT Id
                    FROM animalos__Status_Tracking__c
                    WHERE RecordType.DeveloperName = 'Monthly' AND animalos__Generic_Status_Tracking__c IN :genericStatusTrackingRecords
            ];

            List<animalos__Status_Tracking__c> monthlyStatusTrackingRecordsForInsert = new List<animalos__Status_Tracking__c>();
            String monthlyRecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Status_Tracking__c.SObjectType, 'Monthly');

            for (animalos__Status_Tracking__c genericStatusTrackingRecord : genericStatusTrackingRecords) {
                Datetime startDateTime = genericStatusTrackingRecord.animalos__Start_Date_Time__c;
                Datetime endDateTime = genericStatusTrackingRecord.animalos__End_Date_Time__c;
                Datetime startDateTimeEndOfMonth = Datetime.newInstance(startDateTime.year(), startDateTime.month(), Date.daysInMonth(startDateTime.year(), startDateTime.month()), 23, 59, 59).addSeconds(1);

                if (endDateTime == null && 'Out'.equalsIgnoreCase(genericStatusTrackingRecord.animalos__Stage__c) && startDateTimeEndOfMonth < Datetime.now()) {
                    endDateTime = startDateTimeEndOfMonth;
                }

                List<Map<String, Datetime>> monthsMap = vertic_Utils.dates.splitToMonths(startDateTime, endDateTime);

                for (Map<String, Object> monthMap : monthsMap) {
                    animalos__Status_Tracking__c statusTracking = new animalos__Status_Tracking__c(
                            animalos__Animal__c = genericStatusTrackingRecord.animalos__Animal__c,
                            animalos__Animal_Status__c = genericStatusTrackingRecord.animalos__Animal_Status__c,
                            animalos__Stage__c = genericStatusTrackingRecord.animalos__Stage__c,
                            animalos__Referral__c = genericStatusTrackingRecord.animalos__Referral__c,
                            animalos__Animal_Referral__c = genericStatusTrackingRecord.animalos__Animal_Referral__c,
                            animalos__Incoming_Site__c = genericStatusTrackingRecord.animalos__Incoming_Site__c,
                            animalos__Current_Site__c = genericStatusTrackingRecord.animalos__Current_Site__c,
                            animalos__Outgoing_Site__c = genericStatusTrackingRecord.animalos__Outgoing_Site__c,
                            animalos__Animal_Type__c = genericStatusTrackingRecord.animalos__Animal_Type__c,
                            animalos__Year__c = String.valueOf(((Datetime) monthMap.get('start')).year()),
                            animalos__Month__c = String.valueOf(((Datetime) monthMap.get('start')).month()),
                            animalos__Start_Date_Time__c = (Datetime) monthMap.get('start'),
                            animalos__End_Date_Time__c = (Datetime) monthMap.get('end'),
                            animalos__Generic_Status_Tracking__c = genericStatusTrackingRecord.Id,
                            RecordTypeId = monthlyRecordTypeId
                    );

                    monthlyStatusTrackingRecordsForInsert.add(statusTracking);
                }
            }

            insert monthlyStatusTrackingRecordsForInsert;
        } catch (Exception ex) {
            insert new animalos.Logging().setGroup('Status Tracking')
                    .addDetails(ex)
                    .setType('Error')
                    .setProcess('RecreateMonthlyStatusTrackingBatch')
                    .build();
        }
    }

    public void finish(Database.BatchableContext BC) {

    }
}