force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/aos_Gallery_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>aos_Gallery_Updated_Date__c</fullName>
    <label>Gallery Updated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/aos_Async_Process__c/aos_Async_Process__c.object-meta.xml
<CustomObject>
    <label>AOS Async Process</label>
    <nameField>
        <displayFormat>VAP-{000000000}</displayFormat>
        <label>Vertic Async Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOS Async Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_Async_Process__c/fields/aos_Group_Key__c.field-meta.xml
<CustomField>
    <fullName>aos_Group_Key__c</fullName>
    <label>Group Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/aos_OneDrive_File__c.object-meta.xml
<CustomObject>
    <label>OneDrive File</label>
    <nameField>
        <label>OneDrive File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OneDrive Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Animal__c.field-meta.xml
<CustomField>
    <fullName>aos_Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>OneDrive Files</relationshipLabel>
    <relationshipName>OneDrive_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>aos_Folder_Name__c</fullName>
    <label>Folder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/aos_OneDrive_File__c/fields/aos_Is_Public__c.field-meta.xml
<CustomField>
    <fullName>aos_Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OneDriveFileDomain.cls
public without sharing class OneDriveFileDomain extends fflib_SObjectDomain implements fflib_ISObjectDomain {

    public OneDriveFileDomain(List <sObject> sObjectList) {
        super(sObjectList);
        this.Configuration.disableTriggerCRUDSecurity();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new OneDriveFileDomain(sObjectList);
        }
    }

    public override void onBeforeInsert() {
    }

    public override void onAfterInsert() {
        this.updateAnimalGalleryUpdatedDate(this.Records);
        this.uploadAnimalToPetRescue(this.Records, null);
    }

    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
    }

    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
        this.updateAnimalGalleryUpdatedDate(this.Records);
        this.uploadAnimalToPetRescue(this.Records, existingRecords);
        this.sendDeletedOneDriveFileId(this.Records, existingRecords);
    }

    private void updateAnimalGalleryUpdatedDate(List<sObject> records) {
        Set<Id> animalIds = vertic_Utils.sObjects.getIdFieldValues(
                records,
                aos_OneDrive_File__c.aos_Animal__c
        );

        List<animalos__Animal__c> animalsForUpdate = new List<animalos__Animal__c>();

        for (animalos__Animal__c animal : [
                SELECT Id
                FROM animalos__Animal__c
                WHERE Id IN :animalIds
        ]) {
            animal.aos_Gallery_Updated_Date__c = Date.today();

            animalsForUpdate.add(animal);
        }

        update animalsForUpdate;
    }

    private void uploadAnimalToPetRescue(List<sObject> records, Map<Id, sObject> existingRecords) {

        Set<Id> animalIds = new Set<Id>();

        for (aos_OneDrive_File__c oneDriveFile : (List<aos_OneDrive_File__c>) records) {
            Boolean isCreated = Trigger.isInsert && existingRecords == null;
            Boolean isUpdated = Trigger.isUpdate && existingRecords != null && existingRecords.get(oneDriveFile.Id) != null &&
                    vertic_Utils.sObjects.isSomeFieldChanged(
                            oneDriveFile,
                            existingRecords.get(oneDriveFile.Id),
                            new List<sObjectField>{
                                    aos_OneDrive_File__c.aos_Is_Public__c,
                                    aos_OneDrive_File__c.aos_Is_Deleted__c,
                                    aos_OneDrive_File__c.aos_Is_Primary__c
                            }
                    );

            if (((isCreated && (oneDriveFile.aos_Is_Public__c || oneDriveFile.aos_Is_Primary__c) && !oneDriveFile.aos_Is_Deleted__c) || isUpdated)
                    && oneDriveFile.aos_Animal__c != null
                    && String.isNotBlank(oneDriveFile.aos_Folder_Name__c) && oneDriveFile.aos_Folder_Name__c.containsIgnoreCase('photos')) {
                animalIds.add(oneDriveFile.aos_Animal__c);
            }
        }

        if (!animalIds.isEmpty()) {
            List<animalos__Animal__c> animals = new List<animalos__Animal__c>();

            for (Id animalId : animalIds) {
                animals.add(new animalos__Animal__c(Id = animalId));
            }

            TDTM_aos_AnimalPostToPetRescue.uploadToPetRescueIgnoringUpdateConditions = true;
            update animals;
        }
    }

    private void sendDeletedOneDriveFileId(List<sObject> records, Map<Id, sObject> existingRecords) {
        vertic_AsyncProcess verticAsyncProcess = new vertic_AsyncProcess();

        for (aos_OneDrive_File__c oneDriveFile : (List<aos_OneDrive_File__c>) records) {
            Boolean isUpdated = existingRecords != null && existingRecords.get(oneDriveFile.Id) != null &&
                    vertic_Utils.sObjects.isSomeFieldChanged(
                            oneDriveFile,
                            existingRecords.get(oneDriveFile.Id),
                            new List<SObjectField>{
                                    aos_OneDrive_File__c.aos_Is_Deleted__c,
                                    aos_OneDrive_File__c.aos_Is_Public__c
                            }
                    );

            if (isUpdated && (oneDriveFile.aos_Is_Deleted__c || !oneDriveFile.aos_Is_Public__c)) {
                aos_Async_Process__c vap = vertic_AsyncProcess.create(
                        SendDeletedOneDriveFileIdProc.class,
                        new Map<String, Object>{
                                'recordId' => oneDriveFile.Id
                        }
                );
                vap.aos_Group_Key__c = oneDriveFile.Id;

                verticAsyncProcess.add(vap);
            }
        }

        verticAsyncProcess.enqueue();
    }
}