force-app/main/default/objects/animalos__Animal_Action__c/animalos__Animal_Action__c.object-meta.xml
<CustomObject>
    <label>Animal Action</label>
    <nameField>
        <displayFormat>AA{00000}</displayFormat>
        <label>Animal Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Medicine_Used__c/animalos__Medicine_Used__c.object-meta.xml
<CustomObject>
    <label>Medicine Used</label>
    <nameField>
        <displayFormat>MU{00000}</displayFormat>
        <label>Medicine Used ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medicines Used</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Medicine_Used__c/fields/animalos__Animal_Action__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Action</label>
    <referenceTo>animalos__Animal_Action__c</referenceTo>
    <relationshipLabel>Medicines Used (Animal Action)</relationshipLabel>
    <relationshipName>Medicines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MigrateActionUsedInBatch.cls
global class MigrateActionUsedInBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, animalos__Action_Used_In__c\n' +
                'FROM animalos__Medicine_Used__c\n' +
                'WHERE animalos__Animal_Action__c = NULL AND animalos__Action_Used_In__c != NULL');
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        for (animalos__Medicine_Used__c medicineUsed : (List<animalos__Medicine_Used__c>) scope) {
//            medicineUsed.animalos__Animal_Action__c = medicineUsed.animalos__Action_Used_In__c;
        }

       update scope;
    }

    global void finish(Database.BatchableContext BC) {
    }

}