force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Address__c.field-meta.xml
<CustomField>
    <fullName>animalos__Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Full_Address__c.field-meta.xml
<CustomField>
    <fullName>animalos__Full_Address__c</fullName>
    <formula>IF( NOT(ISBLANK(animalos__Address__Street__s)), animalos__Address__Street__s &amp; &apos;, &apos;, &apos;&apos;) &amp; animalos__Address__City__s &amp; &apos;, &apos; &amp; TEXT(animalos__Address__StateCode__s) &amp; &apos; &apos; &amp; animalos__Address__PostalCode__s &amp; &apos; &apos; &amp; TEXT(animalos__Address__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/animalos__Resource__c/animalos__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Resource__c/fields/animalos__User__c.field-meta.xml
<CustomField>
    <fullName>animalos__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Resource__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/animalos__Resource_Skill__c/animalos__Resource_Skill__c.object-meta.xml
<CustomObject>
    <label>Resource Skill</label>
    <nameField>
        <displayFormat>RS{00000}</displayFormat>
        <label>Resource Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Resource_Skill__c/fields/animalos__Resource__c.field-meta.xml
<CustomField>
    <fullName>animalos__Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>animalos__Resource__c</referenceTo>
    <relationshipLabel>Resource Skills</relationshipLabel>
    <relationshipName>Resource_Skills</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Resource_Skill__c/fields/animalos__Skill__c.field-meta.xml
<CustomField>
    <fullName>animalos__Skill__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Skill</label>
    <referenceTo>animalos__Skill__c</referenceTo>
    <relationshipLabel>Resource Skills</relationshipLabel>
    <relationshipName>Assigned_Resources</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Skill__c/animalos__Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ResourcesNearbyMetaProc.cls
public class ResourcesNearbyMetaProc extends vertic_MetadataProcessor implements Database.AllowsCallouts {

    Set<String> resourceFields = new Set<String>{
            'Id',
            'animalos__Contact__r.Id',
            'animalos__Contact__r.Name',
            'animalos__Contact__r.Account.Name',
            'animalos__Contact__r.Phone',
            'animalos__Contact__r.Email',
            'animalos__Contact__r.MobilePhone',
            'Current_Location__c'
    };

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        super.process(this.request);

        this.doInit();

        return this.response;
    }

    private void doInit() {
        String recordId = this.request.getRequiredString('recordId');

        animalos__Job__c jobVar = (animalos__Job__c) vertic_Utils.arrays.firstOrException([
                SELECT Id, animalos__Full_Address__c, animalos__Address__c
                FROM animalos__Job__c
                WHERE Id = :recordId
                AND animalos__Address__Latitude__s != NULL
                AND animalos__Address__Longitude__s != NULL
                LIMIT 1
        ]);

        Decimal distance = this.request.getDecimal('distance') == null ? 1 : this.request.getDecimal('distance');
        Address jobVarAddress = jobVar.animalos__Address__c;
        List<String> conditions = new List<String>{
                '(DISTANCE(Current_Location__c, :jobVarAddress, \'km\') < :distance)',
                'animalos__Active__c = true',
                'animalos__User__c != null'
        };

        String selectedSkills = this.request.getString('selectedSkills');
        List<String> selectedSkillsList = new List<String>();
        if (String.isNotBlank(selectedSkills)) {
            selectedSkillsList = selectedSkills.split(';');
        }

        fflib_QueryFactory resourcesSOQL = new fflib_QueryFactory(animalos__Resource__c.SObjectType)
                .selectFields(this.resourceFields)
                .setCondition(String.join(conditions, ' AND '));


        resourcesSOQL.subselectQuery(animalos__Resource_Skill__c.SObjectType)
                .selectFields(new Set<String>{
                        'Name',
                        'animalos__Skill__r.Name'
                });


        List<animalos__Resource__c> resources = Database.queryWithBinds(resourcesSOQL.toSOQL(), new Map<String, Object>{
                'jobVarAddress' => jobVarAddress,
                'distance' => distance
        }, AccessLevel.USER_MODE);

        List<animalos__Resource__c> resourcesToRender = new List<animalos__Resource__c>();

        for (animalos__Resource__c res : resources) {
            if (!selectedSkillsList.isEmpty()) {
                Boolean hasSkills = res.animalos__Resource_Skills__r != null && !res.animalos__Resource_Skills__r.isEmpty();

                if (hasSkills) {
                    Set<String> existingSkillsNames = new Set<String>();

                    for (animalos__Resource_Skill__c resSkill : res.animalos__Resource_Skills__r) {
                        existingSkillsNames.add(resSkill.animalos__Skill__r.Name);
                    }

                    for (String skillName : selectedSkillsList) {
                        if (!existingSkillsNames.contains(skillName)) {
                            hasSkills = false;
                            break;
                        }
                    }
                }

                if (hasSkills) {
                    resourcesToRender.add(res);
                }
            } else {
                resourcesToRender.add(res);
            }
        }

        this.response.addSelectOptions('skillsOptions', vertic_Utils.sObjects.toSelectOptions([SELECT Id, Name FROM animalos__Skill__c], 'Name', 'Name'));
        this.response.getMapper().mapAnyValue('resources', resourcesToRender);
    }
}