force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Priority__c.field-meta.xml
<CustomField>
    <fullName>animalos__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>No Incident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/aos_Sync_with_Case_Priority__c.field-meta.xml
<CustomField>
    <fullName>aos_Sync_with_Case_Priority__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Sync with Case Priority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TDTM_JobSetSyncWithCasePriority.cls
global class TDTM_JobSetSyncWithCasePriority extends animalos.TDTM.Handler implements animalos.TDTM.BeforeUpdate {
    public static Boolean triggeredFromRecordPage = true;
    public void onBeforeUpdate(List<SObject> records, Map<Id, SObject> oldMap) {
        if (records.size() == 1 && triggeredFromRecordPage) {
            this.setSyncWithCasePriority(records, oldMap);
        }
    }

    private void setSyncWithCasePriority(List<SObject> records, Map<Id, SObject> existingRecords) {
        for (animalos__Job__c jobVar : (List<animalos__Job__c>) records) {
            Boolean isUpdatedFromUi = Url.getCurrentRequestUrl()?.toExternalForm()?.contains('RecordUi.updateRecord=1');
            Boolean isUpdated = vertic_Utils.sObjects.isSomeFieldChanged(
                    jobVar,
                    existingRecords.get(jobVar.Id),
                    new List<SObjectField>{
                            animalos__Job__c.animalos__Priority__c
                    }
            );

            if (isUpdated && isUpdatedFromUi && String.isNotBlank(jobVar.animalos__Priority__c)) {
                jobVar.aos_Sync_with_Case_Priority__c = false;
            }
        }
    }
}