force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/aos_Person_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>aos_Person_Of_Interest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Of Interest</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs (Person Of Interest)</relationshipLabel>
    <relationshipName>aos_Jobs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/animalos__Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC{0000000}</displayFormat>
        <label>Job Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Contact_Jobs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact_Type__c</fullName>
    <label>Contact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Informant</fullName>
            </value>
            <value>
                <fullName>Informant Secondary</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Person Of Interest</fullName>
            </value>
            <value>
                <fullName>POI Secondary</fullName>
            </value>
            <value>
                <fullName>Police Officer</fullName>
            </value>
            <value>
                <fullName>Rescuer</fullName>
            </value>
            <value>
                <fullName>Spoken to</fullName>
            </value>
            <value>
                <fullName>Subject animal owner</fullName>
            </value>
            <value>
                <fullName>Subject property owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>Witness Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TDTM_aos_JobContactSetJobPOI.cls
global class TDTM_aos_JobContactSetJobPOI extends animalos.TDTM.Handler implements animalos.TDTM.AfterInsert, animalos.TDTM.AfterUpdate {

    public void onAfterInsert(List<SObject> records) {
        this.TDTM_JobContactSetJobPOI(records);
    }

    public void onAfterUpdate(List<SObject> records, Map<Id, SObject> existingRecords) {
        this.TDTM_JobContactSetJobPOI(records);
    }

    private void TDTM_JobContactSetJobPOI(List<sObject> records) {
        Map<Id, animalos__Job__c> jobsByIds = new Map<Id, animalos__Job__c>();

        for (animalos__Job_Contact__c jobContact : (List<animalos__Job_Contact__c>) records) {

            if ('Person Of Interest'.equalsIgnoreCase(jobContact.animalos__Contact_Type__c)) {
                jobsByIds.put(jobContact.animalos__Job__c, new animalos__Job__c(
                        Id = jobContact.animalos__Job__c,
                        aos_Person_of_Interest__c = jobContact.animalos__Contact__c
                ));
            }
        }

        if (!jobsByIds.isEmpty()) {
            animalos.TDTM.getTriggerSObjectTypeEvent(animalos__Job__c.SObjectType).disableAll();
            update jobsByIds.values();
            animalos.TDTM.getTriggerSObjectTypeEvent(animalos__Job__c.SObjectType).enableAll();
        }
    }
}