force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Location_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location_Of_Interest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Of Interest</label>
    <referenceTo>animalos__Location_Of_Interest__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Animal Welfare</fullName>
            </value>
            <value>
                <fullName>Animal Welfare - Intel</fullName>
            </value>
            <value>
                <fullName>Animal Welfare - Referred Externally</fullName>
            </value>
            <value>
                <fullName>Proactive Job</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/animalos__Location_Of_Interest__c.object-meta.xml
<CustomObject>
    <label>Location Of Interest</label>
    <nameField>
        <label>Location Of Interest</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Resource__c/animalos__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Resource__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inspectorate</fullName>
            </value>
            <value>
                <fullName>Rescue</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Trap</fullName>
            </value>
            <value>
                <fullName>Crate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Resource__c/fields/aos_Status__c.field-meta.xml
<CustomField>
    <fullName>aos_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ManageTrapsQAMetaProc.cls
public class ManageTrapsQAMetaProc extends vertic_MetadataProcessor {

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new vertic_MetadataProcessor.MetadataRequest() : (vertic_MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                animalos__Resource__c.aos_Status__c
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        String recordId = this.request.getRequiredString('recordId');

        animalos__Job__c job = (animalos__Job__c) vertic_Utils.arrays.firstOrException([
                SELECT Id, animalos__Location_Of_Interest__c
                FROM animalos__Job__c
                WHERE Id = :recordId
        ]);

        List<animalos__Resource__c> resources = [
                SELECT Id, Name
                FROM animalos__Resource__c
                WHERE animalos__Type__c = 'Trap' AND aos_Status__c = 'Available'
        ];

        this.response.put('locationOfInterestId', job.animalos__Location_Of_Interest__c);
        this.response.getMapper().mapFromListSObjects('resources', resources);
    }
}