force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Location_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location_Of_Interest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Of Interest</label>
    <referenceTo>animalos__Location_Of_Interest__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/animalos__Job_Contact__c.object-meta.xml
<CustomObject>
    <label>Job Contact</label>
    <nameField>
        <displayFormat>JC{0000000}</displayFormat>
        <label>Job Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Contact_Jobs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Contact_Type__c</fullName>
    <label>Contact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Informant</fullName>
            </value>
            <value>
                <fullName>Informant Secondary</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Person Of Interest</fullName>
            </value>
            <value>
                <fullName>POI Secondary</fullName>
            </value>
            <value>
                <fullName>Police Officer</fullName>
            </value>
            <value>
                <fullName>Rescuer</fullName>
            </value>
            <value>
                <fullName>Spoken to</fullName>
            </value>
            <value>
                <fullName>Subject animal owner</fullName>
            </value>
            <value>
                <fullName>Subject property owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>Witness Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job_Contact__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Job Contacts</relationshipLabel>
    <relationshipName>Job_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/animalos__Location_Of_Interest__c.object-meta.xml
<CustomObject>
    <label>Location Of Interest</label>
    <nameField>
        <label>Location Of Interest</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/aos_AnimalWelfareFindExistingRecordsTest.cls
@IsTest
private class aos_AnimalWelfareFindExistingRecordsTest {
    @IsTest
    static void testBehavior() {
        animalos__Location_Of_Interest__c location = new animalos__Location_Of_Interest__c(
                animalos__Address__CountryCode__s = 'AU',
                animalos__Address__StateCode__s = 'NSW',
                animalos__Address__Street__s = '201 Rookwood Road'
        );
        insert location;

        animalos__Job__c job = new animalos__Job__c(
                animalos__Address__CountryCode__s = 'AU',
                animalos__Address__StateCode__s = 'NSW',
                animalos__Address__Street__s = '201 Rookwood Road',
                animalos__Location_Of_Interest__c = location.Id
        );
        insert job;

        Contact contactVar = new Contact(
                LastName = 'Test',
                MailingCountry = 'Australia',
                MailingState = 'NSW',
                MailingStreet = '201 Rookwood Road'
        );

        aos_Request request = new aos_Request();
        request.getMapper().mapFromSObject('jobContact', new animalos__Job_Contact__c(
                animalos__Contact__r = contactVar,
                animalos__Job__c = job.Id,
                animalos__Contact_Type__c = 'Informant'
        ));
        request.getMapper().mapFromSObject('job', job);

        aos_Response response = new aos_AnimalWelfareFindExistingRecords().process(request);

        System.assert(response.isValid);
    }
}