force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/aos_Case__c.field-meta.xml
<CustomField>
    <fullName>aos_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>aos_Jobs_AnimalOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Note__c/animalos__Job_Note__c.object-meta.xml
<CustomObject>
    <label>Job Note</label>
    <nameField>
        <displayFormat>JN{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Note__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Job Notes</relationshipLabel>
    <relationshipName>Job_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Note__c/fields/aos_Case__c.field-meta.xml
<CustomField>
    <fullName>aos_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Job Notes</relationshipLabel>
    <relationshipName>Job_Notes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDTM_JobNotePopulateJobField.cls
global class TDTM_JobNotePopulateJobField extends animalos.TDTM.Handler implements animalos.TDTM.BeforeInsert {
    public void onBeforeInsert(List<SObject> records) {
        this.populateJobField(records);
    }

    private void populateJobField(List<sObject> records) {

        Set<Id> caseIds = vertic_Utils.sObjects.getIdFieldValues(records, animalos__Job_Note__c.aos_Case__c);

        Map<String, sObject> jobsByCaseId = vertic_Utils.sObjects.getSObjectsByAnyFieldMap([
                SELECT Id, aos_Case__c, OwnerId, Name
                FROM animalos__Job__c
                WHERE aos_Case__c IN :caseIds
                ORDER BY CreatedDate ASC
        ], animalos__Job__c.aos_Case__c);

        for (animalos__Job_Note__c clientNote : (List<animalos__Job_Note__c>) records) {
            if (clientNote.aos_Case__c != null && clientNote.animalos__Job__c == null) {
                animalos__Job__c job = (animalos__Job__c) jobsByCaseId.get(clientNote.aos_Case__c);

                if (job != null) {
                    clientNote.animalos__Job__c = job.Id;
                }
            }
        }

    }
}