force-app/main/default/objects/animalos__Assigned_Resource__c/animalos__Assigned_Resource__c.object-meta.xml
<CustomObject>
    <label>Assigned Resource</label>
    <nameField>
        <displayFormat>AR{000000}</displayFormat>
        <label>Assigned Resource ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Assigned_Resource__c/fields/animalos__Job_Activity__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job_Activity__c</fullName>
    <label>Job Activity</label>
    <referenceTo>animalos__Job_Activity__c</referenceTo>
    <relationshipLabel>Assigned Resources</relationshipLabel>
    <relationshipName>Assigned_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Assigned_Resource__c/fields/animalos__Resource__c.field-meta.xml
<CustomField>
    <fullName>animalos__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>animalos__Resource__c</referenceTo>
    <relationshipLabel>Assigned Resources</relationshipLabel>
    <relationshipName>Assigned_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/animalos__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Location_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>animalos__Location_Of_Interest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Of Interest</label>
    <referenceTo>animalos__Location_Of_Interest__c</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Job__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Under Reg Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Recheck</fullName>
            </value>
            <value>
                <fullName>Pending Prosecution</fullName>
            </value>
            <value>
                <fullName>Awaiting Notification Response</fullName>
            </value>
            <value>
                <fullName>Awaiting Further Information</fullName>
            </value>
            <value>
                <fullName>Awaiting Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Re-Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Attendance</fullName>
            </value>
            <value>
                <fullName>In Attendance</fullName>
            </value>
            <value>
                <fullName>Working on Job</fullName>
            </value>
            <value>
                <fullName>Attended – CC left</fullName>
            </value>
            <value>
                <fullName>Attended – enquires continuing</fullName>
            </value>
            <value>
                <fullName>Departed Job</fullName>
            </value>
            <value>
                <fullName>Equipment Set</fullName>
            </value>
            <value>
                <fullName>Follow Up Required</fullName>
            </value>
            <value>
                <fullName>Awaiting AWD Compliance Check</fullName>
            </value>
            <value>
                <fullName>Covering Inspector -Assigned</fullName>
            </value>
            <value>
                <fullName>Covering Inspector – Awaiting Attendance</fullName>
            </value>
            <value>
                <fullName>Covering Inspector – Preliminary Enquiries Made</fullName>
            </value>
            <value>
                <fullName>Notes outstanding</fullName>
            </value>
            <value>
                <fullName>Pending Forfeiture Application</fullName>
            </value>
            <value>
                <fullName>Pending Forfeiture decision</fullName>
            </value>
            <value>
                <fullName>Pending FBOE</fullName>
            </value>
            <value>
                <fullName>Pending FBOE Application Decision</fullName>
            </value>
            <value>
                <fullName>Preliminary inquiries made</fullName>
            </value>
            <value>
                <fullName>Prosecution Commenced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job_Activity__c/animalos__Job_Activity__c.object-meta.xml
<CustomObject>
    <label>Job Activity</label>
    <nameField>
        <displayFormat>JA{000000}</displayFormat>
        <label>Job Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Job_Activity__c/fields/animalos__Job__c.field-meta.xml
<CustomField>
    <fullName>animalos__Job__c</fullName>
    <label>Job</label>
    <referenceTo>animalos__Job__c</referenceTo>
    <relationshipLabel>Job Activities</relationshipLabel>
    <relationshipName>Job_Activities2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Activity__c/fields/animalos__Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>animalos__Start_Date_Time__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/animalos__Job_Activity__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Monitoring Ended</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Update</fullName>
            </value>
            <value>
                <fullName>Ongoing Monitoring</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Search Active</fullName>
            </value>
            <value>
                <fullName>Search Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Job_Activity__c/fields/animalos__Type_of_Work__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type_of_Work__c</fullName>
    <label>Type of Work</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Recheck</fullName>
            </value>
            <value>
                <fullName>Call/SMS</fullName>
            </value>
            <value>
                <fullName>Email/Letter</fullName>
            </value>
            <value>
                <fullName>Brief Prep</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Attendance Safety Declaration</fullName>
            </value>
            <value>
                <fullName>Digital Information Request</fullName>
            </value>
            <value>
                <fullName>Digital Information Response</fullName>
            </value>
            <value>
                <fullName>Trap Deployment</fullName>
            </value>
            <value>
                <fullName>Investigation Plan</fullName>
            </value>
            <value>
                <fullName>Attended Property</fullName>
            </value>
            <value>
                <fullName>Sent Advisory Letter</fullName>
            </value>
            <value>
                <fullName>Sent Warning Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Location_Of_Interest__c/animalos__Location_Of_Interest__c.object-meta.xml
<CustomObject>
    <label>Location Of Interest</label>
    <nameField>
        <label>Location Of Interest</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Resource__c/animalos__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ManageTrapsQASubmitProc.cls
public class ManageTrapsQASubmitProc extends vertic_AbstractProcessor implements vertic_Structs.IRollbackable {

    public override vertic_Response process(vertic_Request request) {
        this.request = request;

        this.doSubmit();

        return this.response;
    }

    private void doSubmit() {
        String recordId = this.request.getRequiredString('recordId');
        animalos__Location_Of_Interest__c locationOfInterest = new animalos__Location_Of_Interest__c();
        this.request.getMapper().mapToSObject('locationOfInterest', locationOfInterest);
        List<animalos__Resource__c> resources = this.request.getMapper().mapToListSObjects('resources', animalos__Resource__c.SObjectType);
        List<animalos__Assigned_Resource__c> assignedResources = new List<animalos__Assigned_Resource__c>();

        animalos__Job__c job = (animalos__Job__c) vertic_Utils.arrays.firstOrException([
                SELECT Id
                FROM animalos__Job__c
                WHERE Id = :recordId
        ]);

        animalos__Job_Activity__c jobActivity = new animalos__Job_Activity__c(
                animalos__Job__c = job.Id,
                animalos__Status__c = 'In Progress',
                animalos__Address__CountryCode__s = locationOfInterest.animalos__Address__CountryCode__s,
                animalos__Address__City__s = locationOfInterest.animalos__Address__City__s,
                animalos__Address__Street__s = locationOfInterest.animalos__Address__Street__s,
                animalos__Address__PostalCode__s = locationOfInterest.animalos__Address__PostalCode__s,
                animalos__Address__StateCode__s = locationOfInterest.animalos__Address__StateCode__s,
                animalos__Start_Date_Time__c = Datetime.now(),
                animalos__Type_of_Work__c = 'Trap Deployment',
                RecordTypeId = vertic_Utils.sObjects.recordTypeIdByAPIName(animalos__Job_Activity__c.SObjectType, 'Trap')
        );
        insert jobActivity;

        for (animalos__Resource__c resource : resources) {
            animalos__Assigned_Resource__c assignedResource = new animalos__Assigned_Resource__c(
                    animalos__Job_Activity__c = jobActivity.Id,
                    animalos__Resource__c = resource.Id,
                    Trap_Status__c = resource.Status__c
            );
            assignedResources.add(assignedResource);
        }
        update resources;
        insert assignedResources;

        this.response.put('jobActivityId', jobActivity.Id);
    }

}