force-app/main/default/objects/animalos__Action_Plan__c/animalos__Action_Plan__c.object-meta.xml
<CustomObject>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Action_Plan__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Action_Plan__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nutrition</fullName>
            </value>
            <value>
                <fullName>Treatment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Action_Plan__c/fields/aos_Assign_To_Incoming_Animals__c.field-meta.xml
<CustomField>
    <fullName>aos_Assign_To_Incoming_Animals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assign To Incoming Animals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/animalos__Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Animal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Stage__c.field-meta.xml
<CustomField>
    <fullName>animalos__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intake</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Under Care</fullName>
            </value>
            <value>
                <fullName>Adoption Ready</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Status__c.field-meta.xml
<CustomField>
    <fullName>animalos__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adopted – Awaiting Pickup</fullName>
            </value>
            <value>
                <fullName>Adopted - Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Adopted – Offsite</fullName>
            </value>
            <value>
                <fullName>Adoption Pending/Hold on Property Check</fullName>
            </value>
            <value>
                <fullName>Available For Adoption</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Awaiting Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – In Foster</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – No Web Presence</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Offsite</fullName>
            </value>
            <value>
                <fullName>Available For Adoption – Waiting Space</fullName>
            </value>
            <value>
                <fullName>Awaiting Behavioural Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Evaluation</fullName>
            </value>
            <value>
                <fullName>Awaiting Behaviour Retest</fullName>
            </value>
            <value>
                <fullName>Awaiting Desex</fullName>
            </value>
            <value>
                <fullName>Awaiting Euthanasia</fullName>
            </value>
            <value>
                <fullName>Awaiting Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Rescue</fullName>
            </value>
            <value>
                <fullName>Awaiting Spay/Neuter – In Foster</fullName>
            </value>
            <value>
                <fullName>Awaiting Surgery – Not Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Awaiting Transfer</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage</fullName>
            </value>
            <value>
                <fullName>Awaiting Triage Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting Vet Exam/Health Check</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Offsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Off Site</fullName>
            </value>
            <value>
                <fullName>Bequest Animal Onsite</fullName>
            </value>
            <value>
                <fullName>Bequest Animal On Site</fullName>
            </value>
            <value>
                <fullName>Court Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal__c/fields/animalos__Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>animalos__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>animalos__Animal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action_Plan__c/animalos__Animal_Action_Plan__c.object-meta.xml
<CustomObject>
    <label>Animal Action Plan</label>
    <nameField>
        <displayFormat>AAP{00000}</displayFormat>
        <label>Animal Action Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Action_Plan__c/fields/animalos__Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>animalos__Action_Plan__c</fullName>
    <label>Action Plan</label>
    <referenceTo>animalos__Action_Plan__c</referenceTo>
    <relationshipLabel>Animal Action Plans</relationshipLabel>
    <relationshipName>Animal_Action_Plans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action_Plan__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Action Plans</relationshipLabel>
    <relationshipName>Animal_Action_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/aos_AssignToIncomingAnimalsService.cls
public class aos_AssignToIncomingAnimalsService {


    public static void handleAssignToIncomingAnimals(List<SObject> records) {
        handleAssignToIncomingAnimals(records, null);
    }

    public static void handleAssignToIncomingAnimals(List<SObject> records, Map<Id, sObject> existingRecords) {

        Set<String> animalsIds = new Set<String>();

        Map<String, List<animalos__Animal__c>> animalTypesMap = new Map<String, List<animalos__Animal__c>>();

        for (animalos__Animal__c animalItem : (List<animalos__Animal__c>) records) {
            if (animalItem.animalos__Stage__c != 'Pre-Intake' && animalItem.animalos__Stage__c != 'Out') {

                if (animalTypesMap.containsKey(animalItem.animalos__Type__c)) {
                    animalTypesMap.get(animalItem.animalos__Type__c).add(animalItem);
                } else {
                    animalTypesMap.put(animalItem.animalos__Type__c, new List<animalos__Animal__c> { animalItem });
                }

                animalsIds.add(animalItem.Id);
            }
        }

        if (animalTypesMap.isEmpty()) {
            return;
        }


        String animalTypesMultiSelectStr = String.join(new List<String>(animalTypesMap.keySet()), ',');

        Map<String, animalos__Action_Plan__c> actionPlansMap = new Map<String, animalos__Action_Plan__c>([
            SELECT Id, animalos__Animal_Type__c
            FROM animalos__Action_Plan__c
            WHERE animalos__Animal_Type__c INCLUDES (:animalTypesMultiSelectStr)
                AND aos_Assign_To_Incoming_Animals__c = TRUE
                AND animalos__Status__c = 'Active'
        ]);

        Map<String, List<SObject>> actionPlansByAnimalType = aos_Utils.sObjects.getSObjectsListByAnyFieldMap(
            actionPlansMap.values(),
            animalos__Action_Plan__c.animalos__Animal_Type__c
        );

        Map<String, Set<String>> existingAnimalActionPlansIdsByAnimal = new Map<String, Set<String>>();

        for (animalos__Animal_Action_Plan__c animalActionPlanItem : [
            SELECT animalos__Animal__c, animalos__Action_Plan__c
            FROM animalos__Animal_Action_Plan__c
            WHERE animalos__Animal__c IN :animalsIds
                AND animalos__Action_Plan__c IN :actionPlansMap.keySet()
                AND animalos__Active__c = TRUE
        ]) {

            if (existingAnimalActionPlansIdsByAnimal.containsKey(animalActionPlanItem.animalos__Animal__c)) {
                existingAnimalActionPlansIdsByAnimal.get(animalActionPlanItem.animalos__Animal__c).add(animalActionPlanItem.animalos__Action_Plan__c);
            } else {
                existingAnimalActionPlansIdsByAnimal.put(animalActionPlanItem.animalos__Animal__c, new Set<String> { animalActionPlanItem.animalos__Action_Plan__c });
            }
        }


        List<animalos__Animal_Action_Plan__c> animalActionPlansForCreate = new List<animalos__Animal_Action_Plan__c>();

        for (String actionPlanAnimalType : actionPlansByAnimalType.keySet()) {
            List<animalos__Action_Plan__c> actionPlans = (List<animalos__Action_Plan__c>) actionPlansByAnimalType.get(actionPlanAnimalType);

            List<String> actionPlanAnimalTypeList = actionPlanAnimalType.split(';');

            for (animalos__Action_Plan__c actionPlanItem : actionPlans) {

                for (String animalTypeItem : actionPlanAnimalTypeList) {

                    if (!animalTypesMap.containsKey(animalTypeItem)) continue;

                    for (animalos__Animal__c animalItem : animalTypesMap.get(animalTypeItem)) {

                        if (
                            isExcludeExistingAnimalActionPlans(existingAnimalActionPlansIdsByAnimal, animalItem.Id, actionPlanItem.Id) == true
                        ) continue;

                        animalActionPlansForCreate.add(
                            new animalos__Animal_Action_Plan__c(
                                animalos__Animal__c = animalItem.Id,
                                animalos__Action_Plan__c = actionPlanItem.Id,
                                animalos__Active__c = true,
                                animalos__Start_Date__c = Date.today()
                            )
                        );
                    }
                }
            }
        }

        if (!animalActionPlansForCreate.isEmpty()) {
            insert animalActionPlansForCreate;
        }
    }


    private static Boolean isExcludeExistingAnimalActionPlans(Map<String, Set<String>> existingAnimalActionPlansIdsByAnimal, String animalId, String actionPlanId) {

        return existingAnimalActionPlansIdsByAnimal != null
                && existingAnimalActionPlansIdsByAnimal.containsKey(animalId)
                && !existingAnimalActionPlansIdsByAnimal.get(animalId).isEmpty()
                && existingAnimalActionPlansIdsByAnimal.get(animalId).contains(actionPlanId);
    }
}