force-app/main/default/objects/animalos__Action_Plan__c/animalos__Action_Plan__c.object-meta.xml
<CustomObject>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Action_Plan__c/fields/animalos__Description__c.field-meta.xml
<CustomField>
    <fullName>animalos__Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action__c/animalos__Animal_Action__c.object-meta.xml
<CustomObject>
    <label>Animal Action</label>
    <nameField>
        <displayFormat>AA{00000}</displayFormat>
        <label>Animal Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Description__c.field-meta.xml
<CustomField>
    <fullName>animalos__Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Animal Actions</relationshipLabel>
    <relationshipName>Animal_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Action_Plan__c/animalos__Animal_Action_Plan__c.object-meta.xml
<CustomObject>
    <label>Animal Action Plan</label>
    <nameField>
        <displayFormat>AAP{00000}</displayFormat>
        <label>Animal Action Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Action_Plan__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Animal Action Plans</relationshipLabel>
    <relationshipName>Animal_Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Condition__c/animalos__Animal_Condition__c.object-meta.xml
<CustomObject>
    <label>Animal Condition</label>
    <nameField>
        <displayFormat>AC{00000}</displayFormat>
        <label>Animal Condition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Condition__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Animal Conditions</relationshipLabel>
    <relationshipName>Animal_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Note__c/animalos__Animal_Note__c.object-meta.xml
<CustomObject>
    <label>Animal Note</label>
    <nameField>
        <displayFormat>AN{00000}</displayFormat>
        <label>Animal Note ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Animal_Note__c/fields/animalos__Animal__c.field-meta.xml
<CustomField>
    <fullName>animalos__Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>animalos__Animal__c</referenceTo>
    <relationshipLabel>Animal Notes</relationshipLabel>
    <relationshipName>Animal_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Note__c/fields/animalos__Content__c.field-meta.xml
<CustomField>
    <fullName>animalos__Content__c</fullName>
    <label>Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/animalos__Animal_Note__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Animal Notes</relationshipLabel>
    <relationshipName>Animal_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Condition__c/animalos__Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Condition__c/fields/animalos__Consult_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Consult_Type__c</fullName>
    <label>Consult Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Medicine__c/animalos__Medicine__c.object-meta.xml
<CustomObject>
    <label>Medicine</label>
    <nameField>
        <label>Medicine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medicines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Medicine__c/fields/animalos__Consult_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Consult_Type__c</fullName>
    <label>Consult Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Black Tag Exam</fullName>
            </value>
            <value>
                <fullName>Cat/Kitten Castration</fullName>
            </value>
            <value>
                <fullName>Cat Flank Spey</fullName>
            </value>
            <value>
                <fullName>Cattle</fullName>
            </value>
            <value>
                <fullName>Community Outreach Initial Consult</fullName>
            </value>
            <value>
                <fullName>Dog/Puppy Castration</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Critical Distress Consultation</fullName>
            </value>
            <value>
                <fullName>Euthanasia - General</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Owner requested/Council requested</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Standard protocol exit point</fullName>
            </value>
            <value>
                <fullName>Fungassay Result: POSITIVE / NEGATIVE</fullName>
            </value>
            <value>
                <fullName>Hair Matting</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Bird</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Poultry</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Reptile</fullName>
            </value>
            <value>
                <fullName>Intake Check - Koala</fullName>
            </value>
            <value>
                <fullName>Koala Examination</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Pig Clinical Exam</fullName>
            </value>
            <value>
                <fullName>Pocket Pet Intake</fullName>
            </value>
            <value>
                <fullName>Rabbit Intake</fullName>
            </value>
            <value>
                <fullName>Routine Cat and Kitten SPEY/ Pregnant cat spey</fullName>
            </value>
            <value>
                <fullName>Sheep/Goat/Alpaca</fullName>
            </value>
            <value>
                <fullName>Wildlife Examination</fullName>
            </value>
            <value>
                <fullName>General Wildlife - Bird</fullName>
            </value>
            <value>
                <fullName>General Wildlife - Amphibian</fullName>
            </value>
            <value>
                <fullName>General Wildlife - Reptile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Medicine_Used__c/animalos__Medicine_Used__c.object-meta.xml
<CustomObject>
    <label>Medicine Used</label>
    <nameField>
        <displayFormat>MU{00000}</displayFormat>
        <label>Medicine Used ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medicines Used</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Medicine_Used__c/fields/animalos__Vet_Consult__c.field-meta.xml
<CustomField>
    <fullName>animalos__Vet_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vet Consult</label>
    <referenceTo>animalos__Vet_Consult__c</referenceTo>
    <relationshipLabel>Medicines Used</relationshipLabel>
    <relationshipName>Medicines_Used</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/animalos__Vet_Consult__c/animalos__Vet_Consult__c.object-meta.xml
<CustomObject>
    <label>Vet Consult</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Vet Consult ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vet Consults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/animalos__Vet_Consult__c/fields/animalos__Consult_Type__c.field-meta.xml
<CustomField>
    <fullName>animalos__Consult_Type__c</fullName>
    <label>Consult Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Black Tag Exam</fullName>
            </value>
            <value>
                <fullName>Cat/Kitten Castration</fullName>
            </value>
            <value>
                <fullName>Cat Flank Spey</fullName>
            </value>
            <value>
                <fullName>Cattle</fullName>
            </value>
            <value>
                <fullName>Community Outreach Initial Consult</fullName>
            </value>
            <value>
                <fullName>Dog/Puppy Castration</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Critical Distress Consultation</fullName>
            </value>
            <value>
                <fullName>Euthanasia - General</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Owner requested/Council requested</fullName>
            </value>
            <value>
                <fullName>Euthanasia - Standard protocol exit point</fullName>
            </value>
            <value>
                <fullName>Fungassay Result: POSITIVE / NEGATIVE</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Hair Matting</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Bird</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Poultry</fullName>
            </value>
            <value>
                <fullName>Intake Check - Domestic Reptile</fullName>
            </value>
            <value>
                <fullName>Intake Check - Koala</fullName>
            </value>
            <value>
                <fullName>Koala Examination</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Pig Clinical Exam</fullName>
            </value>
            <value>
                <fullName>Pocket Pet Intake</fullName>
            </value>
            <value>
                <fullName>Rabbit Intake</fullName>
            </value>
            <value>
                <fullName>Recheck</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Amphibian</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Bird</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Mammal</fullName>
            </value>
            <value>
                <fullName>Recheck Wildlife - Reptile</fullName>
            </value>
            <value>
                <fullName>Routine Cat and Kitten SPEY/ Pregnant cat spey</fullName>
            </value>
            <value>
                <fullName>Sheep/Goat/Alpaca</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/animalos__Vet_Consult__c/fields/animalos__Scheduled_Start__c.field-meta.xml
<CustomField>
    <fullName>animalos__Scheduled_Start__c</fullName>
    <label>Scheduled Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/aos_VetConsultationHistoryController.cls
public with sharing class aos_VetConsultationHistoryController {
    
    // Primary method that returns structured data including medicines
    @AuraEnabled(cacheable=true)
    public static List<VetConsultInfo> getVetConsultsWithMedicines(String animalId) {
        List<VetConsultInfo> result = new List<VetConsultInfo>();
        
        try {
            // Get basic vet consult data
            List<animalos__Vet_Consult__c> consults = [
                SELECT Id, 
                       Name,
                       animalos__Scheduled_Start__c,
                       CreatedBy.Name,
                       animalos__Consult_Type__c,
                       animalos__Description__c,
                       CreatedDate,
                       (SELECT Id, animalos__Content__c, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Notes__r 
                        ORDER BY CreatedDate ASC),
                       (SELECT Id, animalos__Condition__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Conditions__r 
                        ORDER BY CreatedDate ASC),
                       (SELECT Id, animalos__Action_Plan__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Action_Plans__r 
                        ORDER BY CreatedDate ASC)
                FROM animalos__Vet_Consult__c 
                WHERE animalos__Animal__c = :animalId
                ORDER BY animalos__Scheduled_Start__c DESC NULLS LAST, CreatedDate DESC
                LIMIT 100
            ];
            
            // Get Medicine Used records for all these consults
            Map<Id, List<MedicineInfo>> medicinesByConsult = new Map<Id, List<MedicineInfo>>();
            if (!consults.isEmpty()) {
                Set<Id> consultIds = new Set<Id>();
                for (animalos__Vet_Consult__c consult : consults) {
                    consultIds.add(consult.Id);
                }
                medicinesByConsult = getMedicinesByConsult(consultIds);
            }
            
            // Process each consult
            for (animalos__Vet_Consult__c consult : consults) {
                VetConsultInfo info = new VetConsultInfo();
                info.id = consult.Id;
                info.name = consult.Name;
                info.scheduledStart = consult.animalos__Scheduled_Start__c;
                info.vetName = consult.CreatedBy?.Name;
                info.consultType = consult.animalos__Consult_Type__c;
                info.description = consult.animalos__Description__c;
                info.createdDate = consult.CreatedDate;
                
                // Process related records
                info.animalNotes = new List<Map<String, Object>>();
                if (consult.animalos__Animal_Notes__r != null) {
                    for (animalos__Animal_Note__c note : consult.animalos__Animal_Notes__r) {
                        info.animalNotes.add(new Map<String, Object>{
                            'id' => note.Id,
                            'content' => note.animalos__Content__c,
                            'createdDate' => note.CreatedDate,
                            'createdBy' => note.CreatedBy?.Name
                        });
                    }
                }
                
                info.conditions = new List<Map<String, Object>>();
                if (consult.animalos__Animal_Conditions__r != null) {
                    for (animalos__Animal_Condition__c condition : consult.animalos__Animal_Conditions__r) {
                        info.conditions.add(new Map<String, Object>{
                            'id' => condition.Id,
                            'name' => condition.animalos__Condition__r?.Name,
                            'createdDate' => condition.CreatedDate,
                            'createdBy' => condition.CreatedBy?.Name
                        });
                    }
                }
                
                info.actionPlans = new List<Map<String, Object>>();
                if (consult.animalos__Animal_Action_Plans__r != null) {
                    for (animalos__Animal_Action_Plan__c plan : consult.animalos__Animal_Action_Plans__r) {
                        info.actionPlans.add(new Map<String, Object>{
                            'id' => plan.Id,
                            'name' => plan.animalos__Action_Plan__r?.Name,
                            'createdDate' => plan.CreatedDate,
                            'createdBy' => plan.CreatedBy?.Name
                        });
                    }
                }
                
                // Get medicines from our map
                info.medicinesUsed = new List<Map<String, Object>>();
                if (medicinesByConsult.containsKey(consult.Id)) {
                    for (MedicineInfo medicine : medicinesByConsult.get(consult.Id)) {
                        info.medicinesUsed.add(new Map<String, Object>{
                            'id' => medicine.id,
                            'name' => medicine.name,
                            'createdDate' => medicine.createdDate,
                            'createdBy' => medicine.createdBy
                        });
                    }
                }
                
                result.add(info);
            }
        } catch (Exception e) {
            System.debug('Error fetching vet consultation records with medicines: ' + e.getMessage());
            return new List<VetConsultInfo>();
        }
        
        return result;
    }
    
    // Legacy method - kept for backward compatibility
    @AuraEnabled(cacheable=true)
    public static List<animalos__Vet_Consult__c> getVetConsults(String animalId) {
        try {
            return [
                SELECT Id, 
                       Name,
                       animalos__Scheduled_Start__c,
                       CreatedBy.Name,
                       animalos__Consult_Type__c,
                       animalos__Description__c,
                       CreatedDate,
                       (SELECT Id, animalos__Content__c, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Notes__r 
                        ORDER BY CreatedDate ASC),
                       (SELECT Id, animalos__Condition__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Conditions__r 
                        ORDER BY CreatedDate ASC),
                       (SELECT Id, animalos__Action_Plan__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Action_Plans__r 
                        ORDER BY CreatedDate ASC)
                FROM animalos__Vet_Consult__c 
                WHERE animalos__Animal__c = :animalId
                ORDER BY animalos__Scheduled_Start__c DESC NULLS LAST, CreatedDate DESC
                LIMIT 100
            ];
        } catch (Exception e) {
            System.debug('Error fetching vet consultation records: ' + e.getMessage());
            return new List<animalos__Vet_Consult__c>();
        }
    }
    
    // Helper method to get medicines used through Animal Action
    private static Map<Id, List<MedicineInfo>> getMedicinesByConsult(Set<Id> consultIds) {
        Map<Id, List<MedicineInfo>> medicinesByConsult = new Map<Id, List<MedicineInfo>>();
        
        try {
            // Query Animal Actions linked to these vet consults
            List<animalos__Animal_Action__c> actions = [
                SELECT Id, animalos__Vet_Consult__c,
                       (SELECT Id, animalos__Medicine__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Medicines__r
                        ORDER BY CreatedDate ASC)
                FROM animalos__Animal_Action__c
                WHERE animalos__Vet_Consult__c IN :consultIds
            ];
            
            for (animalos__Animal_Action__c action : actions) {
                Id consultId = action.animalos__Vet_Consult__c;
                if (!medicinesByConsult.containsKey(consultId)) {
                    medicinesByConsult.put(consultId, new List<MedicineInfo>());
                }
                
                if (action.animalos__Medicines__r != null) {
                    for (animalos__Medicine_Used__c medicine : action.animalos__Medicines__r) {
                        medicinesByConsult.get(consultId).add(new MedicineInfo(
                            medicine.Id,
                            medicine.animalos__Medicine__r?.Name,
                            medicine.CreatedDate,
                            medicine.CreatedBy?.Name
                        ));
                    }
                }
            }
        } catch (Exception e) {
            System.debug('Error getting medicines: ' + e.getMessage());
        }
        
        return medicinesByConsult;
    }
    
    // Wrapper class for medicine information
    public class MedicineInfo {
        @AuraEnabled public String id;
        @AuraEnabled public String name;
        @AuraEnabled public DateTime createdDate;
        @AuraEnabled public String createdBy;
        
        public MedicineInfo(String id, String name, DateTime createdDate, String createdBy) {
            this.id = id;
            this.name = name != null ? name : 'Unknown medicine';
            this.createdDate = createdDate;
            this.createdBy = createdBy != null ? createdBy : 'Unknown user';
        }
    }
    
    // Wrapper class for complete vet consult information
    public class VetConsultInfo {
        @AuraEnabled public String id;
        @AuraEnabled public String name;
        @AuraEnabled public DateTime scheduledStart;
        @AuraEnabled public String vetName;
        @AuraEnabled public String consultType;
        @AuraEnabled public String description;
        @AuraEnabled public DateTime createdDate;
        @AuraEnabled public List<Map<String, Object>> animalNotes;
        @AuraEnabled public List<Map<String, Object>> conditions;
        @AuraEnabled public List<Map<String, Object>> actionPlans;
        @AuraEnabled public List<Map<String, Object>> medicinesUsed;
    }
    
    // Helper method to debug what fields are available on child objects
    @AuraEnabled
    public static Map<String, Object> debugRelatedRecords(String vetConsultId) {
        Map<String, Object> debugInfo = new Map<String, Object>();
        
        try {
            // Get the vet consult with all relationships we found
            List<animalos__Vet_Consult__c> consults = [
                SELECT Id, 
                       (SELECT Id, animalos__Content__c, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Notes__r),
                       (SELECT Id, animalos__Condition__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Conditions__r),
                       (SELECT Id, animalos__Action_Plan__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Animal_Action_Plans__r)
                FROM animalos__Vet_Consult__c 
                WHERE Id = :vetConsultId
                LIMIT 1
            ];
            
            if (!consults.isEmpty()) {
                animalos__Vet_Consult__c consult = consults[0];
                debugInfo.put('animalNotes', consult.animalos__Animal_Notes__r);
                debugInfo.put('conditions', consult.animalos__Animal_Conditions__r);
                debugInfo.put('actionPlans', consult.animalos__Animal_Action_Plans__r);
            }
            
            // Get medicines through Animal Action
            List<animalos__Animal_Action__c> actions = [
                SELECT Id, animalos__Vet_Consult__c,
                       (SELECT Id, animalos__Medicine__r.Name, CreatedDate, CreatedBy.Name
                        FROM animalos__Medicines__r)
                FROM animalos__Animal_Action__c
                WHERE animalos__Vet_Consult__c = :vetConsultId
            ];
            
            debugInfo.put('animalActions', actions);
            
        } catch (Exception e) {
            debugInfo.put('error', e.getMessage());
        }
        
        return debugInfo;
    }
    
    // Helper method to get correct child relationship names - can be used for testing
    @AuraEnabled
    public static Map<String, String> getChildRelationshipNames() {
        Map<String, String> relationships = new Map<String, String>();
        
        // Get describe information for Vet Consult to find correct child relationship names
        Schema.DescribeSObjectResult vetConsultDescribe = animalos__Vet_Consult__c.SObjectType.getDescribe();
        List<Schema.ChildRelationship> childRelationships = vetConsultDescribe.getChildRelationships();
        
        for (Schema.ChildRelationship rel : childRelationships) {
            String childObjectName = rel.getChildSObject().getDescribe().getName();
            String relationshipName = rel.getRelationshipName();
            
            if (childObjectName.contains('Animal_Condition') || 
                childObjectName.contains('Animal_Action_Plan') || 
                childObjectName.contains('Medicine_Used') ||
                childObjectName.contains('Animal_Note') ||
                childObjectName.contains('Animal_Action')) {
                relationships.put(childObjectName, relationshipName);
            }
        }
        
        return relationships;
    }
}